version: "3.7"

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch-dina:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    extra_hosts:
      # Resolve the Keycloak domain to Keycloak's static IP:
      - "${KEYCLOAK_DOMAIN}:${KEYCLOAK_IP}"
    ports:
      - 9200:9200
      - 9300:9300
    labels:
      - "traefik.http.routers.elasticsearch.rule=Host(`${ELASTICSEARCH_DOMAIN}`)"
  # Check the status of elasticsearch and configure indices if not already present.
  elastic-configurator:
    build: ../repos/dina-search-api/es-init-container
    environment:
      ELASTIC_SERVER_URL: http://elasticsearch-dina:9200
      INDEX_CREATE_CMD: ./create-index.sh
      DINA_INDEX_DECLARATIONS: AGENT MATERIAL_SAMPLE STORAGE OBJECT_STORE
      DINA_DOCUMENT_INDEX_NAME: dina_document_index
      DINA_AGENT_INDEX_NAME: dina_agent_index      
      DINA_MATERIAL_SAMPLE_INDEX_NAME: dina_material_sample_index
      DINA_STORAGE_INDEX_NAME: dina_storage_index
      DINA_OBJECT_STORE_INDEX_NAME: dina_object_store_index
      DINA_DOCUMENT_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/default-document-index/dina_document_index_settings.json
      DINA_AGENT_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/agent-index/dina_agent_index_settings.json
      DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/collection-index/dina_material_sample_index_settings.json
      DINA_STORAGE_INDEX_SETTINGS_FILE: usr/share/elastic-configurator/settings/storage-index/dina_storage_index_settings.json
      DINA_OBJECT_STORE_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/object-store-index/object_store_index_settings.json
    volumes:
      - ./elastic-configurator-settings:/usr/share/elastic-configurator/settings
    depends_on:
      - elasticsearch-dina
  search-cli:
    build: ../repos/dina-search-api/search-cli
    environment:
      ELASTICSEARCH_URL: elasticsearch-dina
      MATERIAL_SAMPLE_URL: http://collection-api:8080/api/v1/material-sample
      METADATA_URL: http://objectstore-api:8080/api/v1/metadata
      ORGANIZATION_URL: http://agent-api:8080/api/v1/organization
      PERSON_URL: http://agent-api:8080/api/v1/person
      RABBITMQ_HOSTNAME: rabbitmq
      IS_MESSAGE_CONSUMER: "true"
      IS_MESSAGE_PRODUCER: "true"
      keycloak.openid_auth_server: http://${KEYCLOAK_DOMAIN}/auth/realms/dina/protocol/openid-connect/token
      keycloak.client_id: dina
      keycloak.username: admin
      keycloak.password: admin
    stdin_open: true
    tty: true
    extra_hosts:
      # Resolve the Keycloak domain to Keycloak's static IP:
      - "${KEYCLOAK_DOMAIN}:${KEYCLOAK_IP}"

volumes:
  elasticsearch-data:
    driver: local
  elastic-configurator-settings:
    driver: local     