env:
  global:
    - CC_TEST_REPORTER_ID=1adf2f4c3169570205e0702dc0166037e02880f128a2bfd74d2f6102f89f699f
language: node_js
node_js:
  - "11"
before_script:
  # Setup the test coverage reporter.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run test:coverage
after_script:
  # Submit the test coverage report.
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: script
    script: bash docker-push-prod.sh
    on:
      branch: master
      tags: true
  - provider: script
    script: bash docker-push-dev.sh
    on:
      branch: dev
