env:
  global:
    - CC_TEST_REPORTER_ID=1adf2f4c3169570205e0702dc0166037e02880f128a2bfd74d2f6102f89f699f
language: node_js
node_js:
  - "11"
cache: npm
before_script:
  # Setup the test coverage reporter.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run test:coverage
after_script:
  # Format seqdb-ui coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.client.json packages/seqdb-ui/coverage/lcov.info
  # Sum coverage parts into coverage/codeclimate.json
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
  # Upload coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
