import { COMMON_UI_MESSAGES_ENGLISH } from "common-ui";

/**
 * English Object Store messages. A message must be set here in English before other languages.
 */
export const OBJECTSTORE_MESSAGES_ENGLISH = {
  ...COMMON_UI_MESSAGES_ENGLISH,
  addManagedAttributeButtonText: "Add New Managed Attribute",
  appTitle: "Object Store",
  attributeLabel: "Attribute",
  closePreviewButtonText: "Close Preview",
  editSelectedButtonText: "Edit Selected",
  field_acCaption: "Caption",
  field_acDigitizationDate: "Date Original Version Created",
  field_acHashFunction: "Hash Function",
  field_acHashValue: "Hash",
  "field_acMetadataCreator.displayName": "Agent (Uploaded By)",
  field_acTags: "Tags",
  field_dcFormat: "Media Format",
  field_dcRights: "Rights Statement",
  field_dcType: "Object Type",
  field_managedAttributeType: "Type",
  field_originalFilename: "Original Filename",
  field_xmpMetadataDate: "Date Metadata Applied",
  field_xmpRightsWebStatement: "Reuse Rights Statement",
  managedAttributeListTitle: "Managed Attributes",
  managedAttributeValueLabel: "Value",
  metadataAgentLabel: "Agent (Uploaded By)",
  metadataBucketNameLabel: "Bucket Name",
  metadataBuiltInAttributesLabel: "Built-in Attributes",
  metadataBulkEditTagsLabel: "Tags (Comma-separated)",
  metadataBulkEditTitle: "Edit Metadata",
  metadataDcFormatLabel: "DcFormat",
  metadataDetailsPageLink: "Details Page",
  metadataFileExtensionLabel: "File Extension",
  metadataFileIdentifierLabel: "File Identifier",
  metadataFilenameLabel: "File Name",
  metadataFirstDigitalVersionCreatedDateLabel:
    "First Digital Version Created Date",
  metadataFormTitle: "Metadata",
  metadataHashFunctionLabel: "Hash Function",
  metadataHashValueLabel: "Hash Value",
  metadataLastMetadataModificationTimeLabel: "Last Metadata Modification Time",
  metadataListGalleryLayout: "Gallery",
  metadataListTableLayout: "Table",
  metadataManagedAttributesLabel: "Managed Attributes",
  metadataObjectTypeLabel: "Stored Object Type",
  metadataTagsLabel: "Tags",
  noFileToDisplay: "No file to display",
  objectListTitle: "Stored Objects",
  objectStoreDetailsTitle: "Object Store Details",
  uploadButtonText: "Upload",
  uploadFormInstructions:
    "Drag and drop files here or click to open browse dialog. Only image, audio, video, .pdf, .doc and docx are accepted.",
  uploadPageTitle: "Upload Files",
  viewPreviewButtonText: "Preview"
};
