import { COMMON_UI_MESSAGES_ENGLISH } from "common-ui";

/**
 * English SeqDB messages. A message must be set here in English before other languages.
 */
export const SEQDB_MESSAGES_ENGLISH = {
  ...COMMON_UI_MESSAGES_ENGLISH,
  addPcrPrimerTitle: "Add PCR Primer",
  addPcrProfileTitle: "Add Thermocycler Profile",
  addProductTitle: "Add Product",
  addProtocolTitle: "Add Protocol",
  addRegionTitle: "Add Region",
  addWorkflowTitle: "Add NGS Workflow",
  appTitle: "Sequence Database",
  availableSamplesTitle: "Available Samples",
  backToListButtonText: "Back to List",
  cancelButtonText: "Cancel",
  createButtonText: "Create New",
  deselectAllCheckedSamplesButtonText: "<-- Deselect all checked samples",
  deselectButtonText: "Deselect",
  editableTable: "Editable Table",
  editPcrPrimerTitle: "Edit PCR Primer",
  editPcrProfileTitle: "Edit Thermocycler Profile",
  editProductTitle: "Edit Product",
  editProtocolTitle: "Edit Protocol",
  editRegionTitle: "Edit Region",
  editWorkflowTitle: "Edit NGS Workflow",
  field_averageFragmentSize: "Average Fragment Size",
  field_concentration: "Concentration",
  field_inputAmount: "Input Amount",
  field_name: "Name",
  field_notes: "Notes",
  field_quality: "Quality",
  "field_sample.name": "Sample Name",
  field_targetDpSize: "Target Dp Size",
  indexSetListTitle: "Index Sets",
  notShearedStatus: "Not Sheared",
  notSizeSelectedStatus: "No Size Selection",
  pcrPrimerListTitle: "PCR Primers",
  pcrPrimerViewTitle: "PCR Primer",
  pcrProfileListTitle: "Thermocycler Profiles",
  pcrProfileViewTitle: "Thermocycler Profile",
  plpDetailsFormTitle: "Add New Shearing/Size Selection Details",
  plpEditModeLabel: "Edit",
  plpShearingModeLabel: "Shearing Details",
  plpSizeModeLabel: "Size Selection Details",
  plpStepTitle: "Shearing/Size Selection",
  plpViewModeSelectorLabel: "View mode: ",
  productListTitle: "Products",
  productUpcFieldHelpText:
    "Note: Universal Product Code can be read from barcode scanner in keyboard mode",
  productViewTitle: "Product",
  protocolListTitle: "Protocols",
  protocolViewTitle: "Protocol",
  regionListTitle: "Regions",
  regionViewTitle: "Region",
  removeShearingDetailsButtonText: "Remove selected Shearing details",
  removeSizeSelectionDetailsButtonText:
    "Remove selected Size Selection details",
  sampleSelectionTitle: "Sample Selection",
  selectAllCheckedSamplesButtonText: "Select all checked samples -->",
  selectButtonText: "Select",
  selectedSamplesTitle: "Selected Samples",
  shearedStatus: "Sheared",
  shearingLabel: "Shearing",
  sizeSelectedStatus: "Size Selection Added",
  sizeSelectionLabel: "Size Selection",
  workflowDetailsTab: "Details",
  workflowListTitle: "NGS Workflows",
  workflowStepTab: "Step {number}: {name}",
  workflowViewTitle: "NGS Workflow"
};
