version: "3.7"
services:
  api:
    image: maven:3.6.3-jdk-8
    # Run as Docker host user so generated files don't belong to root:
    user: $UID:$GID
    volumes:
      - "../repos/objectstore-api:/app"
      # Share host users:
      - "/etc/group:/etc/group:ro"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/shadow:/etc/shadow:ro"
      # Use the host maven repository:
      - "~/.m2:/var/maven/.m2"
    ports:
      - "8080:8080" # app port
      - "5005:5005" # debug port
    # The maven container ignores the docker-compose "environment" field, so pass in variables in the command:
    command: >
      bash -c "
      mvn
      -f /app/pom.xml
      -Duser.home=/var/maven
      -Dspring-boot-maven-plugin.fork=true
      -Dspring-boot.run.jvmArguments=\"
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Dspring.datasource.url=jdbc:postgresql://database/objectstore?currentSchema=objectstore
        -Dspring.datasource.username=postgres
        -Dspring.datasource.password=p
        -Dspring.datasource.continue-on-error=true
        -Dspring.liquibase.user=postgres
        -Dspring.liquibase.password=p
        -Dspring.servlet.multipart.max-file-size=2GB
        -Dspring.servlet.multipart.max-request-size=2GB
        -Dminio.host=minio
        -Dminio.port=9000
        -Dminio.accessKey=minio
        -Dminio.secretKey=minio123
      \"
      spring-boot:run
      "
  # Dev app that hot-reloads the UI source code:
  ui-dev-server:
    image: node:12.16.1
    volumes:
      - "../repos/dina-ui:/dina-ui"
      # Share host home directory for yarn cache:
      - /home/${USER}:/home/${USER}
      # Share host users:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    # Run as Docker host user so generated files don't belong to root:
    user: $UID:$GID
    stop_signal: SIGKILL
    command: >
      bash -c "
      yarn --cwd=/dina-ui/packages/objectstore-ui ;
      yarn --cwd=/dina-ui/packages/objectstore-ui next
      "
  # Front-end gateway that proxies URLs to the correct service:
  ui:
    image: abiosoft/caddy:1.0.3-no-stats
    volumes:
      - "./ui.Caddyfile:/etc/Caddyfile"
    environment:
      UI_DEV_SERVER_ADDRESS: ui-dev-server:3000
      API_ADDRESS: api:8080
    ports:
      - "2015:2015"
