/**
 * English common-ui messages. A message must be set here in English before other languages.
 */
export const COMMON_UI_MESSAGES_ENGLISH = {
  AND: "AND",
  IS: "IS",
  ISNOT: "IS NOT",
  OR: "OR",
  actions: "Actions",
  add: "Add",
  addNew: "Add New",
  agricultureCanada: "Agriculture and Agri-Food Canada",
  areYouSure: "Are you sure?",
  attached: "Attached",
  attributeLabel: "Attribute",
  autoFillGeoSuggestLabel:
    "Auto-fill Location Fields (This search box's value is not persisted)",
  backToList: "Back to list page",
  backToReadOnlyPage: "Back to read-only page",
  bulkEditorValidationError: "Invalid value on row {row}: {value}",
  cancelButtonText: "Cancel",
  checkAll: "Check All",
  checkAllTooltipMessage:
    "Check this header box to check all visible items in this page.",
  closeButtonText: "Close",
  collapse: " Collapse",
  configureLabel: "Configure",
  created: "created",
  createNew: "Create New",
  date: "Date",
  dateMustBeFormattedYyyyMmDd: "Date must be formatted as YYYY-MM-DD",
  deleteAllButtonText: "Delete All",
  deleteButtonText: "Delete",
  description: "Description",
  destroyedLabel: "Destroyed",
  detach: "Detach",
  done: "Done",
  dropdownSearchResults: "Search results",
  editButtonText: "Edit",
  editableTable: "Editable Table",
  errorPageTitle: "Error",
  existing: "Existing",
  expand: "Expand",
  false: "False",
  field_address: "Address",
  field_author: "Author",
  field_changedProperties: "Changed Properties",
  field_commitDateTime: "Commit Date and Time",
  field_familyNames: "Family Names",
  field_givenNames: "Given Names",
  field_group: "Group",
  field_resourceName: "Resource Name",
  field_snapshotType: "Snapshot Type",
  field_version: "Version",
  filterBetween: "BETWEEN",
  filterBlankField: "Blank Field",
  filterExactMatch: "Exact Match",
  filterFrom: "FROM",
  filterGreaterThan: "Greater Than",
  filterLessThan: "Less Than",
  filterPartialMatch: "Partial Match",
  filterRecordsTitle: "Filter records",
  filterSubmitButtonText: "Filter List",
  filterUntil: "UNTIL",
  geoSuggest: "Geo-Suggest",
  geoSuggestTooltip:
    "This button shows some suggested geo-locations based on what you've typed into the field.",
  hasError: "Has error",
  invalidDate: "Invalid Date",
  jumpToPage: "jump to page",
  rowsPerPage: "rows per page",
  languageOfPage: "eng",
  loadingText: "Loading...",
  loggedInAsUser: "Logged in as:",
  logoutBtn: "Logout",
  max: "Max",
  min: "Min",
  name: "Name",
  next: "Next",
  no: "No",
  noRowsFound: "No Rows Found",
  none: "None",
  of: "of",
  oneValuePerLine: "One value per line",
  oneValuePerLineTooltip:
    "Write one value per line. Press enter while typing in the field to add a new line.",
  page: "Page",
  previous: "Previous",
  queryTable: "Query Table",
  queryTableMultiSortExplanation:
    "To sort by multiple columns: Click one column header to sort by that column, then press shift while you click an additional header.",
  queryTableMultiSortTooltipTitle: "Multi-column sorting",
  remarks: "Remarks",
  remove: "Remove",
  resetButtonText: "Reset",
  resetSort: "Reset Sort",
  results: " Results",
  rows: "rows",
  search: "Search",
  searchResults: "Search results",
  select: "Select",
  selectLocation: "Select Location",
  selected: "selected",
  showChanges: "Show Changes",
  somethingWentWrong: "Something went wrong",
  sourceField: "Source Field",
  sourceText: "Source Text",
  startLabel: "Start",
  stepLabel: "Step",
  subjectTermsForPage:
    "government information, scientific information, scientific research",
  submitBtnText: "Save",
  tableTotalCount: "Total matched records: {totalCount}",
  targetField: "Target Field",
  text: "Text",
  to: "To",
  true: "True",
  typeHereToSearch: "Type here to search.",
  typeToSearchOrChooseFromNewest: "Type to search or choose from newest",
  uiAppVersion: "UI Application Version: {version}",
  valueLabel: "Value",
  valueSourceType: "Value Source Type",
  viewDetails: "View Details",
  warning: "Warning",
  yes: "Yes"
};
