import { COMMON_UI_MESSAGES_ENGLISH } from "./common-ui-en";

export const COMMON_UI_MESSAGES_GERMAN: Partial<
  typeof COMMON_UI_MESSAGES_ENGLISH
> = {
  AND: "UND",
  IS: "IST",
  ISNOT: "IST NICHT",
  OR: "ODER",
  actions: "Aktionen",
  add: "Hinzufügen",
  addNew: "Neu hinzufügen",
  agricultureCanada: "Canadische Landwirtschaft",
  areYouSure: "Sind Sie sicher?",
  attached: "anhängen",
  attributeLabel: "Attribut",
  autoFillGeoSuggestLabel:
    "Standortfelder (automatisch befüllt, Inhalt ist nicht beständig)",
  backToList: "Zurück zur Trefferliste",
  backToReadOnlyPage: "Zurück zur schreibgeschützten Seite",
  bulkEdit: "Bearbeitung der Gruppe",
  bulkEditorValidationError: "Fehlerhafte Eingabe in Zeile {row} : {value}",
  bulkSubmissionErrorInfo:
    "fehlerhafte Eingabe: Bitte prüfen Sie die Felder mit roter Kennzeichnung.",
  cancelButtonText: "Annullieren",
  checkAll: "Alle prüfen",
  checkAllTooltipMessage:
    "Prüfen Sie dieses Überschriftenfeld, um alle sichtbaren Elemente auf dieser Seite zu prüfen.",
  closeButtonText: "Schließen",
  collapse: "Zusammenklappen",
  configureLabel: "Konfigurieren",
  createNew: "neue anlegen",
  created: "angelegt",
  date: "Datum",
  dateMustBeFormattedYyyyMmDd:
    "Bitte das Datum in folgendem Format angeben: YYYY-MM-DD",
  dateMustBeFormattedPartial: "Muss partiell formatiert werden",
  deleteAllButtonText: "Alle löschen",
  deleteButtonText: "Löschen",
  deleteSelectedButtonText: "Auswahl löschen",
  description: "Beschreibung",
  destroyedLabel: "zerstört",
  detach: "Trennen",
  done: "Erledigt",
  dropdownSearchResults: "Suchergebnisse",
  editAll: "Alle bearbeiten",
  editButtonText: "Bearbeiten",
  editSelectedButtonText: "Ausgewählte bearbeiten",
  editableTable: "Tabelle bearbeiten",
  edited: "Bearbeitet",
  errorPageTitle: "Fehler",
  existing: "Vorhanden",
  expand: "Erweitern",
  false: "FALSCH",
  field_address: "Adresse",
  field_author: "Verfasser",
  field_changedProperties: "Geänderte Eigenschaften",
  field_commitDateTime: "Datum und Zeitpunkt der Übermittlung",
  field_familyNames: "Familiennamen",
  field_givenNames: "Vornamen",
  field_group: "Gruppe",
  field_resourceName: "Name der Ressource",
  field_snapshotType: "Art der Momentaufnahme",
  field_version: "Version",
  filterBetween: "ZWISCHEN",
  filterBlankField: "Leeres Feld",
  filterExactMatch: "Exakter Treffer",
  filterFrom: "VON",
  filterGreaterThan: "Größer als",
  filterLessThan: "Kleiner als",
  filterPartialMatch: "Partieller Treffer",
  filterRecordsTitle: "Filterprotokoll",
  filterSubmitButtonText: "Filterliste",
  filterUntil: "BIS",
  geoSuggest: "Geo-Vorschlag",
  geoSuggestTooltip:
    "Dieses Feld zeigt Ihnen Vorschläge zu Geo-Standorten, basierend auf Ihrer Eingabe.",
  hasError: "Enthält Fehler",
  invalidDate: "Ungültiges Datum",
  invalidMetersValue: "Ungültige Längenangabe",
  jumpToPage: "Zur Seite springen",
  languageOfPage: "deu",
  loadingText: "lädt…",
  loggedInAsUser: "Eingelogged als:",
  logoutBtn: "Ausloggen",
  max: "Max",
  min: "Min",
  multipleValues: "Mehrere Werte",
  multipleValuesFound: "Mehrere Werte gefunden",
  name: "Name",
  navigation: "Navigation",
  next: "Nächstes",
  no: "Nein",
  noRowsFound: "keine Zeilen gefunden",
  none: "keine",
  of: "von",
  oneValuePerLine: "Ein Eintrag pro Zeile",
  oneValuePerLineTooltip:
    "Bitte tragen Sie einen Eintrag pro Zeile ein. Drücken Sie beim Schreiben im Feld Enter, um eine neue Zeile hinzuzufügen",
  overrideAll: "Alles Überschreiben",
  overrideAllConfirmation:
    "Dieser Schritt LÖSCHT ALLE {fieldName} für ALLE Material Sample",
  overrideAllConfirmationTitle: "Überschreibe alle {fieldName}s?",
  page: "Seite",
  previous: "Vorherige",
  queryTable: "Tabelle durchsuchen",
  queryTableMultiSortExplanation:
    "Um nach mehreren Spalten zu sortieren: Clicken Sie auf eine Spaltenüberschrift, um nach dieser Spalte zu sortieren. Dann halten Sie Shift gedrückt, wärend Sie eine zusätzliche Spaltenüberschrift auswählen.",
  queryTableMultiSortTooltipTitle: "Sortierung nach mehrern Spalten",
  remarks: "Anmerkungen",
  remove: "Entfernen",
  resetButtonText: "Zurücksetzen",
  resetFilters: "Filter zurücksetzen",
  resetSort: "Sortierung zurücksetzen",
  results: "Ergebnisse",
  rows: "Zeilen",
  rowsPerPage: "Zeilen pro Seite",
  search: "Suche",
  searchResults: "Suchergebnisse",
  select: "Auswählen",
  selectLocation: "Location auswählen",
  selected: "ausgewählt",
  showChanges: "Änderungen anzeigen",
  showHide: "Anzeigen / Verbergen",
  somethingWentWrong: "Hier ist etwas schief gegangen",
  sourceField: "Ursprungsfeld",
  sourceText: "Ursprungstext",
  startLabel: "Start",
  stepLabel: "Abschnitt",
  subjectTermsForPage:
    "Regierungsinformationen, wissenschaftliche Informationen, wissenschaftliche Forschung",
  submitBtnText: "Speichern",
  tableTotalCount: "Gesamte Treffereinträge: {totalCount}",
  targetField: "Zielfeld",
  text: "Text",
  to: "Nach",
  true: "Richtig",
  typeHereToSearch: "Für die Suche bitte hier eintragen.",
  typeToSearchOrChooseFromNewest:
    "Wählen Sie aus den neusten Einträgen oder geben Sie hier ihren Suchbegriff ein.",
  uiAppVersion: "UI Anwendungsversion: {version}",
  update: "Aktualisieren",
  valueLabel: "Wert",
  valueSourceType: "Herkunftstyp des Wertes",
  view: "anzeigen",
  viewDetails: "Details anzeigen",
  warning: "Warnung",
  yes: "Ja"
};
