import { COMMON_UI_MESSAGES_ENGLISH } from "./common-ui-en";

export const COMMON_UI_MESSAGES_FR: Partial<typeof COMMON_UI_MESSAGES_ENGLISH> =
  {
    AND: "ET",
    IS: "EST",
    ISNOT: "N’EST PAS",
    OR: "OU",
    actions: "Actions",
    add: "Ajouter",
    addNew: "Ajouter nouveau",
    agricultureCanada: "Agriculture et Agroalimentaire Canada",
    areYouSure: "Êtes-vous certain(e)?",
    attached: "Joint",
    attributeLabel: "Attribut",
    autoFillGeoSuggestLabel:
      "Remplissage automatique des champs de localisation (la valeur de ce champ de recherche nest pas conservée)",
    backToList: "Retour à la page de liste",
    backToReadOnlyPage: "Retour à la page en mode lecture seule",
    bulkEdit: "Modification groupée",
    bulkEditorValidationError:
      "Valeur non valide sur la ligne {row} : {valeur}",
    bulkSubmissionErrorInfo:
      "Erreur d'envoi en bloc : Vérifiez les onglets ayant une étiquette rouge",
    cancelButtonText: "Annuler",
    checkAll: "Cocher tout",
    checkAllTooltipMessage:
      "Cochez cette case pour cocher tous les articles visibles dans cette page. ",
    closeButtonText: "Fermer",
    collapse: "Réduire",
    configureLabel: "Configurer",
    createNew: "Créer nouveau",
    created: "Créé",
    date: "Date",
    dateMustBeFormattedPartial:
      "Les dates doivent être écrites selon lun des formats suivants : AAAA-MM-JJ, AAAA-MM ou AAAA",
    dateMustBeFormattedYyyyMmDd:
      "La date doit être écrite sous la forme AAAA-MM-JJ",
    deleteAllButtonText: "Tout supprimer",
    deleteButtonText: "Supprimer",
    deleteSelectedButtonText: "Supprimer les éléments sélectionnés",
    description: "Description",
    destroyedLabel: "Détruit",
    detach: "Détacher",
    done: "Terminé",
    dontChangeValues: "Ne pas modifier les valeurs",
    dropdownSearchResults: "Rechercher résultats",
    editAll: "Éditer tout",
    editButtonText: "Modifier",
    editSelectedButtonText: "Modifier les éléments sélectionnés",
    editableTable: "Tableau modifiable",
    edited: "Modifié",
    errorPageTitle: "Erreur",
    existing: "Existante",
    expand: "Développer",
    false: "Faux",
    field_address: "Adresse",
    field_author: "Auteur",
    field_changedProperties: "Propriétés modifiées ",
    field_commitDateTime: "Date et heure de validation ",
    field_familyNames: "Noms de famille",
    field_givenNames: "Prénoms",
    field_group: "Groupe",
    field_resourceName: "Nom de la ressource",
    field_snapshotType: "Type d’instantané",
    field_version: "Version",
    filterBetween: "ENTRE",
    filterBlankField: "Champ vide",
    filterExactMatch: "Correspondance exacte",
    filterFrom: "DE",
    filterGreaterThan: "Plus grand que",
    filterLessThan: "Plus petit que",
    filterPartialMatch: "Correspondance partielle",
    filterRecordsTitle: "Filtrer les enregistrements",
    filterSubmitButtonText: "Filtrer la liste",
    filterUntil: "JUSQU’À",
    geoSuggest: "Géo-Suggestion",
    geoSuggestTooltip:
      "Ce bouton affiche des suggestions de géolocalisations fondées sur ce que vous avez saisi dans le champ.",
    hasError: "Comporte une erreur",
    invalidDate: "Date non valide",
    invalidMetersValue: "Valeur en mètres non valide",
    jumpToPage: "Passer à la page",
    languageOfPage: "fra",
    loadingText: "Chargement en cours...",
    loggedInAsUser: "Connecté en tant que :",
    logoutBtn: "Fermer la session",
    max: "Max",
    min: "Min",
    multipleValues: "Valeurs multiples",
    multipleValuesFound: "Valeurs multiples trouvées",
    name: "Nom",
    navigation: "Navigation",
    next: "Suivant",
    no: "Non",
    noRowsFound: "Aucune donnée n’a été trouvée",
    none: "Aucun(e)",
    of: "de",
    oneValuePerLine: "Une valeur par ligne",
    oneValuePerLineTooltip:
      "Écrivez une valeur par ligne. Appuyez sur Entrer lorsque vous dactylographiez dans le champ pour ajouter une nouvelle ligne.",
    overrideAll: "Remplacer tout",
    overrideAllConfirmation:
      "Ceci ÉLIMINERA TOUS LES {fieldName}s pour TOUS les échantillons de matériaux",
    overrideAllConfirmationTitle: "Remplacer tous les {fieldName}s?",
    page: "Page",
    previous: "Précédente",
    queryTable: "Interroger la table",
    queryTableMultiSortExplanation:
      "Pour trier la liste en fonction de plusieurs colonnes : Cliquez sur un en-tête de colonne pour trier par cette colonne, puis appuyez sur la touche Maj pendant que vous cliquez sur un autre en-tête.",
    queryTableMultiSortTooltipTitle: "Trier en fonction de plusieurs colonnes ",
    remarks: "Remarques",
    remove: "Retirer",
    resetButtonText: "Réinitialiser",
    resetFilters: "Réinitialiser les filtres ",
    resetSort: "Réinitialiser l’ordre de tri",
    results: "Résultats",
    rows: "rangées",
    rowsPerPage: "Colonnes par page",
    search: "Rechercher",
    searchResults: "Chercher résultats",
    select: "Sélectionner ",
    selectLocation: "Sélectionner l’emplacement",
    selected: "sélectionné ",
    showChanges: "Visualiser les modifications ",
    showHide: "Afficher/Masquer",
    somethingWentWrong: "Un problème est survenu",
    sourceField: "Champ source",
    sourceText: "Texte de départ",
    startLabel: "Démarrer",
    stepLabel: "Étape",
    subjectTermsForPage:
      "information gouvernemental, information scientifique, recherche scientifique",
    submitBtnText: "Enregistrer",
    tableSelectedCount: "Nombre de documents sélectionnés : {totalCount}",
    tableTotalCount: "Nombre d'enregistrements correspondants : {totalCount}",
    targetField: "Champ cible",
    text: "Texte",
    to: "À",
    true: "Vrai",
    typeHereToSearch: "Tapez ici pour effectuer une recherche.",
    typeToSearchOrChooseFromNewest:
      "Saisir la recherche ou choisir parmi les plus récents",
    uiAppVersion: "Version de l’application IU : {version}",
    update: "Mise à jour",
    valueLabel: "Valeur",
    valueSourceType: "Type de valeur de départ",
    view: "Visualiser",
    viewDetails: "Voir les détails",
    warning: "Avertissement",
    yes: "Oui"
  };
