import { COMMON_UI_MESSAGES_ENGLISH } from "./common-ui-en";

export const COMMON_UI_MESSAGES_GERMAN: Partial<
  typeof COMMON_UI_MESSAGES_ENGLISH
> = {
  AND: "UND",
  IS: "IST",
  ISNOT: "IST NICHT",
  OR: "ODER",
  actions: "Aktionen",
  add: "Hinzufügen",
  addNew: "Neu hinzufügen",
  agricultureCanada: "Canadische Landwirtschaft",
  applyButtonText: "Anwenden",
  areYouSure: "Sind Sie sicher?",
  attachSelected: "Auswahl anhängen",
  attached: "anhängen",
  attributeLabel: "Attribut",
  autoFillGeoSuggestLabel:
    "Standortfelder (automatisch befüllt, Inhalt ist nicht beständig)",
  backToList: "Zurück zur Trefferliste",
  backToParentFile: "Zurück zur übergeordneten Datei: {parentFilename}",
  backToReadOnlyPage: "Zurück zur schreibgeschützten Seite",
  bulkEdit: "Bearbeitung der Gruppe",
  bulkEditorValidationError: "Fehlerhafte Eingabe in Zeile {row} : {value}",
  bulkSubmissionErrorInfo:
    "fehlerhafte Eingabe: Bitte prüfen Sie die Felder mit roter Kennzeichnung.",
  cancelButtonText: "Annullieren",
  changesMade: "Änderungen vorgenommen",
  changesMadeTooltip:
    "Dieses Feld wird für alle ausgewählten Datensätze auf denselben Wert gesetzt. Vorhandene Werte werden überschrieben.",
  checkAll: "Alle prüfen",
  checkAllTooltipMessage:
    "Prüfen Sie dieses Überschriftenfeld, um alle sichtbaren Elemente auf dieser Seite zu prüfen.",
  cleared: "Geleert",
  clearedFieldTooltip:
    "Dieses Feld wird für alle ausgewählten Datensätze geleert. Vorhandene Daten werden entfernt.",
  clearedTooltip:
    "Dieses Feld für alle ausgewählten Einträge leeren. Nach dem Speichern ist es überall leer.",
  closeButtonText: "Schließen",
  collapse: "Zusammenklappen",
  configureLabel: "Konfigurieren",
  createNew: "neue anlegen",
  created: "angelegt",
  date: "Datum",
  dateBetweenInvalid: 'Ungültige Abfrage: Datum "von" liegt nach Datum "bis"',
  dateBetweenMissingValues:
    "Ungültige Abfrage: Zwei Datumswerte müssen angegeben werden",
  dateInRangeInvalid:
    "Ungültige Abfrage: Gültige Datumswerte (YYYY-MM-DD) als komma-separierte Liste eingeben (z.B. 2001-05-19, 2008-12-25, 2023-01-01)",
  dateMustBeFormattedPartial: "Muss partiell formatiert werden",
  dateMustBeFormattedYyyyMmDd:
    "Bitte das Datum in folgendem Format angeben: YYYY-MM-DD",
  deleteAllButtonText: "Alle löschen",
  deleteButtonText: "Löschen",
  deleteSelectedButtonText: "Auswahl löschen",
  deleted: "Gelöscht",
  deletedTooltip: "Dieses Feld wird für alle ausgewählten Datensätze gelöscht.",
  description: "Beschreibung",
  destroyedLabel: "zerstört",
  detach: "Trennen",
  done: "Erledigt",
  dropdownSearchResults: "Suchergebnisse",
  editAll: "Alle bearbeiten",
  editButtonText: "Bearbeiten",
  editSelectedButtonText: "Ausgewählte bearbeiten",
  editableTable: "Tabelle bearbeiten",
  edited: "Bearbeitet",
  errorPageTitle: "Fehler",
  existing: "Vorhanden",
  expand: "Erweitern",
  exportButtonText: "Exportieren",
  exportObjectsButtonText: "Objekte exportieren",
  exportObjectsMaxLimitTooltip:
    "Objekte exportieren erlaubt maximal 100 Dateien. Bitte bis zu 100 Dateien auswählen.",
  false: "FALSCH",
  field_address: "Adresse",
  field_author: "Verfasser",
  field_changedProperties: "Geänderte Eigenschaften",
  field_commitDateTime: "Datum und Zeitpunkt der Übermittlung",
  field_familyNames: "Familiennamen",
  field_givenNames: "Vornamen",
  field_group: "Gruppe",
  field_resourceName: "Name der Ressource",
  field_snapshotType: "Art der Momentaufnahme",
  field_version: "Version",
  filterBetween: "ZWISCHEN",
  filterBlankField: "Leeres Feld",
  filterColumns: "Spalten filtern",
  filterExactMatch: "Exakter Treffer",
  filterFrom: "VON",
  filterGreaterThan: "Größer als",
  filterLessThan: "Kleiner als",
  filterPartialMatch: "Partieller Treffer",
  filterRecordsTitle: "Filterprotokoll",
  filterSubmitButtonText: "Filterliste",
  filterUntil: "BIS",
  first: "Erste",
  generateButtonText: "Vorlage erzeugen",
  geoSuggest: "Geo-Vorschlag",
  geoSuggestTooltip:
    "Dieses Feld zeigt Ihnen Vorschläge zu Geo-Standorten, basierend auf Ihrer Eingabe.",
  hasError: "Enthält Fehler",
  invalidDate: "Ungültiges Datum",
  invalidMetersValue: "Ungültige Längenangabe",
  jumpToPage: "Zur Seite springen",
  keepCurrentValues: "Aktuelle Werte beibehalten",
  languageOfPage: "deu",
  largeImage: "Großes Bild",
  last: "Letzte",
  loadingText: "lädt…",
  loggedInAsUser: "Eingelogged als:",
  logoutBtn: "Ausloggen",
  max: "Max",
  min: "Min",
  mismatchMaterialSampleTypeError:
    "Einige Materialproben entsprechen nicht der Aufteilungskonfiguration und wurden entfernt.",
  multipleValues: "Mehrere Werte",
  multipleValuesFound: "Mehrere Werte gefunden",
  name: "Name",
  navigation: "Navigation",
  next: "Nächstes",
  no: "Nein",
  noChangesMade: "Keine ßnderungen",
  noChangesMadeTooltip:
    "Für dieses Feld werden bei den ausgewählten Datensätzen keine ßnderungen vorgenommen. Bereits vorhandene Werte bleiben unverändert.",
  noRowsFound: "keine Zeilen gefunden",
  none: "keine",
  numberBetweenInvalid:
    "Ungültige Bereichssuche: Die Von-Zahl ist größer als die Bis-Zahl.",
  numberBetweenMissingValues:
    "Ungültige Bereichssuche: Es müssen zwei Zahlen angegeben werden.",
  numberInRangeInvalid:
    "Ungültige In/Not-in-Suche: Zahlen müssen gültig und kommagetrennt sein (z. B. 12.5, 2, 4).",
  numberInvalid: "Bitte gib eine gültige Zahl ein",
  of: "von",
  oneValuePerLine: "Ein Eintrag pro Zeile",
  oneValuePerLineTooltip:
    "Bitte tragen Sie einen Eintrag pro Zeile ein. Drücken Sie beim Schreiben im Feld Enter, um eine neue Zeile hinzuzufügen",
  overrideAll: "Alles Überschreiben",
  overrideAllConfirmation:
    "Dieser Schritt LÖSCHT ALLE {fieldName} für ALLE Material Sample",
  overrideAllConfirmationTitle: "Überschreibe alle {fieldName}s?",
  page: "Seite",
  previous: "Vorherige",
  queryTable: "Tabelle durchsuchen",
  queryTableMultiSortExplanation:
    "Um nach mehreren Spalten zu sortieren: Clicken Sie auf eine Spaltenüberschrift, um nach dieser Spalte zu sortieren. Dann halten Sie Shift gedrückt, wärend Sie eine zusätzliche Spaltenüberschrift auswählen.",
  queryTableMultiSortTooltipTitle: "Sortierung nach mehrern Spalten",
  refreshButtonText: "Aktualisieren",
  remarks: "Anmerkungen",
  remove: "Entfernen",
  resetButtonText: "Zurücksetzen",
  resetFilters: "Filter zurücksetzen",
  resetSort: "Sortierung zurücksetzen",
  results: "Ergebnisse",
  rows: "Zeilen",
  rowsPerPage: "Zeilen pro Seite",
  search: "Suche",
  searchResults: "Suchergebnisse",
  select: "Auswählen",
  selectLocation: "Location auswählen",
  selected: "ausgewählt",
  showChanges: "Änderungen anzeigen",
  showHide: "Anzeigen / Verbergen",
  somethingWentWrong: "Hier ist etwas schief gegangen",
  sourceField: "Ursprungsfeld",
  sourceText: "Ursprungstext",
  splitSelectedButtonText: "Auswahl aufteilen",
  startLabel: "Start",
  stepLabel: "Abschnitt",
  subjectTermsForPage:
    "Regierungsinformationen, wissenschaftliche Informationen, wissenschaftliche Forschung",
  submitBtnText: "Speichern",
  tableSelectedCount: "Gesamt ausgewählte Datensätze: {totalCount}",
  tableTotalCount: "Gesamte Treffereinträge: {totalCount}",
  targetField: "Zielfeld",
  text: "Text",
  thumbnailImage: "Vorschaubild",
  to: "Nach",
  true: "Richtig",
  typeHereToSearch: "Für die Suche bitte hier eintragen.",
  typeToSearchOrChooseFromNewest:
    "Wählen Sie aus den neusten Einträgen oder geben Sie hier ihren Suchbegriff ein.",
  uiAppVersion: "UI Anwendungsversion: {version}",
  undoClearedTooltip:
    "Leeren dieses Feldes rückgängig machen. Die ursprünglichen Werte bleiben erhalten.",
  update: "Aktualisieren",
  uploadDerivative: "Derivative hochladen",
  valueLabel: "Wert",
  valueSourceType: "Herkunftstyp des Wertes",
  view: "anzeigen",
  viewDetails: "Details anzeigen",
  warning: "Warnung",
  yes: "Ja"
};
