import { COMMON_UI_MESSAGES_ENGLISH } from "./common-ui-en";

export const COMMON_UI_MESSAGES_FR: Partial<typeof COMMON_UI_MESSAGES_ENGLISH> =
  {
    AND: "ET",
    IS: "EST",
    ISNOT: "N’EST PAS",
    OR: "OU",
    addNew: "Ajouter nouveau",
    areYouSure: "Êtes-vous certain(e)?",
    attributeLabel: "Attribut",
    autoFillGeoSuggestLabel:
      "Remplissage automatique des champs de localisation (la valeur de ce champ de recherche nest pas conservée)",
    backToList: "Retour à la page de liste",
    bulkEditorValidationError:
      "Valeur non valide sur la ligne {row} : {valeur}",
    cancelButtonText: "Annuler",
    checkAllTooltipMessage:
      "Cochez cette case pour cocher tous les articles visibles dans cette page. ",
    closeButtonText: "Fermer",
    createNew: "Créer nouveau",
    deleteAllButtonText: "Tout supprimer",
    deleteButtonText: "Supprimer",
    editButtonText: "Modifier",
    editableTable: "Tableau modifiable",
    errorPageTitle: "Erreur",
    existing: "Existante",
    false: "Faux",
    field_author: "Auteur",
    field_changedProperties: "Propriétés modifiées ",
    field_commitDateTime: "Date et heure de l’engagement ",
    field_group: "Groupe",
    field_resourceName: "Nom de la ressource",
    field_snapshotType: "Type d’image instantanée ",
    field_version: "Version",
    filterBetween: "ENTRE",
    filterBlankField: "Champ vide",
    filterExactMatch: "Correspondance exacte",
    filterFrom: "DE",
    filterGreaterThan: "Plus grand que",
    filterLessThan: "Plus petit que",
    filterPartialMatch: "Correspondance partielle",
    filterRecordsTitle: "Filtrer les dossiers ",
    filterSubmitButtonText: "Filtrer la liste",
    filterUntil: "JUSQU’À",
    geoSuggest: "Géo-Suggestion",
    geoSuggestTooltip:
      "Ce bouton affiche des suggestions de géolocalisations fondées sur ce que vous avez saisi dans le champ.",
    loadingText: "Chargement en cours...",
    loggedInAsUser: "Connecté en tant que :",
    logoutBtn: "Fermer la session",
    name: "Nom",
    next: "Suivant",
    no: "Non",
    noRowsFound: "Aucune donnée n’a été trouvée",
    none: "Aucun(e)",
    of: "de",
    oneValuePerLine: "Une valeur par ligne",
    oneValuePerLineTooltip:
      "Écrivez une valeur par ligne. Appuyez sur Entrer lorsque vous dactylographiez dans le champ pour ajouter une nouvelle ligne.",
    page: "Page",
    previous: "Précédente",
    queryTableMultiSortExplanation:
      "Pour trier la liste en fonction de plusieurs colonnes : Cliquez sur un en-tête de colonne pour trier par cette colonne, puis appuyez sur la touche Maj pendant que vous cliquez sur un autre en-tête.",
    queryTableMultiSortTooltipTitle: "Trier en fonction de plusieurs colonnes ",
    remove: "Retirer",
    resetButtonText: "Réinitialiser",
    rows: "rangées",
    search: "Rechercher",
    select: "Sélectionner ",
    selectLocation: "Sélectionner l’emplacement",
    selected: "sélectionné ",
    showChanges: "Visualiser les modifications ",
    somethingWentWrong: "Un problème est survenu",
    sourceField: "Champ source",
    sourceText: "Texte de départ",
    submitBtnText: "Enregistrer",
    tableTotalCount: "Nombre de dossiers correspondants : {totalCount}",
    targetField: "Champ cible",
    text: "Texte",
    true: "Vrai",
    typeHereToSearch: "Tapez ici pour effectuer une recherche.",
    uiAppVersion: "Version de l’application IU : {version}",
    valueLabel: "Valeur",
    valueSourceType: "Type de valeur de départ",
    viewDetails: "Voir les détails",
    yes: "Oui",
    backToReadOnlyPage: "Retour à la page en mode lecture seule",
    configureLabel: "Configurer",
    description: "Description",
    destroyedLabel: "Détruit",
    remarks: "Remarques",
    results: "Résultats",
    startLabel: "Démarrer",
    stepLabel: "Étape"
  };
