import { DINAUI_MESSAGES_ENGLISH } from "./dina-ui-en";

export const DINAUI_MESSAGES_FRENCH: Partial<typeof DINAUI_MESSAGES_ENGLISH> = {
  LETTER: "Lettre",
  NUMERICAL: "Numérique",
  actionType: "Type d’action",
  addAnother: "Ajouter un autre {typeName}",
  addAnotherIdentifier: "Ajouter un autre identifiant",
  addAssemblageTitle: "Ajouter un assemblage",
  addAssertion: "Ajouter une géoréférence",
  addAttachments: "Ajouter des pièces jointes",
  addAttributesTemplateTitle: "Nouveau modèle d’attributs",
  addCataloguedObjectTitle: "Ajouter un objet catalogué",
  addCollectingEventTitle: "Ajouter un événement de collecte",
  addCollectionMethodTitle: "Ajouter une méthode de prélèvement",
  addCollectionTitle: "Ajouter une collection",
  addCollectorGroupTitle: "Ajouter un groupe de collecte",
  addCustomPlaceName: "Ajouter",
  addDetermination: "Ajouter une détermination",
  addExistingStorageUnitAsChild: "Ajouter une unité de stockage existante",
  addExternalResourceTitle: "Ajouter une nouvelle ressource externe",
  addFilesButton: "Ajouter des fichiers",
  addGroup: "Ajouter un groupe",
  addIdentifier: "Ajouter un identifiant",
  addInstitutionTitle: "Ajouter un établissement",
  addManagedAttribute: "Ajouter un attribut géré",
  addManagedAttributeButtonText: "Ajouter un nouvel attribut géré",
  addManagedAttributeTitle: "Ajouter un nouvel attribut géré",
  addManagedAttributesViewTitle: "Créer un modèle de formulaire",
  addMaterialSampleTitle: "Ajouter un échantillon de matériau",
  addMaterialSampleTypeTitle: "Ajouter un type d’échantillon de matière",
  addMetadataTitle: "Ajouter des métadonnées",
  addNewChildStorageUnit: "Ajouter une nouvelle unité de stockage pour enfant",
  addNewElement: "Ajouter nouveau {typeName}",
  addNewPerson: "Ajouter nouvelle personne",
  addObjectSubtypeTitle: "Ajouter un nouveau sous-type d’objet",
  addOrganizationTitle: "Ajouter une nouvelle organisation",
  addPersonButtonText: "Ajouter une personne",
  addPersonPopupTooltip: "Ajouter une personne sans quitter la page",
  addPersonTitle: "Ajouter une personne",
  addPreparationMethodTitle: "Ajouter une méthode de préparation",
  addPreparationTypeTitle: "Ajouter un type de préparation",
  addProjectTitle: "Ajouter projet",
  addRule: "Ajouter une règle",
  addRuleSet: "Ajouter un ensemble de règles",
  addScheduledAction: "Ajouter une action prévue",
  addStorageUnitTitle: "Ajouter une unité de stockage",
  addStorageUnitTypeTitle: "Ajouter un type d’unité de stockage",
  addTransactionTitle: "Créer une transaction",
  additionalRemarks: "Remarques additionnelles",
  agent: "Agent",
  agentDetails: "Détails sur l'agent",
  agentName: "Nom de l'agent",
  agentRemarks: "Remarques de l'agent",
  agentRole: "Rôle de l'agent",
  agentsSectionTitle: "Agents",
  allowDuplicate: "Permettre les copies",
  allowExisting: "Autoriser l’existant",
  allowNew: "Autoriser le nouveau",
  appTitle: "DINA",
  appTitleInstanceMode: "DINA ({instanceMode})",
  assemblage: "Assemblage",
  assemblageAttachments: "Pièces jointes de l'assemblage",
  assemblageListTitle: "Assemblages",
  assemblageManagedAttributes: "Attributs gérés de l'assemblage",
  assemblage_tooltip:
    "Mécanisme utilisé pour regrouper des échantillons de matériau selon un certain thème organisationnel.",
  assemblages: "Assemblages",
  assignContentsToNewStorage: "Assigner le contenu au nouveau stockage",
  assignedStorage: "Stockage assigné",
  assignedTo: "Attribué à",
  associatedAgent: "Agent associé",
  associatedMaterialSample: "Échantillon de matériau connexe",
  association: "Association",
  associationType: "Type d'association",
  associationsLegend: "Associations",
  attachExisting: "Joindre l’existant",
  attachExistingObjects: "Joindre des objets existants",
  attachSelected: "Joindre la sélection",
  attachedMaterialSamples: "Pièces jointes des échantillons de matériau",
  attachments: "Pièces jointes",
  attributeLabel: "Attribut",
  auditSnapshot: "Aperçu de l'audit",
  backToParentUnit: "Retour à l'unité parent",
  baseNameLabel: "Nom de base",
  batchModeInfo:
    "Mode de traitement par lots : tous les échantillons de matériaux ont le même no d'identification.",
  browseContents: "Parcourir le contenu",
  browseStorageTree: "Parcourir l’arborescence de stockage",
  bulkCreate: "Créer plusieurs nouveaux",
  bulkEditResourceLinkerWarningMulti:
    "Ce champ {fieldName} sera lié à tous les {targetType}s.",
  bulkEditResourceLinkerWarningSingle:
    "Ce champ {fieldName} sera lié à tous les {targetType}s.",
  bulkEditResourceSetWarningMulti:
    "Ce champ {fieldName} sera affecté à tous les {targetType}s.",
  bulkOperationCompleteTitle: "Opération groupée terminée",
  cancelButtonText: "Annuler",
  cataloguedObjectListTitle: "Objets catalogués",
  cfiaPPCLevel: "Niveau ACIA PPC",
  changedProperties: "Modifications",
  childCultureStrains: "Souches de culture",
  childMaterialSamples: "Échantillon de Matériel Direct Enfants",
  childrenStorageUnits: "Tables enfants des unités de stockage",
  closePreviewButtonText: "Fermer la prévisualisation",
  colSearchBoxTooltip: "Rechercher dans le Catalogue de la vie",
  colSearchLabel: "Recherche de nom",
  collectingAgentsLegend: "Agents de collecte",
  collectingDateLegend: "Date de collecte",
  collectingEvent: "Événement de collecte",
  collectingEventAttachments: "Pièces jointes de l’événement de collecte",
  collectingEventDetails: "Détails de l'activité de collecte",
  collectingEventListTitle: "Événement de collecte",
  collectingEventManagedAttributes:
    "Attributs gérés de l’événement de collecte",
  collectingLocationLegend: "Lieu de collecte",
  collection: "Prélèvement",
  collectionListTitle: "Collections",
  collectionManagedAttributeListTitle:
    "Attributs gérés du module de collections",
  collectionMethodListTitle: "Méthode de prélèvement",
  collectionMethodNameLabel: "Nom de la méthode de prélèvement",
  collectionSectionTitle: "Collections",
  collectionViewTitle: "Collection",
  collectorGroupAgentsLabel: "Agents du groupe de collecte",
  collectorGroupListTitle: "Groupe de collecte",
  collectorGroupNameLabel: "Nom du groupe de collecte",
  components: "Composants",
  configureDefaultValues: "Configurer les valeurs par défaut",
  configureFormTemplate: "Configurer un modèle de formulaire",
  contents: "Table des matières",
  controlledVocabularyTitle: "Vocabulaire vérifié",
  convertToDepthMinMax: "Conversion de la profondeur min/max",
  convertToElevationMinMax: "Conversion de l’élévation min/max",
  coordinateUncertaintyInMeters: "Coordonner l’incertitude en mètres",
  copyFromParentLabel: "Copier du parent",
  countryLabel: "Pays",
  creatNewWorkflow: "Créer nouveau",
  create: "Créer",
  createAndAssign: "Créer et assigner",
  createFormTemplate: "Créer un modèle de formulaire",
  createMaterialSampleFormTemplate:
    "Créer un modèle de formulaire des échantillons de matériau",
  createNew: "Créer",
  createNewLabel: "Créer nouveau",
  createNewMaterialSamples: "Créer de nouveaux échantillons de matériaux",
  createNewView: "Créer une nouvelle vue",
  createSampleWithFormTemplate:
    "Créer un échantillon à l'aide d'un modèle de formulaire",
  createSavedSearch: "Créer une recherche sauvegardée",
  createSplitWorkflow: "Créer un fractionnement",
  createStorage: "Créer un espace d'entreposage",
  customPlaceName: "Nom de lieu personnalisé",
  dataComponents: "Éléments de données",
  dataEntryLabel: "Saisie de données",
  dataType: "Taper: ",
  dataValue: "Valeur: ",
  dataset: "Ensemble de données",
  datasetSearchTooltip:
    "Pour utiliser un ensemble de données différent du Catalogue de la vie.",
  decimalLatLong: "Lat/Long décimales",
  default: "Par défaut",
  defaultValues: "Valeurs par défaut",
  defaultValuesConfig: "Configuration des valeurs par défaut ",
  defaultValuesConfigs: "Configuratsions des valeurs par défaut ",
  deleteButtonText: "Supprimer",
  deleteConfig: "Supprimer la configuration",
  deleteEmptyStorageWarning:
    "L'espace d'entreposage {storageName} est vide. Souhaitez-vous supprimer ce contenant d'entreposage définitivement?",
  deleteThisAttributesTemplate: "Supprimer ce modèle",
  deleteThisView: "Supprimer cette vue",
  deleted: "Supprimé",
  deletedMetadata_tooltip: "ID de métadonnées supprimées : {id}",
  depthInMeters: "Profondeur en mètres",
  destroyOriginal: "Identifier l’original comme « Détruit »",
  detachCollectingEvent: "Détacher l’événement de collecte",
  detachSelectedButtonText: "Détacher la sélection",
  detailsPageLink: "Page des détails",
  determination: "Détermination",
  determinationManagedAttributes: "Détermination des attributs gérés",
  determinationPrimary: "Détermination (primaire)",
  determinations: "Déterminations",
  determiningAgents: "Établissement des agents",
  determiningDate: "Établissement de la date",
  dinaHomeH1: "Dina Accueil",
  dinaManagementSectionTitle: "Gestion",
  disabledForChildMaterialSamples:
    "Table enfant désactivée pour les échantillons de matériau",
  dragDropInstructionsHeader: "Pour modifier l'ordre des attributs : ",
  dragDropKeyboardInstructions:
    "Utiliser le tabulateur pour accéder à l'attribut, puis appuyer sur la barre d'espacement pour le sélectionner. Utiliser les touches fléchées pour déplacer l'élément, puis appuyer sur la barre d'espacement pour le placer.",
  dragDropMouseInstructions:
    "Glisser et déposer l'attribut à sa nouvelle position.",
  duplicate: "Dupliquer",
  duplicateFilesFound: "fichiers en double trouvés",
  duplicatePrimaryIdFound: "Copie du document d'identité principal trouvée ",
  editAssemblageTitle: "Modifier un assemblage",
  editCataloguedObjectTitle: "Modifier un objet catalogué",
  editCollectingEventTitle: "Modifier l’événement de collecte",
  editCollectionMethodTitle: "Modifier la méthode de prélèvement",
  editCollectionTitle: "Modifier la collection",
  editDinaUserTitle: "Modifier l’utilisateur",
  editExternalResourceTitle: "Modifier une ressource externe",
  editInstitutionTitle: "Modifier l’établissement",
  editManagedAttributeTitle: "Modifier l’attribut géré",
  editManagedAttributesViewTitle: "Modifier un modèle de formulaire",
  editMaterialSampleFormTemplate:
    "Modifier un modèle de formulaire des échantillons de matériau",
  editMaterialSampleTitle: "Modifier l’échantillon de matériaux",
  editMaterialSampleTypeTitle: "Modifier le type d’échantillon de matière",
  editMetadataTitle: "Modifier les métadonnées",
  editObjectSubtypeTitle: "Modifier le sous-type d’objet",
  editOrganizationAliasesLabel: "Pseudonymes (séparés par une virgule)",
  editOrganizationTitle: "Modifier l’organisation",
  editPersonTitle: "Modifier la personne",
  editPreparationMethodTitle: "Modifier une méthode de préparation",
  editPreparationTypeTitle: "Modifier le type de préparation",
  editProjectTitle: "Modifier Projet",
  editSelectedAttachmentMetadata:
    "Modifier les métadonnées de la pièce jointe sélectionnée",
  editStorageUnitTitle: "Modifier l’unité de stockage",
  editStorageUnitTypeTitle: "Modifier le type de stockage",
  editThisFormTemplate: "Modifier ce modèle de formulaire",
  editTransactionTitle: "Modifier une transaction",
  elevationInMeters: "Élévation en mètres",
  enableDateRangeLabel: "Activer la plage de dates",
  exact: "Exact",
  exifProperties: "Propriétés existantes",
  existingAttachments: "Pièces jointes existantes",
  extensionListTitle: "Extensions de champ",
  externalResourceListTitle: "Ressources externes",
  feedbackButtonText: "Commentaires",
  fieldExtensions: "Extensions de champs",
  materialSampleFieldExtensions:
    "Extensions de champs de l’échantillon de matériaux",
  collectingEventFieldExtensions:
    "Extensions de champs de l’événement de collecte",
  field_acCaption: "Légende",
  field_acDerivedFrom: "Tiré de",
  field_acDigitizationDate: "Date de création de la version originale",
  field_acDigitizationDate_tooltip:
    "Date et heure auxquelles l’objet numérique décrit par la métadonnée a été créé. Dans le cas d’une image, cela représente le moment où l’image a été prise.",
  field_acHashFunction: "Fonction de hachage",
  field_acHashValue: "Hachage",
  field_acMetadataCreator: "Créateur de métadonnées ",
  "field_acMetadataCreator.displayName": "Téléchargé par",
  "field_acMetadataCreator.displayName_tooltip":
    "Agent qui a créé l’enregistrement de métadonnées.",
  field_acSubtype: "Sous-type d’objet",
  field_acTags: "Balises",
  field_acceptedValues: "Valeurs acceptées",
  field_aliases: "Pseudonymes",
  field_assemblageName: "Nom de l'assemblage",
  field_attachment: "Pièces jointes",
  field_attributesTemplate: "Modèle des attributs définis",
  field_barcode: "Code à barres",
  field_collectingEventCollectionMethod: "Méthode de collecte",
  field_collectingEventCollectionMethod_tooltip:
    "Méthode utilisée durant une activité de collecte. Exemples : piège lumineux à UV, chalut de fond",
  field_collectingEventHost: "Hôte",
  field_collectingEventHost_tooltip:
    "Hôte observé de l'échantillon de matériau au moment de l'activité de collecte",
  field_collectingEventSubstrate: "Substrat",
  field_collectingEventSubstrate_tooltip:
    "Surface observée sur laquelle un organisme a été prélevé et sur laquelle on pense qu'il a vécu",
  field_collectingEvent_endDateTimeError:
    "Le format de date/heure de l’événement final doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_collectingEvent_startDateTimeError:
    "Le format de la date de début de l’événement doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_collectorGroup_agentsError:
    "Au moins un agent doit être précisé pour le groupe",
  field_collectors: "Collecteurs",
  field_contact: "Contact",
  field_createdBy: "Créé par",
  field_createdDate: "Date de création",
  field_createdOn: "Créé le",
  "field_dcCreator.displayName": "Créateur du document",
  field_dcFormat: "Format du média",
  field_dcRights: "Droit d’auteur",
  field_dcType: "Type d’objet stocké",
  field_description: "Description",
  "field_description.en": "Description anglaise",
  "field_description.fr": "Description française",
  "field_description.de": "Description allemande",
  field_determination: "Déterminations",
  "field_determination.typeStatus": "Type d'état",
  "field_determination.verbatimScientificName": "Nom scientifique verbatim",
  field_determinationRemarks: "Détermination - remarques",
  field_displayName: "Visualiser le nom",
  field_dwcCatalogNumber: "Numéro de catalogue",
  field_dwcCoordinateUncertaintyInMeters:
    "Coordonner les incertitudes dans les mesures en mètres",
  field_dwcCoordinateUncertaintyInMeters_tooltip:
    "Distance horizontale en mètres à partir de la latitude décimale (decimalLatitude) et de la longitude décimale (decimalLongitude), décrivant le plus petit cercle renfermant l'ensemble de l'emplacement",
  field_dwcCountry: "Pays",
  field_dwcCountryCode: "Code du pays",
  field_dwcDecimalLatitude: "Latitude décimale",
  field_dwcDecimalLongitude: "Longitude décimale",
  field_dwcDegreeOfEstablishment: "Degré d'établissement",
  field_dwcDegreeOfEstablishment_tooltip:
    "La mesure dans laquelle un organisme survit, se reproduit et étend son aire de répartition à un endroit et à un moment donnés.",
  field_dwcFieldNumber: "Numéro de collection",
  field_dwcFieldNumber_tooltip:
    "Identifiant donné à l'activité sur le terrain au moment de la collecte d'un ou de plusieurs échantillons, servant souvent de lien entre les notes prises sur le terrain et l'activité.",
  field_dwcGeodeticDatum: "Référence géodésique",
  field_dwcGeodeticDatum_tooltip:
    "La référence géodésique sur laquelle les coordonnées géographiques decimalLatitude et decimalLongitude sont fondées. La pratique exemplaire recommandée est ",
  field_dwcGeoreferenceProtocol: "Protocole de géoréférencement",
  field_dwcGeoreferenceProtocol_tooltip:
    "Une description ou une référence aux méthodes utilisées pour déterminer l’empreinte spatiale, les coordonnées et les incertitudes.",
  field_dwcGeoreferenceRemarks: "Remarques sur la géoréférence",
  field_dwcGeoreferenceRemarks_tooltip:
    "Notes ou commentaires sur la détermination de la description spatiale, expliquant les hypothèses faites en plus ou en opposition à celles formalisées dans la méthode visée dans georeferenceProtocol.",
  field_dwcGeoreferenceSources: "Sources de géoréférencement",
  field_dwcGeoreferenceSources_tooltip:
    "Une liste de cartes, de répertoires géographiques ou d’autres ressources utilisées pour géoréférencer le lieu, décrite de manière suffisamment précise pour permettre à quiconque d’utiliser les mêmes ressources à l’avenir.",
  field_dwcGeoreferenceVerificationStatus: "Géoréférencement impossible",
  field_dwcMunicipality: "Municipalité",
  field_dwcOtherCatalogNumbers: "Autres numéros de catalogues",
  field_dwcOtherRecordNumbers: "Autres numéros de mentions",
  field_dwcRecordNumber: "Numéro du collecteur",
  field_dwcRecordNumber_tooltip:
    "Identifiant donné à l'occurrence, par le collectionneur, au moment où elle a été consignée, p. ex. le numéro du collectionneur de spécimens, servant souvent de lien entre les notes prises sur le terrain et une mention d'occurrence.",
  field_dwcRecordedBy: "Collecteurs Verbatim",
  field_dwcStateProvince: "État/province",
  field_dwcVerbatimCoordinateSystem: "Système de coordonnées Verbatim",
  field_dwcVerbatimCoordinateSystem_tooltip:
    "Le format des coordonnées pour les verbatimLatitude et verbatimLongitude ou les verbatimCoordinates de l’emplacement. Exemples : degrés décimaux, degrés minutes décimales, degrés minutes secondes, UTM",
  field_dwcVerbatimCoordinates: "Coordonnées verbatim",
  field_dwcVerbatimCoordinates_tooltip:
    "Les coordonnées spatiales originales verbatim de l’emplacement. L’ellipsoïde de coordonnées, le datum géodésique ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemples : 41 05 54S 121 05 34W, 17T 630000 4833400",
  field_dwcVerbatimDepth: "Profondeur Verbatim",
  field_dwcVerbatimDepth_tooltip:
    "La description originale de la profondeur sous la surface locale. Exemple : 100-200 m",
  field_dwcVerbatimElevation: "Verbatim Élévation",
  field_dwcVerbatimElevation_tooltip:
    "La description originale de l’élévation (altitude, au-dessus du niveau de la mer) de l’emplacement. Exemple : 100-200 m",
  field_dwcVerbatimLatitude: "Verbatim Latitude",
  field_dwcVerbatimLatitude_tooltip:
    "La latitude originale verbatim de l’emplacement. L’ellipsoïde de coordonnées, le geodeticDatum ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemple : 41 05 54.03S",
  field_dwcVerbatimLocality: "Verbatim Localité",
  field_dwcVerbatimLongitude: "Verbatim Longitude",
  field_dwcVerbatimLongitude_tooltip:
    "La longitude originale verbatim de l’emplacement. L’ellipsoïde de coordonnées, le geodeticDatum ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemple : 121 d 10? 34? W",
  field_dwcVerbatimSRS: "Verbatim SRS",
  field_dwcVerbatimSRS_tooltip:
    "L’ellipsoïde, le datum géodésique ou le système de référence spatiale (SRS) sur lesquels sont basées les coordonnées données dans verbatimLatitude et verbatimLongitude, ou verbatimCoordinates. La meilleure pratique recommandée est d’utiliser le code EPSG du SRS, s’il est connu. Exemples : EPSG:4326, WGS84, NAD27",
  field_editableBuiltInAttributes: "Attributs intégrés",
  field_email: "Courriel",
  field_enableGrid: "Activer la grille",
  field_enableGrid_tooltip:
    "Créer une grille permettant de stocker le contenu. Aucune table enfant ne peut être créée pour les unités de stockage.",
  field_endDate: "Date de fin",
  field_endEventDateTime: "Date et heure de l'événement final",
  field_endEventDateTime_tooltip:
    "Le format de date/heure de la fin de l’événement doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_familyNames: "Noms de famille",
  field_familyNames_tooltip:
    "Nom(s) de famille, y compris les noms de famille composés",
  field_fieldExtensions: "Extensions de champs",
  field_fileIdentifier: "Identifiant du fichier",
  field_fileSize: "Taille du fichier",
  field_givenNames: "Prénoms",
  field_givenNames_tooltip: "Prénom et tous les seconds prénoms",
  field_gridLayoutDefinition_column_label: "Par colonne",
  field_gridLayoutDefinition_row_label: "Par ligne",
  field_host: "Hôte",
  field_id: "ID",
  field_isFiledAs_tooltip:
    'Classé en tant que (ajouter cette détermination). Une seule détermination peut être inscrite comme "Classé en tant que".',
  field_isInseperable: "Garder les contenus ensemble",
  field_isInseperable_tooltip: "Les contenus sont inséparables",
  field_isPrimary_tooltip:
    "Faire de cette détermination le point de données principal lors de l'exportation. Une seule détermination peut être principale. ",
  field_isRestricted: "Fait l'objet de restrictions",
  field_isolatedBy: "Isolé par",
  field_isolatedOn: "Isolé le ",
  field_isolationRemarks: "Isolation - remarques",
  field_license: "Licence",
  field_lifeStage: "Étape de la Vie",
  field_managedAttributeComponent: "Type de composant des données cibles",
  field_managedAttributeCreatedBy: "Créé par",
  field_managedAttributeCreatedOn: "Créé le",
  field_managedAttributeMandatoryFieldsError:
    "Le nom et le type sont des champs obligatoires",
  field_managedAttributeName: "Nom de l'attribut",
  field_managedAttributes: "Attributs gérés",
  field_materialSampleName: "Identifiant Échantillons de matériaux",
  field_materialSampleRemarks: "Commentaire sur l'échantillon de matériau",
  field_materialSampleState: "État de l'échantillon de matériau",
  field_materialSampleState_tooltip:
    "Représente l'état d'un échantillon de matériau qui a été détérioré. ",
  field_materialSampleType: "Type d’échantillon de matière",
  field_materialSampleType_tooltip:
    "Terme défini par le système qui prescrit les attentes en aval et la logique selon laquelle des échantillons de matériaux dérivés (ou enfants) seront interprétés et gérés numériquement.",
  field_materialSample_identifierType_materialSampleId_label:
    "No ID d’échantillon de matière",
  field_materialToBeReturned: "À retourner",
  field_name: "Nom",
  field_notPubliclyReleasableReason:
    "Raison pour laquelle il n’est pas possible de le divulguer publiquement",
  field_organismRemarks: "Organisme Remarques",
  field_organismsIndividualEntry: "Entrée d'un organisme individuel",
  field_organismsIndividualEntry_tooltip:
    "Laisser FERMÉ pour copier les mêmes données pour chaque organisme. Basculement ACTIVÉ pour entrer différentes données pour chaque organisme.",
  field_organismsQuantity: "Quantité d'Organismes",
  field_organizationMandatoryFieldsError:
    "Le nom d’au moins une organisation est requis",
  field_orientation: "Orientation",
  field_orientation_tooltip:
    "Détermine la façon dont une image doit être affichée en fonction de sa valeur d’orientation, qui doit être un nombre de 1 à 8.",
  field_orientation_tooltipAlt:
    "Diagramme de toutes les valeurs d’orientation potentielles",
  field_originalFilename: "Nom du fichier original",
  field_otherRecordNumbers: "Numéros de collecte",
  field_otherRecordNumbers_tooltip:
    "Autres numéros ou identifiants associés à l’événement de collecte qui permettent de le distinguer. N’incluez PAS les identifiants basés sur les spécimens, tels que les numéros d’accession.",
  field_parentStorageUnit: "Emplacement",
  field_preparationDate: "Date de la préparation",
  field_preparationFixative: "Solution de fixation de la préparation",
  field_preparationFixative_tooltip:
    "Solution qui a été appliquée à l'échantillon de matériau ou dans laquelle il est conservé. Exemples : ETOH 95 %, ETOH 75 %, ETOH 70 %, solution saline, colle.",
  field_preparationMaterials: "Matériel de préparation",
  field_preparationMaterials_tooltip:
    "Autres milieux ou objets physiques, généralement inertes, dans ou sur lesquels l'organisme d'un échantillon de matériau est conservé. Ne correspond pas à l'état de l'organisme ni aux solutions de fixation utilisées, mais plutôt au matériel qui permet de présenter l'organisme. Exemples : épingle, flacon en verre, bocal en plastique, bocal en verre, lame de microscope, papier sans acide, piège collant/plaquette adhésive, tube Eppendorf.",
  field_preparationMethod: "Méthode de préparation",
  field_preparationMethod_tooltip:
    "Substantif désignant le processus utilisé (la méthode) pour préparer l'échantillon de matériau. Exemples : culture, inoculation mécanique, dissection.",
  field_preparationRemarks: "Commentaires sur la préparation",
  field_preparationSubstrate: "Substrat de la préparation",
  field_preparationSubstrate_tooltip:
    "Matériel sur lequel l'organisme de l'échantillon de matériau est présenté ou croît. Exemples : roche, bois, gélose.",
  field_preparationType: "Type de préparation",
  field_preparationType_tooltip:
    "Substantif désignant ce que l'on prépare. Exemples : membre, tissus, ADN",
  field_preservationType: "Type de préservation",
  field_preservationType_tooltip:
    "Description du type de préservation de l'échantillon de matériau. Exemple : lyophilisation.",
  field_projectName: "Nom du projet",
  field_projectStatus: "État du projet",
  field_publiclyReleasable: "Accessible au public",
  field_publiclyReleasable_tooltip:
    "Indique si l’objet peut être diffusé publiquement sur une page Web ou sur des portails de données ouvertes.",
  field_remarks: "Remarques",
  field_restrictToCreatedBy: "Privé",
  field_restrictions: "Restrictions",
  field_sampleName: "Nom de l’échantillon",
  field_scientificName: "Nom scientifique",
  field_scientificNameInput: "Nom scientifique",
  field_sex: "Sexe",
  field_startDate: "Date de début",
  field_startEventDateTime: "Date et heure de l'événement initial",
  field_startEventDateTime_tooltip:
    "Le format de date/heure du début de l’événement doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_tags: "Étiquettes",
  field_title: "Titre",
  "field_title.en": "Titre en anglais",
  "field_title.fr": "Titre en français",
  field_transcriberRemarks: "Notes du transcripteur",
  field_type: "Catégorie",
  field_typeStatus: "Type de statut",
  field_typeStatusEvidence: "Type de statut - Preuve",
  field_useNextSequence: "Utiliser le prochain identifiant disponible",
  field_useTargetOrganism: "Utiliser l'organisme ciblé",
  field_useTargetOrganismError:
    "Sélectionner l'organisme ciblé lorsque l'option Utiliser l'organisme ciblé est activée.",
  field_verbatimDate: "Verbatim - Date",
  field_verbatimDeterminer: "Déterminant verbatim",
  field_verbatimEventDateTime: "Date et heure de l'événement textuel",
  field_verbatimRemarks: "Verbatim - Remarques",
  field_verbatimScientificName: "Verbatim - Nom scientifique",
  field_visibleManagedAttributes: "Attributs gérés visibles",
  field_visibleManagedAttributes_tooltip:
    "Ajouter ou retirer un attribut à l'aide du présent menu déroulant ne modifie pas la valeur. Cela ne fait que modifier la visibilité de l'attribut dans l'éditeur.",
  field_vocabularyElementType_boolean_label: "Booléen",
  field_vocabularyElementType_date_label: "Date",
  field_vocabularyElementType_decimal_label: "Décimal",
  field_vocabularyElementType_integer_label: "Par ordre numérique",
  field_vocabularyElementType_picklist_label: "Liste de sélection",
  field_vocabularyElementType_text_label: "Texte",
  field_webpage: "Page Web",
  field_xmpMetadataDate: "Date d’application des métadonnées",
  field_xmpMetadataDate_tooltip:
    "Date et heure de la dernière mise à jour du dossier.",
  field_xmpRightsWebStatement: "Licence",
  fileTooBig: "Fichier trop volumineux",
  filterAttribute: "Attribut filtre",
  filterByGroup: "Filtrer par groupe",
  filterPredicate: "Prédicat filtre",
  filterValue: "Valeur filtre",
  footerContactInfo: "Coordonnées du contact ",
  footerPrivacy: "Protection de la vie privée",
  footerTermsAndConditions: "Modalités ",
  forTestingPurposesOnlyMessage:
    "Aux fins d’analyse seulement. Seules des données non classifiées peuvent être téléversées. Toute donnée téléversée peut être supprimée, en tout temps. ",
  formNavigation: "Navigation dans les formulaires",
  formTemplate: "Modèle de formulaire",
  formTemplateEditPermission_tooltip:
    "Seul le créateur de ce modèle de formulaire peut modifier ce modèle de formulaire.",
  formTemplateGroupVisibility_tooltip:
    "Veuillez choisir un groupe pour ce modèle de formulaire pour déterminer la visibilité",
  formTemplatePrivate_tooltip:
    "Vous êtes la seule personne à pouvoir visualiser ce modèle de formulaire.",
  formTemplatePublic_tooltip:
    "Tous les membres du groupe {group} peuvent visualiser ce modèle de formulaire.",
  formTemplateSelection: "Vue du formulaire personnalisé",
  formTemplates: "Modèles de formulaires",
  fromDinaUserGuide: "Extrait du Guide de l'utilisateur de DINA.",
  fromParent: "(de {parentLink})",
  generateBatch: "Produire un lot",
  generateLabel: "Générer l'étiquette",
  generateSeries: "Produire une série",
  generatingReport: "Production de rapport...",
  geoReferenceAssertion: "Assertion de géoréférencement",
  geoReferencing: "Géoréférencement",
  geoReferencingLegend: "Géoréférencement",
  geographyLegend: "Géographie (Lieux)",
  geographySearchBoxTooltip:
    'Recherche par nom de lieu (par exemple "Ottawa" ou coordonnées WGS84 [par exemple "40.123, -74.123"])',
  georeferencedByLabel: "Géoréférencé par (agent)",
  georeferencedDateLabel: "Date géoréférencée",
  globalNameSearchLabel: "Recherche de nom globale",
  goToThePreviousStep: "Aller à la prochaine étape",
  governmentOfCanada: "Gouvernement du Canada",
  governmentOfCanadaSymbol: "Symbole du gouvernement du Canada",
  group: "Groupe",
  groupMustBeSelected: "Un groupe doit être sélectionné ",
  hostOrganismLegend: "Organisme hôte",
  http403ForbiddenError: "Accès refusé",
  identifierLegend: "Identifiants",
  identifierType: "Type d’identifiant",
  identifierURI: "Identifiant URI",
  identifiers: "Identifiants",
  includeAll: "Inclure tous",
  insertHybridSymbol: "Insérer le symbole hybride",
  institution: "Établissement",
  institutionListTitle: "Établissements",
  isFiledAs: "Classé en tant que",
  isTargetHeader: "Est-ce ciblé?",
  isolation: "Isolation",
  keepContentsTogether: "Ne pas séparer le contenu",
  languageOfPage: "fra",
  largeImg: "Grande image",
  latLongAutoSetterButton: "Convertir en décimal Lat/Long",
  latitudeValidationError:
    "Latitude invalide : {latitude}, \nLa plage de latitude valide est comprise entre -90 et 90 pour les degrés, et entre 0 et 60 pour les minutes et les secondes",
  literalGeoreferencedByLabel: "Géoréférencé par",
  load: "Charger",
  loading: "Chargement",
  loanTransaction: "Transaction",
  loanTransactionManagedAttributeListTitle:
    "Attributs de prêt et de transaction gérés",
  loanTransactionsSectionTitle: "Transactions",
  locationLabel: "Emplacement",
  longitudeValidationError:
    "Longitude invalide : {longtitude}, \nLa longitude valide est comprise entre -180 et 180 pour les degrés, et entre 0 et 60 pour les minutes et les secondes",
  makeFiledAs: "Indiquer comme Classé en tant que",
  makePrimary: "Marque principale",
  managedAttributeEditTitle: "Modifier l’attribut géré",
  managedAttributeTemplateOrderInfo:
    "Cette disposition des attributs gérés sera sauvegardée dans le modèle de formulaire.",
  managedAttributeValueLabel: "Valeur",
  managedAttributes: "Attributs gérés",
  managedAttributesViews: "Modèles de formulaires",
  "material-sample": "Échantillon de matériau",
  materialDirection_tooltip:
    "Direction du matériau visé par la transaction : {materialDirection}",
  materialIn: "Entrée de matériel",
  materialOut: "Sortie de matériel",
  materialSample: "Échantillon de matériaux",
  materialSampleAssociationLegend: "Association d'échantillons de matériaux",
  materialSampleAttachments: "Pièces jointes de l’échantillon de matériaux",
  materialSampleFieldsMapping: "Champ Échantillon de matériau",
  materialSampleFormTemplate:
    "Modèle de formulaire des échantillons de matériau",
  materialSampleFormTemplates:
    "Modèles de formulaire des échantillons de matériau",
  materialSampleInfo: "Info sur l'échantillon de matière",
  materialSampleListTitle: "Échantillons de matériaux",
  materialSampleManagedAttributes:
    "Attributs gérés de l’échantillon de matière",
  materialSampleName: "Nom de l’échantillon de matière",
  materialSampleSplitConfiguration: "Configuration du fractionnement",
  materialSampleSplitConfigurationCondition: "Condition",
  materialSampleSplitConfigurationConditionType: "Type de condition",
  materialSampleSplitConfigurationDirectParent: "Parent direct",
  materialSampleSplitConfigurationMaterialSampleNameGeneration:
    "Génération du nom de l'échantillon de matériau",
  materialSampleSplitConfigurationRequiredMaterialSampleType:
    "Le type d'échantillon de matériau est requis lorsque la configuration du fractionnement utilise la stratégie Type d'échantillon de matériau",
  materialSampleSplitConfigurationStrategy: "Stratégie",
  materialSampleSplitConfigurationVisibleMaterialSampleType:
    "Le type d'échantillon de matériau doit être visible lorsque la configuration du fractionnement utilise la stratégie Type d'échantillon de matériau",
  materialSampleTypeListTitle: "Types d’échantillon de matière",
  materialSampleViewTitle: "{primaryID} - Échantillon de matériaux",
  materialSamples: "Échantillons de matériaux",
  materialSamplesBulkFinishLabel: "Échantillons de matériaux",
  materialSamplesCreatedLabel: "Échantillons de matériaux créés",
  materialSamplesToCreate: "Échantillons de matériaux à créer",
  metadataAttributesTemplateSave: "Enregistrer ce modèle d’attributs",
  metadataBucketNameLabel: "Nom de la catégorie",
  metadataBuiltInAttributesLabel: "Attributs intégrés",
  metadataBulkEditTagsLabel: "Balises (séparées par une virgule)",
  metadataDcFormatLabel: "Format de l’élément dc",
  metadataExternalResourceDetailsLabel: "Détails sur les ressources externes",
  metadataFileExtensionLabel: "Extension du fichier",
  metadataFileIdentifierLabel: "Identificateur du fichier",
  metadataFileStorageDetailsLabel: "Stockage du fichier",
  metadataFilenameLabel: "Nom du fichier ",
  metadataFirstDigitalVersionCreatedDateLabel:
    "Date de création de la première version numérique",
  metadataFormTitle: "Métadonnées",
  metadataHashFunctionLabel: "Fonction de hachage",
  metadataHashValueLabel: "Valeur de hachage",
  metadataLastMetadataModificationTimeLabel:
    "Date de la dernière modification des métadonnées",
  metadataListGalleryLayout: "Galerie",
  metadataListTableLayout: "Tableau",
  metadataManagedAttributesLabel: "Attributs gérés",
  metadataMediaDetailsLabel: "Média",
  metadataObjectTypeLabel: "Type d’objet stocké",
  metadataPageLink: "Page des détails",
  metadataResourceExternalURLLabel: "URL des ressources externes",
  metadataRightsDetailsLabel: "Droits",
  metadataTagsLabel: "Balises",
  metadataUploadDetailsLabel: "Télécharger les détails",
  metersField_tooltip:
    "Utilisez les unités suivantes pour la conversion automatique : pi, po, pi po, vg, mm, cm, km",
  moveAllContent: "Déplacer tout le contenu",
  multiple: "Multiple",
  multipleMaterialSamples: "Échantillons à matériel multiple",
  multipleUnits: "Multiples unités",
  mustBeValidDecimalValue: "Doit être une valeur décimale valide.",
  mustBeValidIntegerValue: "Doit être une valeur entière valide.",
  noChildren: "Aucune table enfant",
  noFileToDisplay: "Aucun fichier à afficher",
  noGroups: "Aucun groupe",
  noManagedAttributeValues: "Aucune valeur d’attribut géré.",
  noResultsFound: "Aucun résultat trouvé.",
  noneTopLevel: "Aucun (niveau supérieur)",
  notEditableWhenThereAreChildStorageUnits:
    "Non modifiable lorsqu’il y a des unités de stockage enfant ",
  notPubliclyReleasable: "Diffusion publique interdite",
  objectListTitle: "Objets stockés",
  objectStoreDataUnavailable:
    "Les données du stockage de l’objet ne sont pas disponibles",
  objectStoreDetailsTitle: "Détails sur le stockage de l’objet",
  objectStoreTitle: "Dépôt d’objet",
  objectSubtypeListTitle: "Sous-types d’objet",
  objectSubtypeTitle: "Sous-type d’objet",
  openGeographySearchButtonLabel: "Recherche sur Open Street Maps",
  organism: "Organisme",
  organismRemarks: "Organisme Remarques",
  organismState: "État de l'organisme",
  organisms: "Organismes",
  organismsQuantity: "Quantité d'organismes",
  organizationEnglishNameLabel: "Nom anglais ",
  organizationFrenchNameLabel: "Nom français ",
  organizationGermanNameLabel: "Nom allemand ",
  organizationListTitle: "Organisations",
  originalFile: "Fichier original",
  originalMaterialSampleLabel: "Échantillon de matière original",
  overwriteValues: "Écraser les valeurs",
  parentCollectionLabel: "Collection mère",
  parentMaterialSample: "Échantillon de matériau parent",
  parentSampleNotFoundLabel: "Échantillon parent non trouvé",
  partial: "Partiel",
  personListTitle: "Personnes",
  phacAnimalRGLevel: "Niveau de GR animal ASPC",
  phacContainmentLevel: "Niveau de confinement ASPC",
  phacHumanRGLevel: "Niveau GR humain ASPC",
  possibleDataLossWarning:
    "Vous avez des données non enregistrées, êtes-vous certain de vouloir quitter cette page?",
  preparation: "Préparation",
  preparationData: "Données de préparation",
  preparationManagedAttributes: "Préparation des attributs gérés",
  preparationMethodNameLabel: "Nom de la méthode de préparation",
  preparationProtocols: "Protocoles de préparation",
  preparationTypeListTitle: "Type de préparation",
  preparationTypeNameLabel: "Nom du type de préparation",
  preparations: "Préparations",
  preparedBy: "Préparé par",
  previewAndCustomizeLabel: "Prévisualiser et personnaliser",
  previewLabel: "Aperçu",
  previewNotAvailable: "Aperçu non disponible",
  primary: "Principal",
  primaryButton_tooltip:
    "Faites de cette affirmation le point de données principal lors de l’exportation. Une seule hypothèse peut servir d’hypothèse principale",
  primaryId: "No d'identification principal",
  proceedToCreateMetadata: "Passez à la création de métadonnées",
  projectAttachments: "Pièces jointes liées au projet",
  projectListTitle: "Projets",
  projects: "Projets",
  protocolAttachments: "Protocole sur les pièces jointes",
  protocolData: "Données sur le protocole",
  protocolListTitle: "Protocoles",
  protocolNameLabel: "Nom du protocole",
  protocolViewTitle: "Protocole",
  queryBuilder_addSearchGroup: "Ajouter une sous-requête",
  queryBuilder_addSearchRule: "Ajouter une requête",
  queryBuilder_conjunction_and: "ET",
  queryBuilder_conjunction_or: "OU",
  queryBuilder_extension_field_placeholder:
    "Sélectionner le champ Extension pour faire une recherche...",
  queryBuilder_extension_placeholder:
    "Sélectionner Extension pour faire une recherche...",
  queryBuilder_field_placeholder: "Sélectionner le champ à rechercher",
  queryBuilder_managedAttribute_placeholder:
    "Sélectionner Attribut géré pour faire une recherche...",
  queryBuilder_operator_containsDate: "Contient",
  queryBuilder_operator_empty: "Vide",
  queryBuilder_operator_endsWith: "Se termine par",
  queryBuilder_operator_equals: "Est égal à",
  queryBuilder_operator_exactMatch: "Correspondance exacte",
  queryBuilder_operator_greaterThan: "Supérieur à",
  queryBuilder_operator_greaterThanOrEqualTo: "Supérieur ou égal à",
  queryBuilder_operator_lessThan: "Inférieur à",
  queryBuilder_operator_lessThanOrEqualTo: "Inférieur ou égal à",
  queryBuilder_operator_notEmpty: "N'est pas vide",
  queryBuilder_operator_notEquals: "N'est pas égal à",
  queryBuilder_operator_startsWith: "Commence par ",
  queryBuilder_pickList_placeholder: "Sélectionner une valeur acceptée...",
  queryBuilder_value_false: "Faux ",
  queryBuilder_value_number_placeholder: "Saisir le nombre à rechercher",
  queryBuilder_value_text_placeholder: "Saisir le texte à rechercher",
  queryBuilder_value_true: "true",
  reception: "Réception",
  reloadSavedSearch: "Recharger la recherche enregistrée",
  removeAssertionLabel: "Supprimer ce géoréférencement",
  removeComponentData: "Suppression des données de {composant}",
  removeFromParentStorageUnit: "Retirer de l’unité de stockage parent",
  removeGroup: "Supprimer un groupe",
  removeIdentifier: "Supprimer l’identifiant",
  removeManagedAttributeValue:
    "Retirer la valeur de l’attribut géré : {attributeNames}",
  removeOrganism: "Supprimer l'organisme",
  removeSavedSearch: "Supprimer la recherche enregistrée",
  removeThisElement: "Supprimer cette {typeName}",
  removeThisPlaceLabel: " Supprimer ce lieu",
  requiredField: "Champ requis",
  resetMetadataEditorAttributesButtonText:
    "Réinitialiser à la disposition initiale des attributs",
  resetNamesToDefaultValues: "Réinitialiser les noms aux valeurs par défaut",
  restricted: "Avec restriction",
  restrictions: "Restrictions",
  revisionsButtonText: "Révisions",
  revisionsByUserPageTitle: "Révisions par l’utilisateur",
  revisionsListTitle: "Révisions pour {name}",
  role: "Role",
  roleAction: "Rôle/suivi",
  roles: "Rôles",
  rolesPerGroup: "Rôles par groupe",
  runWorkflow: "Exécuter le flux des travaux",
  save: "Enregistrer",
  saveAll: "Enregistrer tout",
  saveAndCopyToNext: "Sauvegarder et copier au prochain",
  saveAndCreateNewMaterialSampleButton:
    "Enregistrer et créer un nouvel échantillon de matière",
  saveAndGoToViewPageButton: "Enregistrer et passer à la page Visualiser",
  saveAndMarkAsComplete: "Sauvegarder et indiquer comme Terminé",
  saveAsDefault: "Enregistrer comme valeur par défaut",
  saveChanges: "Enregistrer les modifications",
  saveGeoReferenceAssertion: "Sauvegarder l’assertion de géoréférence",
  saveSearch: "Enregistrer la recherche",
  saveSearchInstruction:
    "Entrez un nom pour la recherche. Vous pouvez également faire de cette recherche votre recherche par défaut.",
  saveThisOrderView: "Enregistrer cette vue de la commande",
  savedSearchError:
    "Impossible de récupérer les recherches enregistrées, veuillez réessayer plus tard.",
  savedSearchName: "Nom de la recherche enregistrée",
  savedSearchNotFound: "Aucune recherche enregistrée n'a encore été créée.",
  savedSearchOverwriteExisting:
    "Il existe déjà une recherche enregistrée portant le nom « {savedSearchName} ». La création de cette recherche enregistrée écrasera la recherche enregistrée existante.",
  scheduledActions: "Actions prévues",
  scientificNameSearch: "Classification",
  searchButton: "Recherche",
  searchOnCOL: "Chercher dans le Catalogue of Life",
  searchPreviousTags: "Consulter les précédentes étiquettes",
  searchResults: "Résultats de la recherche ({resultSize})",
  searchStorage: "Recherche dans le stockage",
  selectAll: "Sélectionner Tout",
  selectAnExtenstion: "Sélectionner une extension",
  selectCollectorGroupLabel:
    "Sélectionnez un groupe de collecteurs pour prépeupler le champ «Collecteurs»",
  selectColumn: "Sélectionner Colonne",
  selectGroup: "Sélectionnez Groupe",
  selectOrType: "Sélectionner ou taper",
  selectRuleSet: "Sélectionner un ensemble de règles",
  selectSplitConfiguration: "Sélectionner Configuration du fractionnement",
  selectTemplate: "Sélectionner un modèle",
  seriesModeInfo:
    "Mode de traitement en série : les échantillons de matériaux ont des no d'identification croissants.",
  set: "Ensemble",
  setAll: "Tous les ensembles",
  setAsDefault: "Définir par défaut",
  settingLabel: "Paramètres",
  shipmentAddress: "Adresse d'expédition",
  shipmentDetails: "Détails de l'expédition",
  showLess: "Montrer moins",
  showMore: "Montrer plus",
  showing: "Affiché",
  showingFilteredStorageUnits: "Afficher les unités de stockage filtrées",
  showingTopLevelStorageUnits:
    "Afficher les unités de stockage de niveau supérieur",
  skipToAboutThisApplication: "Passer à « À propos de ce site »",
  skipToBasicHtmlVersion: "Passer à la version HTML simplifiée",
  skipToMainContent: "Passer au contenu principal",
  source: "Source",
  specifyParentContainer: "Veuillez sélectionner le contenant parent",
  splitButton: "Diviser",
  splitFrom: "Partie de",
  splitGenerationOptionLabel: "Options de production ",
  splitGenerationOptionLowercase: "a (en lettres minuscules)",
  splitGenerationOptionNumerical: "1 (en chiffre)",
  splitGenerationOptionUppercase: "A (en lettres majuscules)",
  splitMaterialSampleNameRequiredTooltip:
    "Un identifiant principal est requis pour exécuter un fractionnement.",
  splitPreviewGeneratedIdentifierColumn: "Identifiant généré",
  splitPreviewNumberColumn: "Numéro",
  splitSampleActionMetadataLegend: "Métadonnées sur les mesures",
  splitSampleChildSamplesToCreateLabel:
    "Échantillons de matière enfant à créer",
  splitSampleConfigLegend: "Configurer une action : Division ",
  splitSampleDescription:
    "Diviser un échantillon parent en un ou plusieurs échantillons enfant",
  splitSampleInstructions:
    "Le nombre maximum d’échantillons enfant à créer est de 30",
  splitSampleRemarksPlaceholder:
    "Décrivez ce que vous avez fait, ce qui a été modifié, ou ce qui s’est passé en a résulté (par exemple, la suppression d’une partie)",
  splitSampleTagOriginalAsDestroyed: "Identifier l’original comme « Détruit »",
  splitSeriesOptionContinue: "Série continue",
  splitSeriesOptionContinueFromParent: "Série continue à partir d'un parent",
  splitSeriesOptionContinueFromParentTooltip:
    "La série continue à partir d'un parent est seulement disponible si l'échantillon de matériau qui est fractionné a un parent pour continuer la série.",
  splitSeriesOptionContinueTooltip:
    "La série continue est seulement disponible si l'échantillon de matériau qui est fractionné a déjà des enfants pour continuer la série.",
  splitSeriesOptionLabel: "Options de séries",
  splitSeriesOptionNew: "Nouvelle série",
  splitSubsampleTitle: "Division (sous-échantillon)",
  splitWorkflowRunTitle: "Exécuter la division du flux de travail ",
  spreadsheetHeader: "En-tête de la feuille de calcul",
  startNewRunConfigLabel: "Lancer une nouvelle éxécution",
  stateChangeMetaLegend: "Métadonnées sur le changement d'état (optionnel)",
  stateProvinceLabel: "État/province",
  status: "Statut",
  storage: "Stockage",
  storageUnitListTitle: "Unités de stockage",
  storageUnitName: "Nom de l'entrepôt",
  storageUnitType: "Type d’unité de stockage",
  storageUnitTypeListTitle: "Types d’unités de stockage",
  storagesCreatedByMe: "Stockages créés par moi",
  tags: "Étiquettes",
  target: "Cible",
  template: "Modèle",
  thisWillRemoveYourTemplate:
    "Cette opération supprimera les champs du modèle sélectionnés et les valeurs par défaut.",
  thumbnail: "Vignette",
  thumbnailNotAvailableText: "Aucune vignette disponible",
  title_assemblage: "Assemblage",
  title_collectingEvent: "Activité de collecte",
  title_collection: "Collecte",
  title_organism: "Organisme",
  title_person: "Personne",
  title_preparationMethod: "Méthode de préparation",
  title_preparationType: "Type de préparation",
  title_storageUnit: "Unité de stockage",
  title_storageUnitType: "Type d'unité de stockage",
  to: "À",
  toBeReturned: "À retourner",
  tooltipDefaultLinkMessage: "Cliquez ici pour en savoir plus.",
  toponymyLegend: "Lieu géographique actuel",
  totalExtenstionFieldsCount: "Total des champs pour cette extension",
  transactionAttachments: "Pièces jointes à la transaction",
  transactionDetails: "Détails de la transaction",
  transactions: "Transactions",
  type: "Catégorie",
  typeAnythingOrPickAScientificName:
    "Taper quelque chose ou choisir un nom scientifique",
  typeNewTagOrSearchPreviousTags:
    "Entrer la nouvelle étiquette ou consulter les précédentes étiquettes",
  typeSpecimen: "Taper spécimen",
  unit: "Unité: ",
  unsavedChanges: "Modifications non sauvegardées apportées",
  unsetAsDefault: "Ne plus définir par défaut",
  unsupportedFileTypeError:
    'Le fichier "{fileName}" ne peut pas être téléversé puisque ce type de fichier n\'est pas pris en charge.  ',
  updateExistingView: "Mettre à jour la vue existante",
  uploadButtonText: "Téléverser",
  uploadFilesMaxSize: "La taille maximale des fichiers est de {maxSize}",
  uploadFormInstructions:
    "Glisser-déposer les fichiers ici ou cliquer pour ouvrir la fenêtre de dialogue. Seuls les fichiers graphiques, audio, vidéo, .pdf, .doc et .docx sont acceptés.",
  uploadNewAttachments: "Téléverser de nouvelles pièces jointes",
  uploadPageTitle: "Téléverser les fichiers",
  useCollectorGroupLabel: "Utiliser le groupe de collecteurs",
  useLastSelectedOrderView:
    "Utiliser la dernière vue des commandes sélectionnées",
  userListTitle: "Utilisateurs",
  userMustBelongToGroup: "L’utilisateur doit appartenir à un groupe",
  userViewTitle: "Utilisateur",
  valueCad: "Valeur ($ CA)",
  verbatimDeterminationLegend: "Détermination verbatim",
  verbatimEventDateTime: "Date et heure de l’événement Verbatim",
  verbatimLabelLegend: "Étiquette Verbatim",
  verbatimLatLong: "Verbatim Lat/Long",
  viewDetailButtonLabel: "Afficher détails",
  viewOnMap: "Visualiser sur la carte",
  viewPreviewButtonText: "Prévisualiser",
  warningMessage: "Messages d’avertissement",
  whoAmITitle: "Qui suis-je?",
  withAKeyboard: "Avec un clavier",
  withAMouse: "Avec une souris",
  workBookDuplicateFieldMap:
    "Cette colonne ne doit pas être mise en correspondance avec le même champ ({fieldName})",
  workBookInvalidDataFormat:
    "Format de données invalide, feuille : {sheet}, rangée : {index}, champ : {field}, le type de données doit être {dataType}",
  workBookInvalidManagedAttributeDataType:
    "Type de données invalide pour l'attribut géré : la clé d'attribut géré {key} correspond au type de données {type}.",
  workBookInvalidManagedAttributeKey:
    "Clé d'attribut géré invalide : clé d'attribut géré {key} introuvable.",
  workbookGroupUploadTitle: "Téléverser le tableur",
  workbookTitle: "Tableurs",
  workbookUploadFailure:
    "Un problème est survenu lors de la tentative de lecture de la feuille de calcul téléchargée.",
  workbookUploadInstructions:
    "Faites glisser et déposez une feuille de calcul ici ou cliquez pour ouvrir la boîte de dialogue de navigation.",
  year: "Année",
  yearMonth: "Année-Mois",
  yearMonthDay: "Année-Mois-Jour",
  yearMonthDayTime: "Année-Mois-Jour-Heure",
  field_storageUnit: "Unité de stockage",
  field_transactionNumber: "Numéro de transaction",
  field_transactionType: "Type de transaction",
  field_materialDirection: "Direction du matériau",
  field_otherIdentifiers: "Autres identifiants",
  field_purpose: "But",
  field_status: "Statut",
  field_openedDate: "Date d'ouverture",
  field_closedDate: "Date de fermeture",
  field_dueDate: "Date d'échéance"
};
