/**
 * English Object Store messages. A message must be set here in English before other languages.
 */
export const DINAUI_MESSAGES_ENGLISH = {
  addAttributesTemplateTitle: "New Attributes Template",
  addFilesButton: "Add Files",
  addManagedAttributeButtonText: "Add New Managed Attribute",
  addObjectSubtypeTitle: "Add New Object Subtype",
  addOrganizationTitle: "Add New Organization",
  addPersonTitle: "Add Person",
  addPersonButtonText: "Add Person",
  addPersonPopupTooltip: "Add Person without leaving the page",
  agentsSectionTitle: "Agents",
  appTitle: "DINA",
  attributeLabel: "Attribute",
  cancelButtonText: "Cancel",
  changedProperties: "Changes",
  closePreviewButtonText: "Close Preview",
  deleteButtonText: "Delete",
  deleteSelectedButtonText: "Delete Selected",
  dinaUserSectionTitle: "Dina User",
  editObjectSubtypeTitle: "Edit Object Subtype",
  editOrganizationTitle: "Edit Organization",
  editOrganizationAliasesLabel: "Aliases (comma seperated)",
  editPersonTitle: "Edit Person",
  editSelectedButtonText: "Edit Selected",
  exifProperties: "Exif Properties",
  feedbackButtonText: "Feedback",
  field_acceptedValues: "Accepted Values",
  field_acCaption: "Caption",
  field_acSubtype: "Ac Subtype",
  field_acDerivedFrom: "Derived From",
  field_acDigitizationDate: "Date Original Version Created",
  field_acDigitizationDate_tooltip:
    "Date and time of when the digital object described by the metadata was created. For an image it represents when the image was taken.",
  field_acHashFunction: "Hash Function",
  field_acHashValue: "Hash",
  field_acMetadataCreator: "Metadata Created By",
  "field_acMetadataCreator.displayName": "Metadata Created By",
  "field_acMetadataCreator.displayName_tooltip":
    "Agent who created the metadata record.",
  field_acSubType: "Object SubType",
  field_acTags: "Tags",
  "field_dcCreator.displayName": "Digitized By",
  field_attributesTemplate: "",
  field_createdBy: "Created By",
  field_createdDate: "Created Date",
  field_createdOn: "Created On",
  field_dcFormat: "Media Format",
  field_dcRights: "Rights Statement",
  field_dcType: "Stored Object Type",
  field_description: "Description",
  "field_description.en": "English Description",
  "field_description.fr": "French Description",
  field_displayName: "Display Name",
  field_editableBuiltInAttributes: "Built In Attributes",
  field_editableManagedAttributes: "Managed Attributes",
  field_email: "Email",
  field_license: "License",
  field_managedAttributeAcceptedValue: "Accepted Value",
  field_managedAttributeCreatedOn: "Created On",
  field_managedAttributeCreatedBy: "Created By",
  field_managedAttributeMandatoryFieldsError:
    "Both name and type are mandatory fields",
  field_managedAttributeName: "Attribute Name",
  field_managedAttributeType_integer_label: "Numerical",
  field_managedAttributeType_picklist_label: "Pick List",
  field_managedAttributeType_text_label: "Text",
  field_originalFilename: "Original Filename",
  field_organizationMandatoryFieldsError:
    "At least one orgnization name is required",
  field_publiclyReleasable: "Publicly releasable",
  field_publiclyReleasable_tooltip:
    "Indicates if the object could be released publicly on a web page or open data portals.",
  field_type: "Type",
  field_xmpMetadataDate: "Last Updated On",
  field_xmpMetadataDate_tooltip:
    "Date and time of when the record was last updated.",
  field_xmpRightsWebStatement: "Reuse Rights Statement",
  footerContactInfo: "Contact information",
  footerTermsAndConditions: "Terms and conditions",
  footerPrivacy: "Privacy",
  forTestingPurposesOnlyMessage:
    "For testing purpose only. Only unclassified data should be uploaded. Any uploaded data can be deleted at any given moment.",
  governmentOfCanada: "Government of Canada",
  groupMustBeSelected: "Group must be selected",
  managedAttributeEditTitle: "Edit Managed Attribute",
  managedAttributeListTitle: "Managed Attributes",
  managedAttributeValueLabel: "Value",
  metadataAttributesTemplateSave: "Save This Attributes Template",
  metadataBucketNameLabel: "Bucket Name",
  metadataBuiltInAttributesLabel: "Built-in Attributes",
  metadataBulkEditTagsLabel: "Tags (Comma-separated)",
  metadataBulkEditTitle: "Edit Metadata",
  metadataDcFormatLabel: "DcFormat",
  metadataDetailsPageLink: "Details Page",
  metadataFileExtensionLabel: "File Extension",
  metadataFileIdentifierLabel: "File Identifier",
  metadataFileStorageDetailsLabel: "File Storage",
  metadataFilenameLabel: "File Name",
  metadataFirstDigitalVersionCreatedDateLabel:
    "First Digital Version Created Date",
  metadataFormTitle: "Metadata",
  metadataHashFunctionLabel: "Hash Function",
  metadataHashValueLabel: "Hash Value",
  metadataLastMetadataModificationTimeLabel: "Last Metadata Modification Time",
  metadataListGalleryLayout: "Gallery",
  metadataListTableLayout: "Table",
  metadataManagedAttributesLabel: "Managed Attributes",
  metadataMediaDetailsLabel: "Media",
  metadataObjectTypeLabel: "Stored Object Type",
  metadataPageLink: "Details Page",
  metadataRevisionsListTitle: "Revisions for {name}",
  metadataRightsDetailsLabel: "Rights",
  metadataTagsLabel: "Tags",
  metadataUploadDetailsLabel: "Upload Details",
  noFileToDisplay: "No file to display",
  objectListTitle: "Stored Objects",
  objectStoreDetailsTitle: "Object Store Details",
  objectStoreTitle: "Object Store",
  objectSubtypeListTitle: "Object Subtypes",
  objectSubtypeTitle: "Object Subtype",
  organizationEnglishNameLabel: "English Name",
  organizationFrenchNameLabel: "French Name",
  organizationListTitle: "Organizations",
  organizationViewTitle: "View Organization",
  personListTitle: "Persons",
  personViewTitle: "View Person",
  revisionsButtonText: "Revisions",
  revisionsByUserPageTitle: "Revisions by user",
  searchButton: "Search",
  thumbnailNotAvailableText: "No thumbnail available",
  uploadButtonText: "Upload",
  uploadFormInstructions:
    "Drag and drop files here or click to open browse dialog. Only image, audio, video, .pdf, .doc and docx are accepted.",
  uploadPageTitle: "Upload Files",
  userMustBelongToGroup: "User must belong to a Group",
  valueLabel: "Value",
  viewPreviewButtonText: "Preview",
  whoAmITitle: "Who Am I"
};
