/**
 * English Object Store messages. A message must be set here in English before other languages.
 */
export const DINAUI_MESSAGES_ENGLISH = {
  addAnotherAssertion: "Add Another GeoReference",
  addAssertion: "Add GeoReference",
  addAttachments: "Add Attachments",
  addAttributesTemplateTitle: "New Attributes Template",
  addNewChildStorageUnit: "Add New Child Storage Unit",
  addCataloguedObjectTitle: "Add Catalogued Object",
  addCollectingEventTitle: "Add Collecting Event",
  addCollectionTitle: "Add Collection",
  addCollectorGroupTitle: "Add Collector Group",
  addCustomPlaceName: "Add",
  addExistingStorageUnitAsChild: "Add Existing Storage Unit as Child",
  addFilesButton: "Add Files",
  addGroup: "Add Group",
  addManagedAttributeButtonText: "Add New Managed Attribute",
  addMaterialSampleTitle: "Add Material Sample",
  addMaterialSampleTypeTitle: "Add Material Sample Type",
  addNewPerson: "Add New Person",
  addObjectSubtypeTitle: "Add New Object Subtype",
  addOrganizationTitle: "Add New Organization",
  addPersonButtonText: "Add Person",
  addPersonPopupTooltip: "Add Person without leaving the page",
  addPersonTitle: "Add Person",
  addPreparationTypeTitle: "Add Preparation Type",
  addRule: "Add Rule",
  addRuleSet: "Add Rule Set",
  addStorageUnitTitle: "Add Storage Unit",
  addStorageUnitTypeTitle: "Add Storage Unit Type",
  agentsSectionTitle: "Agents",
  allowExisting: "Allow Existing",
  allowNew: "Allow New",
  appTitle: "DINA",
  assignToStorage: "Assign to Storage",
  assignedStorage: "Assigned Storage",
  assignContentsToNewStorage: "Assign Contents to New Storage",
  associatedAgent: "Associated Agent",
  attachExisting: "Attach Existing",
  attachExistingObjects: "Attach Existing Objects",
  attachSelected: "Attach Selected",
  attachedCollectingEvent: "Attached Collecting Event",
  attachments: "Attachments",
  attributeLabel: "Attribute",
  baseNameLabel: "Base Name",
  browseContents: "Browse Contents",
  browseStorageTree: "Browse Storage Tree",
  cancelButtonText: "Cancel",
  cataloguedObjectListTitle: "Catalogued Objects",
  cataloguedObjectViewTitle: "View Catalogued Object",
  changedProperties: "Changes",
  childMaterialSamplesCreatedLabel: "Child Material Samples Created",
  closePreviewButtonText: "Close Preview",
  collectingAgentsLegend: "Collecting Agents",
  collectingDateLegend: "Collecting Date",
  collectingEvent: "Collecting Event",
  collectingEventAttachments: "Collecting Event Attachments",
  collectingEventDetailsPageLink: "Collecting Event Details Page",
  collectingEventListTitle: "Collecting Event",
  collectingEventManagedAttributes: "Collecting Event Managed Attributes",
  collectingEventViewTitle: "View Collecting Event",
  collectingLocationLegend: "Collecting Location",
  collectionListTitle: "Collections",
  collectionManagedAttributeListTitle: "Collection Module Managed Attributes",
  collectionSectionTitle: "Collections",
  collectionViewTitle: "Collection",
  collectorGroupAgentsLabel: "Collector Group Agents",
  collectorGroupListTitle: "Collector Group",
  collectorGroupNameLabel: "Collector Group Name",
  collectorGroupViewTitle: "View Collector Group",
  components: "Components",
  configureAction: "Configure Action",
  configureDefaultValues: "Configure default values",
  coordinateUncertaintyInMeters: "Coordinate Uncertainty In Meters",
  copyFromParentLabel: "Copy From Parent",
  countryLabel: "Country",
  creatNewWorkflow: "Create New",
  createSplitWorkflow: "Create Split",
  createWorkflowTemplateTitle: "Create Workflow Template",
  customPlaceName: "Custom Place Name",
  dataEntryLabel: "Data Entry",
  decimalLatLong: "Decimal Lat/Long",
  decimalLatitude: "Decimal Latitude",
  decimalLongitude: "Decimal Longitude",
  defaultValuesConfig: "Default Values Config",
  defaultValuesConfigs: "Default Values Configs",
  deleteButtonText: "Delete",
  deleteConfig: "Delete Config",
  deleteSelectedButtonText: "Delete Selected",
  deleteThisAttributesTemplate: "Delete This Template",
  deleted: "Deleted",
  deletedMetadata_tooltip: "Deleted Metadata ID: {id}",
  destroyOriginal: 'Tag Original as "Destroyed"',
  detachCollectingEvent: "Detach Collecting Event",
  detachSelectedButtonText: "Detach Selected",
  detailsPageLink: "Details Page",
  dinaHomeH1: "Dina Home",
  dinaUserSectionTitle: "Users",
  duplicateFilesFound: "duplicate files found",
  editCataloguedObjectTitle: "Edit Catalogued Object",
  editCollectingEventTitle: "Edit Collecting Event",
  editCollectionTitle: "Edit Collection",
  editDinaUserTitle: "Edit User",
  editMaterialSampleTitle: "Edit Material Sample",
  editMaterialSampleTypeTitle: "Edit Material Sample Type",
  editMetadataTitle: "Edit Metadata",
  editObjectSubtypeTitle: "Edit Object Subtype",
  editOrganizationAliasesLabel: "Aliases (Comma-separated)",
  editOrganizationTitle: "Edit Organization",
  editPersonTitle: "Edit Person",
  editPreparationTypeTitle: "Edit Preparation Type",
  editSelectedAttachmentMetadata: "Edit Selected Attachment Metadata",
  editSelectedButtonText: "Edit Selected",
  editStorageUnitTitle: "Edit Storage Unit",
  editStorageUnitTypeTitle: "Edit Storage Type",
  editWorkflowTemplateTitle: "Edit Workflow Template",
  enableDateRangeLabel: "Enable Date Range",
  endEventDateTimeLabel: "End Event DateTime (YYYY-MM-DDTHH:MM:SS.MMM)",
  exifProperties: "Exif Properties",
  existingAttachments: "Existing Attachments",
  feedbackButtonText: "Feedback",
  field_acCaption: "Caption",
  field_acDerivedFrom: "Derived From",
  field_acDigitizationDate: "Date Original Version Created",
  field_acDigitizationDate_tooltip:
    "Date and time of when the digital object described by the metadata was created. For an image it represents when the image was taken.",
  field_acHashFunction: "Hash Function",
  field_acHashValue: "Hash",
  field_acMetadataCreator: "Uploaded By",
  "field_acMetadataCreator.displayName": "Uploaded By",
  "field_acMetadataCreator.displayName_tooltip":
    "Agent who created the metadata record.",
  field_acSubtype: "Object Subtype",
  field_acTags: "Tags",
  field_acceptedValues: "Accepted Values",
  field_aliases: "Aliases",
  field_attributesTemplate: "Set Attributes Template",
  field_collectingEvent_endDateTimeError:
    "End event datetime format must be a subset of : YYYY-MM-DDTHH:MM:SS.MMM, if datetime is present, 'T' is mandatory",
  field_collectingEvent_startDateTimeError:
    "Start event datetime format must be a subset of: YYYY-MM-DDTHH:MM:SS.MMM, if datetime is present, 'T' is mandatory",
  field_collectorGroup_agentsError:
    "At lease one agent should be specified for the group",
  field_collectors: "Collectors",
  field_createdBy: "Created By",
  field_createdDate: "Created Date",
  field_createdOn: "Created On",
  "field_dcCreator.displayName": "Digitized By",
  field_dcFormat: "Media Format",
  field_dcRights: "Copyright",
  field_dcType: "Stored Object Type",
  field_description: "Description",
  "field_description.en": "English Description",
  "field_description.fr": "French Description",
  field_displayName: "Display Name",
  field_dwcCatalogNumber: "Catalog Number",
  field_dwcCountry: "Country",
  field_dwcCountryCode: "Country Code",
  field_dwcGeodeticDatum: "Geodetic Datum",
  field_dwcGeodeticDatum_tooltip:
    "The geodetic datum upon which the geographic coordinates given in decimalLatitude and decimalLongitude is based. Recommended best practice is to use the EPSG code. Examples: EPSG:4326 (EPSG code for WGS84)",
  field_dwcGeoreferenceProtocol: "Georeference Protocol",
  field_dwcGeoreferenceProtocol_tooltip:
    "A description or reference to the methods used to determine the spatial footprint, coordinates, and uncertainties.",
  field_dwcGeoreferenceRemarks: "Georeference Remarks",
  field_dwcGeoreferenceRemarks_tooltip:
    "Notes or comments about the spatial description determination, explaining assumptions made in addition or opposition to the those formalized in the method referred to in georeferenceProtocol.",
  field_dwcGeoreferenceSources: "Georeference Sources",
  field_dwcGeoreferenceSources_tooltip:
    "A list of maps, gazetteers, or other resources used to georeference the Location, described specifically enough to allow anyone in the future to use the same resources.",
  field_dwcGeoreferenceVerificationStatus: "Georeferencing Not Possible",
  field_dwcMunicipality: "Municipality",
  field_dwcOtherCatalogNumbers: "Other Catalog Numbers",
  field_dwcOtherRecordNumbers: "Collection Numbers",
  field_dwcOtherRecordNumbers_tooltip:
    "Other numbers or identifiers associated with the collecting event that help to distinguish it. Do NOT include specimen-based identifiers such as accession numbers.",
  field_dwcRecordNumber: "Collector's Number",
  field_dwcRecordedBy: "Verbatim Collectors",
  field_dwcStateProvince: "State/Province",
  field_dwcVerbatimCoordinateSystem: "Verbatim Coordinate System",
  field_dwcVerbatimCoordinateSystem_tooltip:
    "The coordinate format for the verbatimLatitude and verbatimLongitude or the verbatimCoordinates of the Location. Examples: decimal degrees, degrees decimal minutes, degrees minutes seconds, UTM",
  field_dwcVerbatimCoordinates: "Verbatim Coordinates",
  field_dwcVerbatimCoordinates_tooltip:
    "The verbatim original spatial coordinates of the Location. The coordinate ellipsoid, geodeticDatum, or full Spatial Reference System (SRS) for these coordinates should be stored in verbatimSRS and the coordinate system should be stored in verbatimCoordinateSystem. Examples: 41 05 54S 121 05 34W, 17T 630000 4833400",
  field_dwcVerbatimDepth: "Verbatim Depth",
  field_dwcVerbatimDepth_tooltip:
    "The original description of the depth below the local surface. Example: 100-200 m",
  field_dwcVerbatimElevation: "Verbatim Elevation",
  field_dwcVerbatimElevation_tooltip:
    "The original description of the elevation (altitude, above sea level) of the Location. Example: 100-200 m",
  field_dwcVerbatimLatitude: "Verbatim Latitude",
  field_dwcVerbatimLatitude_tooltip:
    "The verbatim original latitude of the Location. The coordinate ellipsoid, geodeticDatum, or full Spatial Reference System (SRS) for these coordinates should be stored in verbatimSRS and the coordinate system should be stored in verbatimCoordinateSystem. Example: 41 05 54.03S",
  field_dwcVerbatimLocality: "Verbatim Locality",
  field_dwcVerbatimLongitude: "Verbatim Longitude",
  field_dwcVerbatimLongitude_tooltip:
    "The verbatim original longitude of the Location. The coordinate ellipsoid, geodeticDatum, or full Spatial Reference System (SRS) for these coordinates should be stored in verbatimSRS and the coordinate system should be stored in verbatimCoordinateSystem. Example: 121d 10′ 34″ W",
  field_dwcVerbatimSRS: "Verbatim SRS",
  field_dwcVerbatimSRS_tooltip:
    "The ellipsoid, geodetic datum, or spatial reference system (SRS) upon which coordinates given in verbatimLatitude and verbatimLongitude, or verbatimCoordinates are based. Recommended best practice is to use the EPSG code of the SRS, if known. Examples: EPSG:4326, WGS84, NAD27",
  field_editableBuiltInAttributes: "Visible Built In Attributes",
  field_editableManagedAttributes: "Visible Managed Attributes",
  field_email: "Email",
  field_familyNames_tooltip: "Family name(s) including compound family names",
  field_givenNames_tooltip: "First and all middle names",
  field_license: "License",
  field_managedAttributeComponent: "Target Data Component Type",
  field_managedAttributeCreatedBy: "Created By",
  field_managedAttributeCreatedOn: "Created On",
  field_managedAttributeMandatoryFieldsError:
    "Both name and type are mandatory fields",
  field_managedAttributeName: "Attribute Name",
  field_managedAttributeType_integer_label: "Numerical",
  field_managedAttributeType_picklist_label: "Pick List",
  field_managedAttributeType_text_label: "Text",
  field_materialSampleName: "Material Sample ID",
  "field_materialSampleType.name": "Material Sample Type",
  "field_materialSampleType.uuid": "Material Sample Type",
  field_materialSample_identifierType_catalogueNumber_label: "Catalogue Number",
  field_materialSample_identifierType_materialSampleId_label:
    "Material Sample ID",
  field_notPubliclyReleasableReason: "Not Publicly Releasable Reason",
  field_organizationMandatoryFieldsError:
    "At least one orgnization name is required",
  field_orientation: "Orientation",
  field_orientation_tooltip:
    "Determines the way an image should be displayed based on its orientation value, must be a number from 1 to 8.",
  field_orientation_tooltipAlt:
    "Diagram of all the possible orientation values.",
  field_originalFilename: "Original Filename",
  field_parentStorageUnit: "Location",
  field_preparationType: "Preparation Type",
  field_publiclyReleasable: "Publicly releasable",
  field_publiclyReleasable_tooltip:
    "Indicates if the object could be released publicly on a web page or open data portals.",
  field_type: "Type",
  field_xmpMetadataDate: "Last Updated On",
  field_xmpMetadataDate_tooltip:
    "Date and time of when the record was last updated.",
  field_xmpRightsWebStatement: "License",
  fileTooBig: "File too big",
  filterByGroup: "Filter By Group",
  footerContactInfo: "Contact information",
  footerPrivacy: "Privacy",
  footerTermsAndConditions: "Terms and conditions",
  forTestingPurposesOnlyMessage:
    "For testing purpose only. Only unclassified data should be uploaded. Any uploaded data can be deleted at any given moment.",
  formNavigation: "Form Navigation",
  generateBatch: "Generate Batch",
  generateSeries: "Generate Series",
  geoReferencing: "Geo-Referencing",
  geoReferencingLegend: "Georeferencing",
  geographyLegend: "Geography (Places)",
  geographySearchBoxTooltip:
    'Search by place name (e.g. "Ottawa" or WGS84 coordinates (e.g. "40.123, -74.123"))',
  georeferencedByLabel: "Georeferenced By (agent)",
  georeferencedDateLabel: "Georeferenced Date",
  governmentOfCanada: "Government of Canada",
  group: "Group",
  groupMustBeSelected: "Group must be selected",
  identifiers: "Identifiers",
  includeAll: "Include All",
  largeImg: "Large Image",
  latLongAutoSetterButton: "Convert to Decimal Lat/Long",
  latitudeValidationError:
    "Invalid latitude: {latitude},   \nValid latitude range is between -90 to 90 for degree, and 0 to 60 for minute and second",
  literalGeoreferencedByLabel: "Georeferenced By",
  locationDescriptionLegend: "Location Description",
  locationLabel: "Location",
  longitudeValidationError:
    "Invalid longitude: {longtitude},   \nValid longitude is between -180 to 180 for degree, and 0 to 60 for minute and second",
  makePrimary: "Make Primary",
  managedAttributeEditTitle: "Edit Managed Attribute",
  managedAttributeListTitle: "Managed Attributes",
  managedAttributeValueLabel: "Value",
  materialSample: "Material Sample",
  materialSampleAttachments: "Material Sample Attachments",
  materialSampleListTitle: "Material Samples",
  materialSampleManagedAttributes: "Material Sample Managed Attributes",
  materialSampleName: "Material Sample Name",
  materialSampleTypeListTitle: "Material Sample Types",
  materialSampleTypeViewTitle: "Material Sample Type",
  materialSampleViewTitle: "Material Sample",
  metadataAttributesTemplateSave: "Save This Attributes Template",
  metadataBucketNameLabel: "Bucket Name",
  metadataBuiltInAttributesLabel: "Built-in Attributes",
  metadataBulkEditTagsLabel: "Tags (Comma-separated)",
  metadataBulkEditTitle: "Edit Metadata",
  metadataDcFormatLabel: "DcFormat",
  metadataFileExtensionLabel: "File Extension",
  metadataFileIdentifierLabel: "File Identifier",
  metadataFileStorageDetailsLabel: "File Storage",
  metadataFilenameLabel: "File Name",
  metadataFirstDigitalVersionCreatedDateLabel:
    "First Digital Version Created Date",
  metadataFormTitle: "Metadata",
  metadataHashFunctionLabel: "Hash Function",
  metadataHashValueLabel: "Hash Value",
  metadataLastMetadataModificationTimeLabel: "Last Metadata Modification Time",
  metadataListGalleryLayout: "Gallery",
  metadataListTableLayout: "Table",
  metadataManagedAttributesLabel: "Managed Attributes",
  metadataMediaDetailsLabel: "Media",
  metadataObjectTypeLabel: "Stored Object Type",
  metadataPageLink: "Details Page",
  metadataRightsDetailsLabel: "Rights",
  metadataTagsLabel: "Tags",
  metadataUploadDetailsLabel: "Upload Details",
  moveAllContent: " Move All Content",
  noFileToDisplay: "No file to display",
  noGroups: "No Groups",
  noManagedAttributeValues: "No Managed Attribute values.",
  noNestedStorageUnits: "No Nested Storage Units",
  noResultsFound: "No results found.",
  noneTopLevel: "None (Top-level)",
  notEditableWhenThereAreChildStorageUnits:
    "Not editable when there are child Storage Units.",
  objectListTitle: "Stored Objects",
  objectStoreDataUnavailable: "Object Store data unavailable",
  objectStoreDetailsTitle: "Object Store Details",
  objectStoreTitle: "Object Store",
  objectSubtypeListTitle: "Object Subtypes",
  objectSubtypeTitle: "Object Subtype",
  openGeographySearchButtonLabel: "Search On Open Street Maps",
  organizationEnglishNameLabel: "English Name",
  organizationFrenchNameLabel: "French Name",
  organizationListTitle: "Organizations",
  organizationViewTitle: "View Organization",
  originalFile: "Original File",
  originalMaterialSampleLabel: "Original Material Sample",
  parentSampleNotFoundLabel: " Parent sample not found",
  personListTitle: "Persons",
  personViewTitle: "Person",
  preparation: "Preparation",
  preparationData: "Preparation Data",
  preparationTypeListTitle: "Preparation Type",
  preparationTypeNameLabel: "Preparation Type Name",
  preparationTypeViewTitle: "View Preparation Type",
  preparations: "Preparations",
  preparedBy: "Prepared By",
  previewAndCustomizeLabel: "Preview and Customize",
  primary: "Primary",
  primaryButton_tooltip:
    "Make this assertion the primary data point when exported. Only one assertion can be primary",
  proceedToCreateMetadata: "Proceed to Create Metadata",
  removeAssertionLabel: "Remove this GeoReference",
  removeComponentData: "Remove {component} data",
  removeFromParentStorageUnit: "Remove From Parent Storage Unit",
  removeGroup: "Remove Group",
  removeManagedAttributeValue:
    "Remove Managed Attribute Value: {attributeNames}",
  removeThisPlaceLabel: " Remove this Place",
  resetMetadataEditorAttributesButtonText: "Reset to initial attributes layout",
  revisionsButtonText: "Revisions",
  revisionsByUserPageTitle: "Revisions by user",
  revisionsListTitle: "Revisions for {name}",
  role: "Role",
  roles: "Roles",
  rolesPerGroup: "Roles Per Group",
  runWorkflow: "Run Workflow",
  saveGeoReferenceAssertion: "Save GeoReference Assertion",
  searchButton: "Search",
  searchResults: "Search Results ({resultSize})",
  searchStorage: "Search Storage",
  selectCollectorGroupLabel:
    "Select a collector group to pre-poplulate 'Collectors' field",
  selectGroup: "Select Group",
  set: "Set",
  setAll: "Set All",
  showing: "Showing",
  showingFilteredStorageUnits: "Showing Filtered Storage Units",
  showingTopLevelStorageUnits: "Showing Top Level Storage Units",
  specifyParentContainer: "Please select parent container",
  splitSampleActionMetadataLegend: "Action Metadata",
  splitSampleChildSamplesToCreateLabel: "Child Material Samples to create",
  splitSampleConfigLegend: "Configure Action: Split",
  splitSampleDescription:
    "Split a Parent Sample into one or more Child Samples",
  splitSampleInstructions: "Max number of child samples to create is 30",
  splitSampleRemarksPlaceholder:
    " Describe what you did, what was changed, or what happened as a result. (i.e. removed leg)",
  splitSampleTagOriginalAsDestroyed: 'Tag Original as "Destroyed"',
  splitSubsampleTitle: "Split(Subsample)",
  splitWorkflowRunTitle: "Split Workflow Run",
  startEventDateTimeLabel: "Start Event DateTime (YYYY-MM-DDTHH:MM:SS.MMM)",
  startNewRunConfigLabel: "Start a New Run ",
  stateProvinceLabel: "State/Province",
  storage: "Storage",
  storageUnitListTitle: "Storage Units",
  storageUnitType: "Storage Unit Type",
  storageUnitTypeListTitle: "Storage Unit Types",
  storageUnitViewTitle: "Storage Unit",
  storagesCreatedByMe: "Storages Created By Me",
  suffixOptional: "Suffix (Optional)",
  switchToActionType: 'Switch to "{actionType}".',
  templateNameMandatoryErrorMsg: "Please enter a workflow template name.",
  thisWillRemoveYourTemplate:
    "This will remove your selected template fields and default values.",
  thumbnail: "Thumbnail",
  thumbnailNotAvailableText: "No thumbnail available",
  to: "To",
  tooltipDefaultLinkMessage: "Click here to learn more.",
  toponymyLegend: "Current Geographic Place",
  uploadButtonText: "Upload",
  uploadFilesMaxSize: "The maximum file size is {maxSize}.",
  uploadFormInstructions:
    "Drag and drop files here or click to open browse dialog.",
  uploadNewAttachments: "Upload New Attachments",
  uploadPageTitle: "Upload Files",
  useCollectorGroupLabel: "Use Collector Group",
  userListTitle: "Users",
  userMustBelongToGroup: "User must belong to a Group",
  userViewTitle: "User",
  verbatimEventDateTimeLabel: "Verbatim Event DateTime",
  verbatimLabelLegend: "Verbatim Label",
  verbatimLatLong: "Verbatim Lat/Long",
  viewDetailButtonLabel: " View Detail",
  viewOnMap: "View on Map",
  viewPreviewButtonText: "Preview",
  warningMessage: "Warning Message",
  whoAmITitle: "Who Am I",
  workflowCompleteTitle: "Workflow Complete",
  workflowTemplateListTitle: "Workflow Templates",
  workflowTemplateTitle: "Workflow Template",
  year: "Year",
  yearMonth: "Year-Month",
  yearMonthDay: "Year-Month-Day",
  yearMonthDayTime: "Year-Month-Day-Time"
};
