import { DINAUI_MESSAGES_ENGLISH } from "./dina-ui-en";

export const DINAUI_MESSAGES_FRENCH: Partial<typeof DINAUI_MESSAGES_ENGLISH> = {
  actionType: "Type d'action",
  addAnother: "Ajouter un autre {typeName}",
  addAnotherIdentifier: "Ajouter un autre identifiant",
  addAssertion: "Ajouter une géoréférence",
  addAttachments: "Ajouter des pièces jointes",
  addAttributesTemplateTitle: "Nouveau modèle d’attributs",
  addCataloguedObjectTitle: "Ajouter un objet catalogué",
  addCollectingEventTitle: "Ajouter un événement de collecte",
  addCollectionMethodTitle: "Ajouter une méthode de prélèvement",
  addCollectionTitle: "Ajouter une collection",
  addCollectorGroupTitle: "Ajouter un groupe de collecte",
  addCustomPlaceName: "Ajouter",
  addDetermination: "Ajouter une détermination",
  addExistingStorageUnitAsChild:
    "Ajouter une unité de stockage existante comme enfant",
  addFilesButton: "Ajouter des fichiers",
  addGroup: "Ajouter un groupe",
  addIdentifier: "Ajouter un identifiant",
  addInstitutionTitle: "Ajouter un établissement",
  addManagedAttributeButtonText: "Ajouter un nouvel attribut géré",
  addManagedAttributeTitle: "Ajouter un nouvel attribut géré",
  addMaterialSampleTitle: "Ajouter un échantillon de matériau",
  addMaterialSampleTypeTitle: "Ajouter un type d’échantillon de matière",
  addNewChildStorageUnit: "Ajouter une nouvelle unité de stockage pour enfant",
  addNewPerson: "Ajouter nouvelle personne",
  addObjectSubtypeTitle: "Ajouter un nouveau sous-type d’objet",
  addOrganizationTitle: "Ajouter une nouvelle organisation",
  addPersonButtonText: "Ajouter une personne",
  addPersonPopupTooltip: "Ajouter une personne sans quitter la page",
  addPersonTitle: "Ajouter une personne",
  addPreparationTypeTitle: "Ajouter un type de préparation",
  addRule: "Ajouter une règle",
  addRuleSet: "Ajouter un ensemble de règles",
  addScheduledAction: "Ajouter une action prévue",
  addStorageUnitTitle: "Ajouter une unité de stockage",
  addStorageUnitTypeTitle: "Ajouter un type d’unité de stockage",
  agentsSectionTitle: "Agents",
  allowExisting: "Autoriser l’existant",
  allowNew: "Autoriser le nouveau",
  appTitle: "DINA",
  assignContentsToNewStorage: "Assigner le contenu au nouveau stockage",
  assignedStorage: "Stockage assigné",
  assignedTo: "Attribué à",
  assignToStorage: "Assigner au stockage",
  associatedAgent: "Agent associé",
  attachExisting: "Joindre l’existant",
  attachExistingObjects: "Joindre des objets existants",
  attachSelected: "Joindre la sélection",
  attachments: "Pièces jointes",
  attributeLabel: "Attribut",
  baseNameLabel: "Nom de base",
  browseContents: "Parcourir le contenu",
  browseStorageTree: "Parcourir l’arborescence de stockage",
  cancelButtonText: "Annuler",
  cataloguedObjectListTitle: "Objets catalogués",
  changedProperties: "Modifications",
  childMaterialSamples: "Sous-échantillons de matière",
  childMaterialSamplesCreatedLabel: "Création d’échantillons de matière enfant",
  closePreviewButtonText: "Fermer la prévisualisation",
  collectingAgentsLegend: "Agents de collecte",
  collectingDateLegend: "Date de collecte",
  collectingEvent: "Événement de collecte",
  collectingEventAttachments: "Pièces jointes de l’événement de collecte",
  collectingEventDetails: "Détails de l'activité de collecte",
  collectingEventListTitle: "Événement de collecte",
  collectingEventManagedAttributes:
    "Attributs gérés de l’événement de collecte",
  collectingLocationLegend: "Lieu de collecte",
  collection: "Prélèvement",
  collectionListTitle: "Collections",
  collectionManagedAttributeListTitle:
    "Attributs gérés du module de collections",
  collectionMethodNameLabel: "Nom de la méthode de prélèvement",
  collectionMethodListTitle: "Méthode de prélèvement",
  collectionSectionTitle: "Collections",
  collectionViewTitle: "Collection",
  collectorGroupAgentsLabel: "Agents du groupe de collecte",
  collectorGroupListTitle: "Groupe de collecte",
  collectorGroupNameLabel: "Nom du groupe de collecte",
  colSearchBoxTooltip: "Rechercher dans le Catalogue de la vie",
  colSearchLabel: "Recherche de nom",
  components: "Composants",
  configureAction: "Configurer l’action",
  configureDefaultValues: "Configurer les valeurs par défaut",
  convertToElevationMinMax: "Conversion de l’élévation min/max",
  convertToDepthMinMax: "Conversion de la profondeur min/max",
  coordinateUncertaintyInMeters: "Coordonner l’incertitude en mètres",
  copyFromParentLabel: "Copier du parent",
  countryLabel: "Pays",
  creatNewWorkflow: "Créer nouveau",
  createSplitWorkflow: "Créer un fractionnement",
  createWorkflowTemplateTitle: "Créer un modèle de flux des travaux",
  customPlaceName: "Nom de lieu personnalisé",
  dataComponents: "Éléments de données",
  dataEntryLabel: "Saisie de données",
  dataset: "Ensemble de données",
  datasetSearchTooltip:
    "Pour utiliser un ensemble de données différent du Catalogue de la vie.",
  decimalLatLong: "Lat/Long décimales",
  decimalLatitude: "Latitude décimale",
  decimalLongitude: "Longitude décimale",
  defaultValuesConfig: "Configuration des valeurs par défaut ",
  defaultValuesConfigs: "Configurations des valeurs par défaut ",
  deleteButtonText: "Supprimer",
  deleteConfig: "Supprimer la configuration",
  deleteSelectedButtonText: "Supprimer les éléments sélectionnés",
  deleteThisAttributesTemplate: "Supprimer ce modèle",
  deleted: "Supprimé",
  deletedMetadata_tooltip: "ID de métadonnées supprimées : {id}",
  depthInMeters: "Profondeur en mètres",
  destroyOriginal: "Identifier l’original comme « Détruit »",
  detachCollectingEvent: "Détacher l’événement de collecte",
  detachSelectedButtonText: "Détacher la sélection",
  detailsPageLink: "Page des détails",
  determination: "Détermination",
  determinations: "Déterminations",
  determiningAgents: "Établissement des agents",
  determiningDate: "Établissement de la date",
  dinaHomeH1: "Dina Accueil",
  dinaUserSectionTitle: "Utilisateur Dina ",
  duplicateFilesFound: "fichiers en double trouvés",
  editCataloguedObjectTitle: "Modifier un objet catalogué",
  editCollectingEventTitle: "Modifier l’événement de collecte",
  editCollectionMethodTitle: "Modifier la méthode de prélèvement",
  editCollectionTitle: "Modifier la collection",
  editDinaUserTitle: "Modifier l’utilisateur",
  editInstitutionTitle: "Modifier l’établissement",
  editManagedAttributeTitle: "Modifier l’attribut géré",
  editMaterialSampleTitle: "Modifier l’échantillon de matériaux",
  editMaterialSampleTypeTitle: "Modifier le type d’échantillon de matière",
  editMetadataTitle: "Modifier les métadonnées",
  editObjectSubtypeTitle: "Modifier le sous-type d’objet",
  editOrganizationAliasesLabel: "Pseudonymes (séparés par une virgule)",
  editOrganizationTitle: "Modifier l’organisation",
  editPersonTitle: "Modifier la personne",
  editPreparationTypeTitle: "Modifier le type de préparation",
  editSelectedAttachmentMetadata:
    "Modifier les métadonnées de la pièce jointe sélectionnée",
  editSelectedButtonText: "Modifier les éléments sélectionnés",
  editStorageUnitTitle: "Modifier l’unité de stockage",
  editStorageUnitTypeTitle: "Modifier le type de stockage",
  editWorkflowTemplateTitle: "Modifier le modèle de flux de travail",
  elevationInMeters: "Élévation en mètres",
  enableDateRangeLabel: "Activer la plage de dates",
  endEventDateTime: "Date/heure de fin d’événement (AAAA-MM-JJTHH:MM:SS.MMM)",
  exifProperties: "Propriétés existantes",
  existingAttachments: "Pièces jointes existantes",
  feedbackButtonText: "Commentaires",
  field_acCaption: "Légende",
  field_acDerivedFrom: "Tiré de",
  field_acDigitizationDate: "Date de création de la version originale",
  field_acDigitizationDate_tooltip:
    "Date et heure auxquelles l’objet numérique décrit par la métadonnée a été créé. Dans le cas d’une image, cela représente le moment où l’image a été prise.",
  field_acHashFunction: "Fonction de hachage",
  field_acHashValue: "Hachage",
  field_acMetadataCreator: "Créateur de métadonnées ",
  "field_acMetadataCreator.displayName": "Téléchargé par",
  "field_acMetadataCreator.displayName_tooltip":
    "Agent qui a créé l’enregistrement de métadonnées.",
  field_acSubtype: "Sous-type d’objet",
  field_acTags: "Balises",
  field_acceptedValues: "Valeurs acceptées",
  field_aliases: "Pseudonymes",
  field_attributesTemplate: "Modèle des attributs définis",
  field_collectingEvent_endDateTimeError:
    "Le format de date/heure de l’événement final doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_collectingEvent_startDateTimeError:
    "Le format de la date de début de l’événement doit être un sous-ensemble de : AAAA-MM-JJTHH:MM:SS.MMM, si la date est présente, 'T’ est obligatoire",
  field_collectorGroup_agentsError:
    "Au moins un agent doit être précisé pour le groupe",
  field_collectors: "Collecteurs",
  field_contact: "Contact",
  field_createdBy: "Créé par",
  field_createdDate: "Date de création",
  field_createdOn: "Créé le",
  "field_dcCreator.displayName": "Créateur du document",
  field_dcFormat: "Format du média",
  field_dcRights: "Droit d’auteur",
  field_dcType: "Type d’objet stocké",
  field_description: "Description",
  "field_description.en": "Description anglaise",
  "field_description.fr": "Description française",
  field_displayName: "Visualiser le nom",
  field_dwcCountry: "Pays",
  field_dwcCountryCode: "Code du pays",
  field_dwcDegreeOfEstablishment: "Degré d'établissement",
  field_dwcDegreeOfEstablishment_tooltip:
    "La mesure dans laquelle un organisme survit, se reproduit et étend son aire de répartition à un endroit et à un moment donnés.",
  field_dwcGeodeticDatum: "Référence géodésique",
  field_dwcGeodeticDatum_tooltip:
    "La référence géodésique sur laquelle les coordonnées géographiques decimalLatitude et decimalLongitude sont fondées. La pratique exemplaire recommandée est ",
  field_dwcGeoreferenceProtocol: "Protocole de géoréférencement",
  field_dwcGeoreferenceProtocol_tooltip:
    "Une description ou une référence aux méthodes utilisées pour déterminer l’empreinte spatiale, les coordonnées et les incertitudes.",
  field_dwcGeoreferenceRemarks: "Remarques sur la géoréférence",
  field_dwcGeoreferenceRemarks_tooltip:
    "Notes ou commentaires sur la détermination de la description spatiale, expliquant les hypothèses faites en plus ou en opposition à celles formalisées dans la méthode visée dans georeferenceProtocol.",
  field_dwcGeoreferenceSources: "Sources de géoréférencement",
  field_dwcGeoreferenceSources_tooltip:
    "Une liste de cartes, de répertoires géographiques ou d’autres ressources utilisées pour géoréférencer le lieu, décrite de manière suffisamment précise pour permettre à quiconque d’utiliser les mêmes ressources à l’avenir.",
  field_dwcGeoreferenceVerificationStatus: "Géoréférencement impossible",
  field_dwcMunicipality: "Municipalité",
  field_dwcOtherCatalogNumbers: "Autres numéros de catalogues",
  field_dwcOtherRecordNumbers: "Numéros de collecte",
  "field_materialSampleType.name": "Type d’échantillon de matière",
  "field_materialSampleType.uuid": "Types d’échantillons de matière",
  field_dwcOtherRecordNumbers_tooltip:
    "Autres numéros ou identifiants associés à l’événement de collecte qui permettent de le distinguer. N’incluez PAS les identifiants basés sur les spécimens, tels que les numéros d’accession.",
  field_dwcRecordNumber: "Numéro du collecteur",
  field_dwcRecordedBy: "Collecteurs Verbatim",
  field_dwcStateProvince: "État/province",
  field_dwcVerbatimCoordinateSystem: "Système de coordonnées Verbatim",
  field_dwcVerbatimCoordinateSystem_tooltip:
    "Le format des coordonnées pour les verbatimLatitude et verbatimLongitude ou les verbatimCoordinates de l’emplacement. Exemples : degrés décimaux, degrés minutes décimales, degrés minutes secondes, UTM",
  field_dwcVerbatimCoordinates: "Coordonnées verbatim",
  field_dwcVerbatimCoordinates_tooltip:
    "Les coordonnées spatiales originales verbatim de l’emplacement. L’ellipsoïde de coordonnées, le datum géodésique ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemples : 41 05 54S 121 05 34W, 17T 630000 4833400",
  field_dwcVerbatimDepth: "Profondeur Verbatim",
  field_dwcVerbatimDepth_tooltip:
    "La description originale de la profondeur sous la surface locale. Exemple : 100-200 m",
  field_dwcVerbatimElevation: "Verbatim Élévation",
  field_dwcVerbatimElevation_tooltip:
    "La description originale de l’élévation (altitude, au-dessus du niveau de la mer) de l’emplacement. Exemple : 100-200 m",
  field_dwcVerbatimLatitude: "Verbatim Latitude",
  field_dwcVerbatimLatitude_tooltip:
    "La latitude originale verbatim de l’emplacement. L’ellipsoïde de coordonnées, le geodeticDatum ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemple : 41 05 54.03S",
  field_dwcVerbatimLocality: "Verbatim Localité",
  field_dwcVerbatimLongitude: "Verbatim Longitude",
  field_dwcVerbatimLongitude_tooltip:
    "La longitude originale verbatim de l’emplacement. L’ellipsoïde de coordonnées, le geodeticDatum ou le système de référence spatiale (SRS) complet pour ces coordonnées doivent être stockés dans verbatimSRS et le système de coordonnées doit être stocké dans verbatimCoordinateSystem. Exemple : 121 d 10? 34? W",
  field_dwcVerbatimSRS: "Verbatim SRS",
  field_dwcVerbatimSRS_tooltip:
    "L’ellipsoïde, le datum géodésique ou le système de référence spatiale (SRS) sur lesquels sont basées les coordonnées données dans verbatimLatitude et verbatimLongitude, ou verbatimCoordinates. La meilleure pratique recommandée est d’utiliser le code EPSG du SRS, s’il est connu. Exemples : EPSG:4326, WGS84, NAD27",
  field_editableBuiltInAttributes: "Attributs intégrés",
  field_editableManagedAttributes: "Attributs gérés",
  field_endEventDateTime: "Date et heure de l'événement final",
  field_email: "Courriel",
  field_familyNames: "Noms de famille",
  field_familyNames_tooltip:
    "Nom(s) de famille, y compris les noms de famille composés",
  field_givenNames: "Prénoms",
  field_givenNames_tooltip: "Prénom et tous les seconds prénoms",
  field_isInseperable: "Garder les contenus ensemble",
  field_isInseperable_tooltip: "Les contenus sont inséparables",
  field_license: "Licence",
  field_managedAttributeComponent: "Type de composant des données cibles",
  field_managedAttributeCreatedBy: "Créé par",
  field_managedAttributeCreatedOn: "Créé le",
  field_managedAttributeMandatoryFieldsError:
    "Le nom et le type sont des champs obligatoires",
  field_managedAttributeName: "Nom de l'attribut",
  field_managedAttributeType_integer_label: "Par ordre numérique",
  field_managedAttributeType_picklist_label: "Liste de sélection",
  field_managedAttributeType_text_label: "Texte",
  field_materialSampleName: "Identifiant Échantillons de matériaux",
  field_materialSample_identifierType_catalogueNumber_label:
    "Numéro de catalogue",
  field_materialSample_identifierType_materialSampleId_label:
    "No ID d’échantillon de matière",
  field_notPubliclyReleasableReason:
    "Raison pour laquelle il n’est pas possible de le divulguer publiquement",
  field_organizationMandatoryFieldsError:
    "Le nom d’au moins une organisation est requis",
  field_orientation: "Orientation",
  field_orientation_tooltip:
    "Détermine la façon dont une image doit être affichée en fonction de sa valeur d’orientation, qui doit être un nombre de 1 à 8.",
  field_orientation_tooltipAlt:
    "Diagramme de toutes les valeurs d’orientation potentielles",
  field_originalFilename: "Nom du fichier original",
  field_parentStorageUnit: "Emplacement",
  field_preparationType: "Type de préparation",
  field_publiclyReleasable: "Accessible au public",
  field_publiclyReleasable_tooltip:
    "Indique si l’objet peut être diffusé publiquement sur une page Web ou sur des portails de données ouvertes.",
  field_remarks: "Remarques",
  field_startEventDateTime: "Date et heure de l'événement initial",
  field_transcriberRemarks: "Notes du transcripteur",
  field_type: "Catégorie",
  field_typeStatus: "Type de statut",
  field_typeStatusEvidence: "Type de statut - Preuve",
  field_verbatimDate: "Verbatim - Date",
  field_verbatimDeterminer: "Déterminant verbatim",
  field_verbatimEventDateTime: "Date et heure de l'événement textuel",
  field_verbatimRemarks: "Verbatim - Remarques",
  field_verbatimScientificName: "Verbatim - Nom scientifique",
  field_webpage: "Page Web",
  field_xmpMetadataDate: "Date d’application des métadonnées",
  field_xmpMetadataDate_tooltip:
    "Date et heure de la dernière mise à jour du dossier.",
  field_xmpRightsWebStatement: "Licence",
  fileTooBig: "Fichier trop volumineux",
  filterAttribute: "Attribut filtre",
  filterByGroup: "Filtrer par groupe",
  filterPredicate: "Prédicat filtre",
  filterValue: "Valeur filtre",
  footerContactInfo: "Coordonnées du contact ",
  footerPrivacy: "Protection de la vie privée",
  footerTermsAndConditions: "Modalités ",
  forTestingPurposesOnlyMessage:
    "Aux fins d’analyse seulement. Seules des données non classifiées peuvent être téléversées. Toute donnée téléversée peut être supprimée, en tout temps. ",
  formNavigation: "Navigation dans les formulaires",
  generateBatch: "Produire un lot",
  generateSeries: "Produire une série",
  geoReferencing: "Géoréférencement",
  geoReferencingLegend: "Géoréférencement",
  geographyLegend: "Géographie (Lieux)",
  geographySearchBoxTooltip:
    'Recherche par nom de lieu (par exemple "Ottawa" ou coordonnées WGS84 [par exemple "40.123, -74.123"])',
  georeferencedByLabel: "Géoréférencé par (agent)",
  georeferencedDateLabel: "Date géoréférencée",
  goToThePreviousStep: "Aller à la prochaine étape",
  governmentOfCanada: "Gouvernement du Canada",
  governmentOfCanadaSymbol: "Symbole du gouvernement du Canada",
  group: "Groupe",
  groupMustBeSelected: "Un groupe doit être sélectionné ",
  identifierLegend: "Identifiants",
  identifierType: "Type d’identifiant",
  identifierURI: "Identifiant URI",
  identifiers: "Identifiants",
  includeAll: "Inclure tous",
  institution: "Établissement",
  institutionListTitle: "Établissements",
  languageDescriptionEnglish: "Anglais",
  languageDescriptionFrench: "Français",
  languageOfPage: "fra",
  largeImg: "Grande image",
  latLongAutoSetterButton: "Convertir en décimal Lat/Long",
  latitudeValidationError:
    "Latitude invalide : {latitude}, \nLa plage de latitude valide est comprise entre -90 et 90 pour les degrés, et entre 0 et 60 pour les minutes et les secondes",
  literalGeoreferencedByLabel: "Géoréférencé par",
  locationLabel: "Emplacement",
  longitudeValidationError:
    "Longitude invalide : {longtitude}, \nLa longitude valide est comprise entre -180 et 180 pour les degrés, et entre 0 et 60 pour les minutes et les secondes",
  makePrimary: "Marque principale",
  managedAttributeEditTitle: "Modifier l’attribut géré",
  managedAttributeListTitle: "Attributs gérés",
  managedAttributeValueLabel: "Valeur",
  materialSample: "Échantillon de matériaux",
  materialSampleAttachments: "Pièces jointes de l’échantillon de matériaux",
  materialSampleInfo: "Info sur l'échantillon de matière",
  materialSampleManagedAttributes:
    "Attributs gérés de l’échantillon de matière",
  materialSampleName: "Nom de l’échantillon de matière",
  materialSampleListTitle: "Échantillons de matériaux",
  materialSampleTypeListTitle: "Types d’échantillon de matière",
  materialSampleViewTitle: "Échantillon de matériaux",
  metadataAttributesTemplateSave: "Enregistrer ce modèle d’attributs",
  metadataBucketNameLabel: "Nom de la catégorie",
  metadataBuiltInAttributesLabel: "Attributs intégrés",
  metadataBulkEditTagsLabel: "Balises (séparées par une virgule)",
  metadataBulkEditTitle: "Modifier les métadonnées",
  metadataDcFormatLabel: "Format de l’élément dc",
  metadataFileExtensionLabel: "Extension du fichier",
  metadataFileIdentifierLabel: "Identificateur du fichier",
  metadataFileStorageDetailsLabel: "Stockage du fichier",
  metadataFilenameLabel: "Nom du fichier ",
  metadataFirstDigitalVersionCreatedDateLabel:
    "Date de création de la première version numérique",
  metadataFormTitle: "Métadonnées",
  metadataHashFunctionLabel: "Fonction de hachage",
  metadataHashValueLabel: "Valeur de hachage",
  metadataLastMetadataModificationTimeLabel:
    "Date de la dernière modification des métadonnées",
  metadataListGalleryLayout: "Galerie",
  metadataListTableLayout: "Tableau",
  metadataManagedAttributesLabel: "Attributs gérés",
  metadataMediaDetailsLabel: "Média",
  metadataObjectTypeLabel: "Type d’objet stocké",
  metadataPageLink: "Page des détails",
  metadataRightsDetailsLabel: "Droits",
  metadataTagsLabel: "Balises",
  metadataUploadDetailsLabel: "Télécharger les détails",
  metersField_tooltip:
    "Utilisez les unités suivantes pour la conversion automatique : pi, po, pi po, vg, mm, cm, km",
  moveAllContent: "Déplacer tout le contenu",
  multiple: "Multiple",
  noFileToDisplay: "Aucun fichier à afficher",
  noGroups: "Aucun groupe",
  noManagedAttributeValues: "Aucune valeur d’attribut géré.",
  noNestedStorageUnits: "Aucune untié de stockage imbriquée",
  noneTopLevel: "Aucun (niveau supérieur)",
  noResultsFound: "Aucun résultat trouvé.",
  notEditableWhenThereAreChildStorageUnits:
    "Non modifiable lorsqu’il y a des unités de stockage enfant ",
  notPubliclyReleasable: "Diffusion publique interdite",
  objectListTitle: "Objets stockés",
  objectStoreDataUnavailable:
    "Les données du stockage de l’objet ne sont pas disponibles",
  objectStoreDetailsTitle: "Détails sur le stockage de l’objet",
  objectStoreTitle: "Dépôt d’objet",
  objectSubtypeListTitle: "Sous-types d’objet",
  objectSubtypeTitle: "Sous-type d’objet",
  openGeographySearchButtonLabel: "Recherche sur Open Street Maps",
  organismState: "État de l'organisme",
  organizationEnglishNameLabel: "Nom anglais ",
  organizationFrenchNameLabel: "Nom français ",
  organizationListTitle: "Organisations",
  originalFile: "Fichier original",
  originalMaterialSampleLabel: "Échantillon de matière original",
  parentCollectionLabel: "Collection mère",
  parentMaterialSample: "Échantillon d'origine",
  parentSampleNotFoundLabel: "Échantillon parent non trouvé",
  personListTitle: "Personnes",
  preparation: "Préparation",
  preparationData: "Données de préparation",
  preparationTypeListTitle: "Type de préparation",
  preparationTypeNameLabel: "Nom du type de préparation",
  preparations: "Préparations",
  preparedBy: "Préparé par",
  previewAndCustomizeLabel: "Prévisualiser et personnaliser",
  primary: "Principal",
  primaryButton_tooltip:
    "Faites de cette affirmation le point de données principal lors de l’exportation. Une seule hypothèse peut servir d’hypothèse principale",
  proceedToCreateMetadata: "Passez à la création de métadonnées",
  removeThisElement: "Supprimer cette {typeName}",
  removeComponentData: "Suppression des données de {component}",
  removeGroup: "Supprimer un groupe",
  removeFromParentStorageUnit: "Retirer de l’unité de stockage parent",
  removeIdentifier: "Supprimer l’identifiant",
  removeManagedAttributeValue:
    "Retirer la valeur de l’attribut géré : {attributeNames}",
  removeThisPlaceLabel: " Supprimer ce lieu",
  resetMetadataEditorAttributesButtonText:
    "Réinitialiser à la disposition initiale des attributs",
  resetNamesToDefaultValues: "Réinitialiser les noms aux valeurs par défaut",
  revisionsButtonText: "Révisions",
  revisionsByUserPageTitle: "Révisions par l’utilisateur",
  revisionsListTitle: "Révisions pour {name}",
  role: "Role",
  roles: "Rôles",
  rolesPerGroup: "Rôles par groupe",
  runWorkflow: "Exécuter le flux de travail",
  saveAndGoToViewPageButton: "Enregistrer et passer à la page Visualiser",
  saveAndCreateNewMaterialSampleButton:
    "Enregistrer et créer un nouvel échantillon de matière",
  saveGeoReferenceAssertion: "Sauvegarder l’assertion de géoréférence",
  scheduledActions: "Actions prévues",
  searchButton: "Recherche",
  searchPreviousTags: "Consulter les précédentes étiquettes",
  searchResults: "Résultats de la recherche ({resultSize})",
  searchStorage: "Recherche dans le stockage",
  selectCollectorGroupLabel:
    "Sélectionnez un groupe de collecteurs pour prépeupler le champ «Collecteurs»",
  selectGroup: "Sélectionnez Groupe",
  selectOrType: "Sélectionner ou taper",
  set: "Ensemble",
  setAll: "Tous les ensembles",
  showing: "Affiché",
  skipToMainContent: "Passer au contenu principal",
  skipToAboutThisApplication: "Passer à « À propos de ce site »",
  skipToBasicHtmlVersion: "Passer à la version HTML simplifiée",
  showingFilteredStorageUnits: "Afficher les unités de stockage filtrées",
  showingTopLevelStorageUnits:
    "Afficher les unités de stockage de niveau supérieur",
  source: "Source",
  specifyParentContainer: "Veuillez sélectionner le contenant parent",
  splitButton: "Diviser",
  splitSampleActionMetadataLegend: "Métadonnées sur les mesures",
  splitSampleChildSamplesToCreateLabel:
    "Échantillons de matière enfant à créer",
  splitSampleConfigLegend: "Configurer une action : Division ",
  splitSampleDescription:
    "Diviser un échantillon parent en un ou plusieurs échantillons enfant",
  splitSampleInstructions:
    "Le nombre maximum d’échantillons enfant à créer est de 30",
  splitSampleRemarksPlaceholder:
    "Décrivez ce que vous avez fait, ce qui a été modifié, ou ce qui s’est passé en a résulté (par exemple, la suppression d’une partie)",
  splitSampleTagOriginalAsDestroyed: "Identifier l’original comme « Détruit »",
  splitSubsampleTitle: "Division (sous-échantillon)",
  splitWorkflowRunTitle: "Exécuter la division du flux de travail ",
  startEventDateTime:
    "Date/heure de début de l’événement (AAAA-MM-JJTHH:MM:SS.MMM)",
  startNewRunConfigLabel: "Lancer une nouvelle éxécution",
  stateProvinceLabel: "État/province",
  status: "Statut",
  storage: "Stockage",
  storageUnitListTitle: "Unités de stockage",
  storageUnitType: "Type d’unité de stockage",
  storageUnitTypeListTitle: "Types d’unités de stockage",
  storagesCreatedByMe: "Stockages créés par moi",
  suffixOptional: "Suffixe (facultatif)",
  switchToActionType: 'Passer à "{actionType}".',
  tags: "Étiquettes",
  templateNameMandatoryErrorMsg:
    "Veuillez entrer un nom de modèle de flux de travaux.",
  thisWillLoseAllDataEnteredInThisStep:
    "Cette opération entraîne la perte de toutes les données saisies au cours de cette étape.",
  thisWillRemoveYourTemplate:
    "Cette opération supprimera les champs du modèle sélectionnés et les valeurs par défaut.",
  thumbnail: "Vignette",
  thumbnailNotAvailableText: "Aucune vignette disponible",
  to: "À",
  tooltipDefaultLinkMessage: "Cliquez ici pour en savoir plus.",
  toponymyLegend: "Lieu géographique actuel",
  typeAnythingOrPickAScientificName:
    "Taper quelque chose ou choisir un nom scientifique",
  typeNewTagOrSearchPreviousTags:
    "Entrer la nouvelle étiquette ou consulter les précédentes étiquettes",
  typeSpecimen: "Taper spécimen",
  uploadButtonText: "Téléverser",
  uploadFilesMaxSize: "La taille maximale des fichiers est de {maxSize}",
  uploadFormInstructions:
    "Glisser-déposer les fichiers ici ou cliquer pour ouvrir la fenêtre de dialogue. Seuls les fichiers graphiques, audio, vidéo, .pdf, .doc et .docx sont acceptés.",
  uploadNewAttachments: "Téléverser de nouvelles pièces jointes",
  uploadPageTitle: "Téléverser les fichiers",
  useCollectorGroupLabel: "Utiliser le groupe de collecteurs",
  userListTitle: "Utilisateurs",
  userMustBelongToGroup: "L’utilisateur doit appartenir à un groupe",
  userViewTitle: "Utilisateur",
  verbatimDeterminationLegend: "Détermination verbatim",
  verbatimEventDateTime: "Date et heure de l’événement Verbatim",
  verbatimLabelLegend: "Étiquette Verbatim",
  verbatimLatLong: "Verbatim Lat/Long",
  viewDetailButtonLabel: "Afficher détails",
  viewOnMap: "Visualiser sur la carte",
  viewPreviewButtonText: "Prévisualiser",
  warningMessage: "Messages d’avertissement",
  whoAmITitle: "Qui suis-je?",
  workbookGroupUploadTitle: "Téléverser le tableur",
  workbookTitle: "Tableurs",
  workbookUploadInstructions:
    "Faites glisser et déposez une feuille de calcul ici ou cliquez pour ouvrir la boîte de dialogue de navigation.",
  workbookUploadFailure:
    "Un problème est survenu lors de la tentative de lecture de la feuille de calcul téléchargée.",
  workflowCompleteTitle: "Flux de travail achevé",
  workflowTemplateListTitle: "Modèles de flux de travail",
  workflowTemplateTitle: "Modèle de flux des travaux",
  year: "Année",
  yearMonth: "Année-Mois",
  yearMonthDay: "Année-Mois-Jour",
  yearMonthDayTime: "Année-Mois-Jour-Heure"
};
