import { DINAUI_MESSAGES_ENGLISH } from "./dina-ui-en";

export const DINAUI_MESSAGES_FRENCH: Partial<typeof DINAUI_MESSAGES_ENGLISH> = {
  appTitle: "DINA",
  governmentOfCanada: "Gouvernement du Canada",
  addFilesButton: "Ajouter des fichiers",
  addManagedAttributeButtonText: "Ajouter un nouvel attribut géré",
  addObjectSubtypeTitle: "Ajouter un nouveau sous-type d'objet",
  addOrganizationTitle: "Ajouter une nouvelle organisation",
  addPersonTitle: "Ajouter une personne",
  addPersonButtonText: "Ajouter une personne",
  addPersonPopupTooltip: "Ajouter une personne sans quitter la page",
  agentsSectionTitle: "Agents",
  attributeLabel: "Attribut",
  cancelButtonText: "Annuler",
  changedProperties: "Modifications",
  closePreviewButtonText: "Fermer la prévisualisation",
  deleteButtonText: "Supprimer",
  deleteSelectedButtonText: "Supprimer les éléments sélectionnés",
  editObjectSubtypeTitle: "Modifier le sous-type d'objet",
  editOrganizationTitle: "Modifier l'organisation",
  editOrganizationAliasesLabel: "Pseudonymes (séparés par une virgule)",
  editPersonTitle: "Modifier la personne",
  editSelectedButtonText: "Modifier les éléments sélectionnés",
  feedbackButtonText: "Commentaires",
  field_acCaption: "Légende",
  field_acDerivedFrom: "Tiré de",
  field_acDigitizationDate: "Date de création de la version originale",
  field_acHashFunction: "Fonction de hachage",
  field_acHashValue: "Hachage",
  "field_acMetadataCreator.displayName": "Téléchargé par",
  field_acSubType: "Sous-type d'objet",
  field_acTags: "Balises",
  "field_dcCreator.displayName": "Créateur du document",
  field_dcFormat: "Format du média",
  field_dcRights: "Déclaration sur les droits",
  field_dcType: "Type d'objet stocké",
  field_editableBuiltInAttributes: "Attributs intégrés",
  field_editableManagedAttributes: "Attributs gérés",
  field_license: "Licence",
  field_managedAttributeAcceptedValue: "Valeur acceptée",
  field_managedAttributeCreatedOn: "Créé le",
  field_managedAttributeCreatedBy: "Créé par",
  field_managedAttributeDescEn: "Description anglaise",
  field_managedAttributeDescFr: "Description française",
  field_managedAttributeMandatoryFieldsError:
    "Le nom et le type sont des champs obligatoires",
  field_managedAttributeName: "Nom de l'attribut",
  field_managedAttributeType: "Type",
  field_originalFilename: "Nom du fichier original",
  field_xmpMetadataDate: "Date d'application des métadonnées",
  field_xmpRightsWebStatement: "Déclaration sur les droits de réutilisation",
  groupMustBeSelected: "Un groupe doit être sélectionné ",
  managedAttributeEditTitle: "Modifier l'attribut géré",
  managedAttributeListTitle: "Attributs gérés",
  managedAttributeValueLabel: "Valeur",
  metadataBucketNameLabel: "Nom de la catégorie",
  metadataBuiltInAttributesLabel: "Attributs intégrés",
  metadataBulkEditTagsLabel: "Balises (séparées par une virgule)",
  metadataBulkEditTitle: "Modifier les métadonnées",
  metadataDcFormatLabel: "Format de l'élément dc",
  metadataDetailsPageLink: "Page des détails",
  metadataFileExtensionLabel: "Extension du fichier",
  metadataFileIdentifierLabel: "Identificateur du fichier",
  metadataFileStorageDetailsLabel: "Stockage du fichier",
  metadataFilenameLabel: "Nom du fichier ",
  metadataFirstDigitalVersionCreatedDateLabel:
    "Date de création de la première version numérique",
  metadataFormTitle: "Métadonnées",
  metadataHashFunctionLabel: "Fonction de hachage",
  metadataHashValueLabel: "Valeur de hachage",
  metadataLastMetadataModificationTimeLabel:
    "Date de la dernière modification des métadonnées",
  metadataListGalleryLayout: "Galerie",
  metadataListTableLayout: "Tableau",
  metadataManagedAttributesLabel: "Attributs gérés",
  metadataMediaDetailsLabel: "Média",
  metadataObjectTypeLabel: "Type d'objet stocké",
  metadataPageLink: "Page des détails",
  metadataRevisionsListTitle: "Révisions pour {name}",
  metadataRightsDetailsLabel: "Droits",
  metadataTagsLabel: "Balises",
  metadataUploadDetailsLabel: "Télécharger les détails",
  noFileToDisplay: "Aucun fichier à afficher",
  objectListTitle: "Objets stockés",
  objectStoreDetailsTitle: "Détails sur le stockage de l'objet",
  objectStoreTitle: "Stockage de l'objet",
  objectSubtypeListTitle: "Sous-types d'objet",
  objectSubtypeTitle: "Sous-type d'objet",
  organizationListTitle: "Organisations",
  organizationViewTitle: "Afficher l'organisation",
  personListTitle: "Personnes",
  personViewTitle: "Afficher la personne",
  revisionsButtonText: "Révisions",
  revisionsByUserPageTitle: "Révisions par l'utilisateur",
  searchButton: "Recherche",
  thumbnailNotAvailableText: "Aucune vignette disponible",
  uploadButtonText: "Télécharger",
  uploadFormInstructions:
    "Glisser-déposer les fichiers ici ou cliquer pour ouvrir la fenêtre de dialogue. Seuls les fichiers graphiques, audio, vidéo, .pdf, .doc et .docx sont acceptés.",
  uploadPageTitle: "Télécharger les fichiers",
  userMustBelongToGroup: "L'utilisateur doit appartenir à un groupe",
  valueLabel: "Valeur",
  viewPreviewButtonText: "Prévisualiser"
};
