import { DINAUI_MESSAGES_ENGLISH } from "./dina-ui-en";

export const DINAUI_MESSAGES_GERMAN: Partial<typeof DINAUI_MESSAGES_ENGLISH> = {
  LETTER: "Buchstabe",
  NUMERICAL: "Numerisch",
  actionType: "Aktionstyp",
  actions: "Aktionen",
  addAnother: "weiteren {typeName} hinzufügen",
  addAnotherIdentifier: "weiteren Identifier hinzufügen",
  addAssemblageTitle: "Teilsammlung hinzufügen",
  addAssertion: "GeoReferenz hinzufügen",
  addAttachments: "Anhang hinzufügen",
  addAttributesTemplateTitle: "Template eines neuen Attributs",
  addCataloguedObjectTitle: "Katalogisiertes Objekt hinzufügen",
  addCollectingEventTitle: "Sammlungsevent hinzufügen",
  addCollectionMethodTitle: "Sammlungsmethode hinzufügen",
  addCollectionTitle: "Sammlung hinzufügen",
  addCollectorGroupTitle: "Sammlergruppe hinzufügen",
  addCustomPlaceName: "Hinzufügen",
  addDetermination: "Bestimmung hinzufügen",
  addExistingStorageUnitAsChild: "existierende Lagerungseinheit hinzufügen",
  addExpeditionTitle: "Expedition hinzufügen",
  addExternalResourceTitle: "Neue externe Ressource hinzufügen",
  addFilesButton: "Datei hinzufügen",
  addGroup: "Gruppe hinzufügen",
  addIdentifier: "Bezeichner hinzufügen",
  addInstitutionTitle: "Institution hinzufügen",
  addManagedAttribute: "Regelattribut hinzufügen",
  addManagedAttributeButtonText: "neues Regelattribut hinzufügen",
  addManagedAttributeTitle: "neues Regelattribut hinzufügen",
  addManagedAttributesViewTitle: "Formularvorlage erstellen",
  addMaterialSampleTitle: "Materialprobe hinzufügen",
  addMaterialSampleTypeTitle: "Typ der Materialprobe hinzufügen",
  addMetadataTitle: "Metadaten hinzufügen",
  addNewChildStorageUnit: "Neue Lagerungseinheit (Nachfolger) hinzufügen",
  addNewElement: "Neues {typeName} hinzufügen",
  addNewGroup: "Neue Gruppe hinzufügen",
  addNewPerson: "Neue Person hinzufügen",
  addObjectSubtypeTitle: "Neuen Objektsubtyp hinzufügen",
  addOrganizationTitle: "neue Organisation hinzufügen",
  addPersonButtonText: "Person hinzufügen",
  addPersonPopupTooltip: "Person hinzufügen, ohne die Seite zu verlassen",
  addPersonTitle: "Person hinzufügen",
  addPreparationMethodTitle: "Aufbereitungsmethode hinzufügen",
  addPreparationTypeTitle: "Aufbereitungstyp hinzufügen",
  addProjectTitle: "Projekt hinzufügen",
  addRule: "Regel hinzufügen",
  addRuleSet: "Regelsatz hinzufügen",
  addScheduledAction: "Terminierte Aktion hinzufügen",
  addStorageUnitTitle: "Lagerungseinheit hinzufügen",
  addStorageUnitTypeTitle: "Typ einer Lagerungseinheit hinzufügen",
  addTransactionTitle: "Transaktion anlegen",
  additionalRemarks: "Zusätzliche Anmerkungen",
  agent: "Agent",
  agentDetails: "Details zum Agenten",
  agentName: "Agentenname",
  agentRemarks: "Agentenanmerkungen",
  agentRole: "Agentenrolle",
  agentsSectionTitle: "Agenten",
  allowDuplicate: "Dublikate zulassen",
  allowExisting: "Existierende zulassen",
  allowNew: "Neue zulassen",
  andNMore: "... und {count} weitere",
  appTitle: "DINA",
  appTitleInstanceMode: "DINA ({instanceMode})",
  assemblage: "Teilsammlung",
  assemblageAttachments: "Teilsammlung-Anhänge",
  assemblageListTitle: "Teilsammlungen",
  assemblageManagedAttributes: "Regelattribute der Teilsammlungen",
  assemblage_tooltip:
    "Mechanismus zur Gruppierung von Materialproben nach einem organisatorischen Thema.",
  assemblages: "Teilsammlungen",
  assignContentsToNewStorage: "Inhalt einer neuen Lagerungseinheit zuordnen",
  assignedStorage: "Zugeordnete Lagerungseinheit",
  assignedTo: "Zugewiesen an",
  associatedAgent: "Verknüpfter Agent",
  associatedMaterialSample: "Verknüpftes Materialprobe",
  association: "Verknüpfung",
  associationType: "Verknüpfungstyp",
  associationsLegend: "Verknüpfungen",
  attachExisting: "Bestehendes anhängen",
  attachExistingObjects: "Bestehendes Objekt anhängen",
  attachSelected: "Ausgewähltes anhängen",
  attachedMaterialSamples: "Verknüpfte Materialproben",
  attachments: "Anhang",
  attributeLabel: "Attribut",
  auditSnapshot: "Audit-Schnappschuss",
  backToParentUnit: "Zurück zur Vorfahren",
  baseNameLabel: "Basisname",
  batchModeInfo: "Batch-Modus: Alle Materialprobe müssen die gleiche ID haben.",
  browseContents: "Inhalt durchsuchen",
  browseStorageTree: "Lagerungsbaum durchsuchen",
  bulkCreate: "mehrere Neue anlegen",
  bulkEditNotPubliclyReleasableTooltip:
    'Der aktuelle Status der ausgewählten Elemente ist standardmäßig auf "{keepCurrentValues}" gesetzt. Ãnderungen hier werden auf alle ausgewählten Elemente angewendet.',
  bulkEditResourceLinkerWarningMulti:
    "Diese {fieldName} wird mit allen {targetType} verknüpft",
  bulkEditResourceLinkerWarningSingle:
    "Dieses {fieldName} wird mit allen {targetType} verknüpft",
  bulkEditResourceLinkerWarning_Attachments_MaterialSample_Multi:
    "Diese Anhänge werden mit allen Materialproben verknüpft.",
  bulkEditResourceLinkerWarning_Attachments_MaterialSample_Single:
    "Dieser Anhang wird mit allen Materialproben verknüpft.",
  bulkEditResourceLinkerWarning_Organisms_MaterialSample_Multi:
    "Diese Organismen werden mit allen Materialproben verknüpft.",
  bulkEditResourceLinkerWarning_Organisms_MaterialSample_Single:
    "Dieser Organismus wird mit allen Materialproben verknüpft.",
  bulkEditResourceSetWarningMulti:
    "Diese {fieldName} werden für allen {targetType} gesetzt.",
  bulkEditResourceSetWarning_Associations_MaterialSample_Multi:
    "Diese Verknüpfungen werden für alle Materialproben gesetzt.",
  bulkEditResourceSetWarning_Associations_MaterialSample_Single:
    "Diese Verknüpfung wird für alle Materialproben gesetzt.",
  bulkEditResourceSetWarning_ScheduledActions_MaterialSample_Multi:
    "Diese geplanten Aktionen werden für alle Materialproben gesetzt.",
  bulkEditResourceSetWarning_ScheduledActions_MaterialSample_Single:
    "Diese geplante Aktion wird für alle Materialproben gesetzt.",
  bulkOperationCompleteTitle: "Sammeloperation abgeschlossen",
  bulkUploadDetectedDescription:
    "Sie haben {count} Dateien hochgeladen. Die Tabelle muss diese Dateien mit passenden âOriginal Filenameâ-Werten enthalten.",
  cancelButtonText: "Abbrechen",
  cataloguedObjectListTitle: "Katalogisierte Objekte",
  cfiaPPCLevel: "CFIA PPC Level",
  changedProperties: "Änderungen",
  childCultureStrains: "Kulturstämme",
  childMaterialSamples: "Materialprobe Nachfahre",
  childrenStorageUnits: "Lagerungseinheit für Kindelemente",
  closePreviewButtonText: "Vorschau schließen",
  colSearchBoxTooltip: "Catalog of Life durchsuchen",
  colSearchLabel: "Namenssuche",
  collectingAgentsLegend: "Sammlungsagent",
  collectingDateLegend: "Sammlungsdatum",
  collectingEvent: "Sammlungsevent",
  collectingEventAttachments: "Anhänge zum Sammlungsevent",
  collectingEventDetails: "Details zum Sammlungsevent",
  collectingEventEditAlertMessage:
    "Dieses Sammlungsevent ist derzeit mit {count} Materialproben verknüpft. Stellen Sie sicher",
  collectingEventEditAlertTitle: "Sammlungsevent aktualisieren?",
  collectingEventEditErrorMessage:
    "Dieses Sammlungsevent ist derzeit mit {count} Materialproben verknüpft. Bearbeitung ist nur auf der Detailseite des Sammlungsevents mÃ¶glich.",
  collectingEventEditErrorMessageSingle:
    "Dieses Sammlungsevent ist derzeit mit einer Materialprobe verknüpft. Bearbeitung ist nur auf der Detailseite des Sammlungsevents mÃ¶glich.",
  collectingEventFieldExtensions: "Sammlungsevent-Felderweiterungen",
  collectingEventGoToDetails: "Zur Detailseite des Sammlungsevents",
  collectingEventListTitle: "Sammlungsevent",
  collectingEventManagedAttributes: "Regelattribute des Sammlungsevents",
  collectingEventPartOfExpedition: "Sammlungsevent Teil von Expedition",
  collectingEventPermissionAlert: "Sie haben keine Berechtigung",
  collectingEventViewMaterialSamplesAttached:
    "Verknüpfte Materialproben anzeigen",
  collectingEvents: "Sammlungsevents",
  collectingLocationLegend: "Sammlungsort",
  collection: "Sammlung",
  collectionListTitle: "Sammlungen",
  collectionManagedAttributeListTitle: "Regelattribut des Sammlungsmoduls",
  collectionMethodListTitle: "Sammlungsmethode",
  collectionMethodNameLabel: "Name der Sammlungsmethode",
  collectionSectionTitle: "Sammlungen",
  collectionViewTitle: "Sammlung",
  collectorGroupAgentsLabel: "Agenten der Sammlergruppe",
  collectorGroupListTitle: "Sammlergruppe",
  collectorGroupNameLabel: "Name der Sammlergruppe",
  components: "Komponenten",
  configureDefaultValues: "Standardwert konfigurieren",
  configureFormTemplate: "Formularvorlage konfigurieren",
  contents: "Inhalt",
  continueWithBatchEntryForm: "Mit Masseneingabeformular fortfahren",
  continueWithWorkbook: "Mit Arbeitsmappe fortfahren",
  contributors: "Mitwirkende",
  controlledVocabularyTitle: "Kontrolliertes Vokabular",
  convertToDepthMinMax: "Umwandeln in Min/Max Tiefe",
  convertToElevationMinMax: "Umwandeln in Min/Max Richthöhe",
  coordinateUncertaintyInMeters: "Koordinatenungenauigkeit in Metern",
  copyFromParentLabel: "Kopie des Vorfahren",
  countryLabel: "Land",
  creatNewWorkflow: "Neu anlegen",
  create: "Erstellen",
  createAndAssign: "Anlegen und zuodnen",
  createFormTemplate: "Aus einer Vorlage anlegen",
  createMaterialSampleFormTemplate: "Materialprobe nach Vorlage anlegen",
  createNew: "Neu erstellen",
  createNewLabel: "Neu anlegen",
  createNewMaterialSamples: "Neues Materialprobe anlegen",
  createNewView: "Neuen View anlegen",
  createSampleWithFormTemplate: "Muster nach Formvorlage anlegen",
  createSavedSearch: "Gespeicherte Suche erstellen",
  createSplitWorkflow: "Aufteilung anlegen",
  createStorage: "Lagerort anlegen",
  croppedImg: "Zugeschnittenes Bild",
  customPlaceName: "Benutzerdefinierter Ortsname",
  customPlaceNamePlaceholder: "Eigenen Ortsnamen eingeben â¦",
  dataComponents: "Datenelement",
  dataEntryLabel: "Dateneingabe",
  dataSourceHasNoTaxonData:
    "Diese Datenquelle liefert nur Namen. Ãbergeordnete taxonomische Daten sind nicht verfügbar.",
  dataType: "Typ:",
  dataUnit: "Einheit:",
  dataValue: "Wert:",
  dataset: "Datensatz",
  datasetSearchTooltip:
    "Um einen anderen Datensatz aus dem Catalog of Life zu verwenden",
  decimalLatLong: "Dezimale Lat/Long",
  default: "Standard",
  defaultValues: "Standardwert",
  defaultValuesConfig: "Konfiguration der Standardwerte",
  defaultValuesConfigs: "Konfigurationen der Standardwerte",
  deleteAllStorageUnit: "Standort aus allen Lagereinheiten lÃ¶schen",
  deleteButtonText: "Löschen",
  deleteConfig: "Konfiguration löschen",
  deleteEmptyStorageWarning:
    "Speicher  {storageName} ist leer. Wollen Sie diesen Speichercontainer dauerhaft löschen?",
  deleteThisAttributesTemplate: "Diese Vorlage löschen",
  deleteThisView: "Diesen View löschen",
  deleted: "Gelöscht",
  deletedMetadata_tooltip: "ID der gelöschten Metaraten: {id}",
  depthInMeters: "Tiefe in Metern",
  derivativeDetailsLabel: "Derivative-Details",
  destroyOriginal: "Original als 'Vernichtet' kennzeichnen",
  detachCollectingEvent: "Sammlungsevent heraustrennen",
  detachSelectedButtonText: "Auswahl lösen",
  detailsPageLink: "Detailseite",
  determination: "Bestimmung",
  determinationManagedAttributes: "Regelattribut zur Bestimmung",
  determinationPrimary: "Bestimmung (Primär)",
  determinations: "Bestimmungen",
  determiningAgents: "Bestimmungsagent",
  determiningDate: "Bestimmungsdatum",
  dinaConfigurationSectionTitle: "Konfiguration",
  dinaHomeH1: "Dina Home",
  dinaManagementSectionTitle: "Management",
  disabledForChildMaterialSamples: "Für Nachfahren-Materialprobe",
  dragDropInstructionsHeader: "Um die Reihenfolge der Attribute zu ändern:",
  dragDropKeyboardInstructions:
    "Verwenden Sie die Registerkarte, um zum Attribut zu navigieren, und drücken Sie dann die Leertaste, um es auszuwählen. Verwenden Sie die Pfeiltasten, um das Element zu verschieben, und drücken Sie dann die Leertaste, um es zu platzieren.",
  dragDropMouseInstructions:
    "Ziehen Sie das Attribut per Drag & Drop an seine neue Position.",
  duplicate: "Duplikat",
  duplicateFilesFound: "doppelte Dateien gefunden",
  duplicatePrimaryIdFound: "doppete primäre ID gefunden",
  editAssemblageTitle: "Teilsammlung bearbeiten",
  editCataloguedObjectTitle: "Katalogisiertes Objekt bearbeiten",
  editCollectingEventTitle: "Sammlungsevent bearbeiten",
  editCollectionMethodTitle: "Sammlungsmethode bearbeiten",
  editCollectionTitle: "Sammler bearbeiten",
  editDerivativeMetadata: "Derivative-Metadaten bearbeiten",
  editDinaUserTitle: "Benutzer bearbeiten",
  editExpeditionTitle: "Expedition bearbeiten",
  editExternalResourceTitle: "Externe Ressource bearbeiten",
  editGroupTitle: "Gruppe bearbeiten",
  editInstitutionTitle: "Institution bearbeiten",
  editManagedAttributeTitle: "Regelattribut bearbeiten",
  editManagedAttributesViewTitle: "Formularvorlage bearbeite",
  editMaterialSampleFormTemplate: "Materialprobe-Formatvorlage bearbeiten",
  editMaterialSampleTitle: "Materialprobe bearbeiten",
  editMaterialSampleTypeTitle: "Typ der Materialprobe bearbeiten",
  editMetadataTitle: "Metadaten bearbeiten",
  editObjectSubtypeTitle: "Objektuntertyp bearbeiten",
  editOrganizationAliasesLabel: "Aliase (Komma-separiert)",
  editOrganizationTitle: "Organisation bearbeiten",
  editPersonTitle: "Person bearbeiten",
  editPreparationMethodTitle: "Vorbereitungsmethode bearbeiten",
  editPreparationTypeTitle: "Vorbereitungstyp bearbeiten",
  editProjectTitle: "Projekt bearbeiten",
  editSelectedAttachmentMetadata:
    "Metadaten des ausgewählten Anhangs bearbeiten",
  editStorageUnitTitle: "Lagereinheit bearbeiten",
  editStorageUnitTypeTitle: "Lagerungstyp bearbeiten",
  editThisFormTemplate: "Diese Formatvorlage bearbeiten",
  editTransactionTitle: "Transaktion bearbeiten",
  elevationInMeters: "Höhe in Metern",
  enableDateRangeLabel: "Datumsbereich aktivieren",
  enterFullscreen: "Vollbild aktivieren",
  exact: "Exakt",
  exifProperties: "EXIF-Eigenschaften",
  existingAttachments: "bestehende Anhänge",
  exitFullscreen: "Vollbild verlassen",
  expectedFiles: "Erwartete Dateien",
  expeditionListTitle: "Expeditionen",
  extensionListTitle: "Felderweiterung",
  externalResourceListTitle: "Externe Ressource",
  feedbackButtonText: "Feedback",
  feedbackContactUs:
    "Wenn Sie sicherheitsrelevante Themen ansprechen, kontaktieren Sie uns bitte per E-Mail.",
  feedbackExternal: "(extern, GitHub-Konto erforderlich)",
  feedbackLinkHeader: "GitHub-Issue hier einreichen:",
  feedbackLinkTitle: "GitHub-Issues",
  feedbackTitle: "Feedback wird in öffentlichen GitHub-Issues erfasst",
  feedbackWarningDescription:
    "Überprüfen Sie vor dem Posten Text und Anhänge, um sicherzustellen, dass keine sensiblen Informationen offengelegt werden. Private Daten, Zugangsdaten oder proprietäre Projektinformationen gelten als offengelegt, wenn sie in Issue-Beschreibungen, Kommentaren oder Anhängen vorkommen.",
  feedbackWarningTitle:
    "Warnung: GitHub-Issues sind öffentlich sichtbar, jeder kann Inhalte einsehen und durchsuchen.",
  fieldExtensions: "Felderweiterung",
  field__globalSearch: "Globale Suche",
  field__relationshipPresence: "Beziehungen",
  field__relationshipPresence_column: "Hat {relationshipName}",
  field_acCaption: "Legende",
  field_acDerivedFrom: "Abgeleitet von",
  field_acDigitizationDate: "Erstellungsdatum der Originalversion",
  field_acDigitizationDate_tooltip:
    "Datum und Uhrzeit der Erstellung des durch die Metadaten beschriebenen digitalen Objekts. Im Falle eines Bildes stellt dies dar, wann das Bild aufgenommen wurde.",
  field_acHashFunction: "Hash-Funktion",
  field_acHashValue: "Hash",
  field_acMetadataCreator: "Ersteller der Metadaten",
  "field_acMetadataCreator.displayName": "Hochgeladen durch",
  "field_acMetadataCreator.displayName_tooltip":
    "Agent, der den Matadatensatz angelegt hat.",
  field_acSubtype: "Objektuntertyp",
  field_acTags: "Stichworte",
  field_acceptedValues: "Akzeptierte Werte",
  field_aliases: "Aliase",
  field_analysisType: "Analysetyp",
  field_assemblageName: "Teilsammlungsname",
  field_attachment: "Anhänge zum Sammlungsevent",
  field_attributesTemplate: "Attributvorlage festlegen",
  field_barcode: "Barcode",
  field_collectingEventCollectionMethod: "Sammlungsmethode",
  field_collectingEventCollectionMethod_tooltip:
    "Methode, die während des Sammlungsevents genutzt wurde. Beispiel: UV-Lichtfalle, Bodenzug",
  field_collectingEventHost: "Wirt",
  field_collectingEventHost_tooltip:
    "Beobachteter Wirt der Materialprobe zur Zeit des Sammlungsevents",
  field_collectingEventSubstrate: "Substrat",
  field_collectingEventSubstrate_tooltip:
    "Beobachteter Untergrund, von dem der Organismus aufgesammelt wurde und auf dem er zu leben scheint.",
  field_collectingEvent_endDateTimeError:
    "Datums- und Uhrzeitsformat des Endereignisses muss eine Teilmenge von sein: YYYY-MM_DDTHH:MM:SS.MMM. Liegt die Uhrzeit vorliegt, ist 'T' zwingend erforderlich",
  field_collectingEvent_startDateTimeError:
    "Datums- und Uhrzeitsformat des Startereignisses muss eine Teilmenge von sein: YYYY-MM_DDTHH:MM:SS.MMM. Liegt die Uhrzeit vorliegt, ist 'T' zwingend erforderlich",
  field_collectorGroup_agentsError:
    "Mindestens ein Agent muss für die Gruppe angegeben werden",
  field_collectors: "Sammler",
  field_contact: "Kontakt",
  field_createdBy: "Erstellt von",
  field_createdDate: "Erstellungsdatum",
  field_createdOn: "Erstellt am",
  "field_dcCreator.displayName": "Digitalisiert von",
  field_dcFormat: "Medienformat",
  field_dcRights: "Copyright",
  field_dcSize: "Dateigröße",
  field_dcType: "Gespeicherter Objekttyp",
  field_description: "Beschreibung",
  "field_description.de": "Deutsche Beschreibung",
  "field_description.en": "Englische Beschreibung",
  "field_description.fr": "Französische Beschreibung",
  field_determination: "Bestimmungen",
  "field_determination.scientificName": "Wissenschaftlicher Name",
  "field_determination.scientificNameDetails":
    "Wissenschaftliche Klassifikation",
  "field_determination.typeStatus": "Typstatus",
  "field_determination.verbatimScientificName":
    "Wörtlicher wissenschaftlicher Name",
  field_determinationRemarks: "Anmerkungen zur Bestimmung",
  field_displayName: "Anzeigename",
  field_dwcCatalogNumber: "Katalognummer",
  field_dwcCoordinateUncertaintyInMeters: "Coordinatenabweichung in Metern",
  field_dwcCoordinateUncertaintyInMeters_tooltip:
    "Der horizontale Abstand in Metern zwischen der angegebenen decimalLatitude und der decimal Longitude, die den kleinsten Kreis beschreibt, der den gesamten Standort enthält",
  field_dwcCountry: "Land",
  field_dwcCountryCode: "Landesvorwahl",
  field_dwcDecimalLatitude: "Dezimale Latitude",
  field_dwcDecimalLongitude: "Dezimale Longitude",
  field_dwcDegreeOfEstablishment: "Gründungsgrad",
  field_dwcDegreeOfEstablishment_tooltip:
    "Das Ausmaß, in dem ein Organismus an einem bestimmten Ort und zu einer bestimmten Zeit überlebt, sich reproduziert und sein Verbreitungsgebiet ausdehnt.",
  field_dwcFieldNumber: "Sammlungsnummer",
  field_dwcFieldNumber_tooltip:
    "Eine Kennung, die dem Ereignis im Feld zum Zeitpunkt der Sammlung einer oder mehrerer Proben gegeben wurde. Dient oft als Bindeglied zwischen Feldnotizen und dem Ereignis.",
  field_dwcGeodeticDatum: "Geodätisches Datum",
  field_dwcGeodeticDatum_tooltip:
    "Das geodätische Datum, auf dem die in decimalLatitude und decimalLongitude angegebenen geografischen Koordinaten basieren. Die empfohlene Best Practice ist die Verwendung des EPSG-Codes. Beispiel: EPSG:4326 (EPSG-Code für WGS84)",
  field_dwcGeoreferenceProtocol: "Georeferenzierungsprotokoll",
  field_dwcGeoreferenceProtocol_tooltip:
    "Eine Beschreibung oder Referenzierung der Methode zur Bestimmung des räumlichen Fußabdrucks, der Koordinaten und der Unsicherheiten",
  field_dwcGeoreferenceRemarks: "Georeferenzierungsanmerkungen",
  field_dwcGeoreferenceRemarks_tooltip:
    "Anmerkungen oder Kommentare zur räumlichen Beschreibung der Bestimmung, um die zusätzlich oder im Gegensatz zu den in der Methode, auf die im Georeferenzprotokoll verwiesen wird, getroffenen Annahmen zu erläutern.",
  field_dwcGeoreferenceSources: "Georeferenzquelle",
  field_dwcGeoreferenceSources_tooltip:
    "Liste von Karten, Ortsverzeichnissen oder anderen Ressourcen, die zur Georeferenzierung des Standorts verwendet werden und ausreichend genau beschrieben sind, damit jeder in Zukunft dieselbsne Ressourcen verwenden kann",
  field_dwcGeoreferenceVerificationStatus: "Georeferenzierung nicht möglich",
  field_dwcMunicipality: "Gemeinde",
  field_dwcOtherCatalogNumbers: "Andere Katalognummern",
  field_dwcOtherRecordNumbers: "Andere Dokumentnummern",
  field_dwcRecordNumber: "Sammlernummer",
  field_dwcRecordNumber_tooltip:
    "Eine Kennung, die dem Ereignis vom Collector zum Zeitpunkt der Aufzeichnung gegeben wurde. Dient oft als Bindeglied zwischen Feldnotizen und einem Ereignisprotokoll, wie z. B. einer Probensammlernummer.",
  field_dwcRecordedBy: "Sammler Verbatim",
  field_dwcStateProvince: "Staat / Provinz",
  field_dwcVerbatimCoordinateSystem: "Koordinatensystem Verbatim",
  field_dwcVerbatimCoordinateSystem_tooltip:
    "Das Koordinatenformat für verbatimLatitude und verbatimLongitude oder die verbatimKoordinaten des Standorts. Beispiele: Dezimalgrad, Grad Dezimalminuten, Grad Dezimalsekunden, UTM",
  field_dwcVerbatimCoordinates: "Koordinaten Verbatim",
  field_dwcVerbatimCoordinates_tooltip:
    "Die ausführlich ursprünglichen Raumkoordinaten des Standorts. Das Koordinatenellipsoid, geodeticDatum oder vollständige Spatial Reference System (SRS) für diese Koordinaten sollte in verbatimSRS und das Koordinatensystem in verbatimCoordinateSystem gespeichert werden. Beispiele: 41 05 54S 121 05 34W, 17T 630000 4833400",
  field_dwcVerbatimDepth: "Tiefe Verbatim",
  field_dwcVerbatimDepth_tooltip:
    "Die original Beschreibung der Tiefe unter der lokalen Oberfläche. Beispiel: 100-200 m",
  field_dwcVerbatimElevation: "Höhe Verbatim",
  field_dwcVerbatimElevation_tooltip:
    "Die original Beschreibung der Höhe (Höhe über dem Meeresspiegel) des Standorts. Beispiel: 100-200 m",
  field_dwcVerbatimLatitude: "Verbatim Latitude",
  field_dwcVerbatimLatitude_tooltip:
    "Der wörtliche ursprüngliche Breitengrad des Standorts. Das Koordinatenellipsoid, geodeticDatum oder vollständige Spatial Reference System (SRS) für diese Koordinaten sollte in verbatimSRS und das Koordinatensystem in verbatimCoordinateSystem gespeichert werden. Beispiel: 41 05 54.03S",
  field_dwcVerbatimLocality: "Verbatim Lokalität",
  field_dwcVerbatimLongitude: "Verbatim Longitude",
  field_dwcVerbatimLongitude_tooltip:
    "Der ursprüngliche Verbatim-Längengrad des Standorts. Das Koordinatenellipsoid, geodeticDatum oder vollständige Spatial Reference System (SRS) für diese Koordinaten sollte in verbatimSRS und das Koordinatensystem in verbatimCoordinateSystem gespeichert werden. Beispiel: 121d 10? 34? W",
  field_dwcVerbatimSRS: "Verbatim SRS",
  field_dwcVerbatimSRS_tooltip:
    "Das Ellipsoid, das geodätische Datum oder räumliche Bezugssystem (SRS), auf dem die in verbatimLatitude und verbatimLongitude oder in ausführlichen Koordinaten angegebenen Koordinaten basieren. Empfohlene Best Practice ist die Verwendung des EPSG-Codes der SRS, falls bekannt. Beispiele: EPSG:4326, WGS84, NAD27",
  field_dwcVernacularName: "Vernakularname",
  field_editableBuiltInAttributes: "Sichtbare integrierte Eigenschaften",
  field_email: "E-Mail",
  field_enableGrid: "Raster aktivieren",
  field_enableGrid_tooltip:
    "Raster anlegen um Inhalte zu lagern. Nachfahrenlagereinheiten dürfen nicht enthalten sein.",
  field_endDate: "Enddatum",
  field_endEventDateTime: "Datum und Zeit des Endevents",
  field_endEventDateTime_tooltip:
    "Endzeitpunktformat muss ein Teilformat von YYYY-MM-DDTHH:MM:SS.MMM sein. Wenn ein Datum/Zeitwert vorhanden ist, ist âTâ erforderlich.",
  field_expeditionName: "Expeditionsname",
  field_familyNames: "Familienname",
  field_familyNames_tooltip:
    "Familienname(n), einschließlich zusammengesetzter Familiennamen",
  field_fieldExtensions: "Felderweiterungen",
  field_fileIdentifier: "Datei-Bezeichner",
  field_fileSize: "Dateigröße",
  field_filename: "Dateiname",
  field_geographicContext: "Geographischer Kontext",
  field_givenNames: "Vornamen",
  field_givenNames_tooltip: "Erster und alle zweiten Vornamen",
  field_gridLayoutDefinition_column_label: "Pro Spalte",
  field_gridLayoutDefinition_row_label: "pro Zeile",
  field_groupLabels: "Labels",
  field_host: "Host",
  field_id: "ID",
  field_includeQualityControls:
    "Qualitätskontrollen und Leerproben einbeziehen",
  field_isBaseForSplitByType: "Als Basisname für Aufteilung verwenden",
  field_isBaseForSplitByType_tooltip:
    "Wenn aktiviert und Typ-basierte Aufteilungskonfigurationen verwendet werden, wird diese Materialprobe zur Identifikatorableitung genutzt, sofern Eltern keine anderen Typen enthalten.",
  field_isFiledAs_tooltip:
    "Diese Bestimmung als abgelegt markieren. Nur eine Bestimmung kann als abgelegt markiert werden.",
  field_isInseperable: "Inhalt zusammen halten",
  field_isInseperable_tooltip: "Inhalte sind unzerteilbar",
  field_isPrimary_tooltip:
    "Diese Bestimmung als primäre Daten im Export markieren. Nur eine Bestimmung kann primär sein.",
  field_isRestricted: "Ist eingeschränkt",
  field_isolatedBy: "Isoliert durch",
  field_isolatedOn: "Isoliert auf",
  field_isolationRemarks: "Isolationsanmerkungen",
  field_license: "Lizenz",
  field_lifeStage: "Entwicklungsstadium",
  field_managedAttributeComponent: "Typ der Zieldatenkomponente",
  field_managedAttributeCreatedBy: "Angelegt durch",
  field_managedAttributeCreatedOn: "Angelegt an",
  field_managedAttributeMandatoryFieldsError:
    "Sowohl Name als auch Typ sind Pflichtfelder",
  field_managedAttributeName: "Attributsname",
  field_managedAttributes: "Regelattribute",
  field_materialSampleName: "Primäre ID",
  field_materialSampleRemarks: "Anmerkungen zur Materialprobe",
  field_materialSampleState: "Zustand der Materialprobe",
  field_materialSampleState_tooltip:
    "Stellt den Zustand einer Materialprobe dar, when ihr Zustand negativ beeinflusst wird.",
  field_materialSampleType: "Typ der Materialprobe",
  field_materialSampleType_tooltip:
    "Ein systemdefinierter Begriff, der die nachgelagerten Erwartungen und die Logik vorschreibt, wie abgeleitete (oder untergeordnete) Materialproben zu interpretieren und digital zu verwalten sind.",
  field_materialSample_identifierType_materialSampleId_label:
    "ID der Materialprobe",
  field_materialToBeReturned: "Zurückzusenden",
  field_name: "Name",
  field_notPubliclyReleasableReason:
    "Grund, warum es nicht möglich ist, es öffentlich bekannt zu geben",
  field_organismRemarks: "Organismus-Bemerkungen",
  field_organismsIndividualEntry: "Eintrag einzelner Organismen",
  field_organismsIndividualEntry_tooltip:
    "Lassen Sie diese Option AUS, um dieselben Daten für jeden Organismus zu kopieren. Schalten Sie auf ON um, um unterschiedliche Daten für jeden Organismus einzugeben.",
  field_organismsQuantity: "Anzahl Organismen",
  field_organizationMandatoryFieldsError:
    "Mindestens ein Organisationsname ist erforderlich",
  field_orientation: "Orientierung",
  field_orientation_tooltip:
    "Legt fest, wie ein Bild basierend auf seinem Orientierungswert angezeigt werden soll, muss eine Zahl zwischen 1 und 8 sein.",
  field_orientation_tooltipAlt: "Diagramm aller möglichen Orientierungswerten",
  field_originalFilename: "Ursprünglicher Dateiname",
  field_otherRecordNumbers: "Zusätzliche Sammlungsnummern",
  field_otherRecordNumbers_tooltip:
    "Andere Nummern oder Identifikatoren, die mit dem Sammelereignis verbunden sind und helfen, es zu unterscheiden. Fügen Sie KEINE probenbasierte Kennungen wie Zugangsnummern hinzu.",
  field_parentStorageUnit: "Ort",
  field_participants: "Teilnehmende",
  field_personIdentifierTypeError: "Identifikatortyp ist erforderlich.",
  field_personIdentifierUniqueError: "Identifikatoren müssen eindeutig sein.",
  field_personIdentifierValueError: "Identifikatorwert ist erforderlich.",
  field_personMandatoryFieldsError: "Das Anzeigenamen-Feld ist erforderlich.",
  field_preparationDate: "Datum der Aufbereitung",
  field_preparationFixative: "Fixativ der Aufbereitung",
  field_preparationFixative_tooltip:
    "Lösung, auf die die Materialprobe aufgetragen wurde oder in der sie aufbewahrt wird. Beispiele: EtOH 95 %, EtOH 75 %, EtOH 70 %, Kochsalzlösung, Klebstoff.",
  field_preparationMaterials: "Material der Aufbereitung",
  field_preparationMaterials_tooltip:
    "Zusätzliche, typischerweise inerte physikalische Umgebungen oder Gegenstände, in oder auf denen der Organismus in einer Materialprobe gelagert wird. Es drückt weder den Zustand des Organismus noch die verwendeten Fixiermittel aus, sondern die Materialien, die es ermöglichen, den Organismus darzustellen. Beispiele: Pinnnadel, Glasfläschchen, Plastikgefäß, Glasgefäß, Objektträger, säurefreies Papier, Klebefalle/-karte, Eppendorf-Röhrchen.",
  field_preparationMethod: "Methode der Aufbereitung",
  field_preparationMethod_tooltip:
    "Ein Substantiv, das den bei der Aufbereitung der Materialprobe verwendeten Prozess (das Wie) darstellt. Beispiele: Kultur, mechanische Inokulation, Dissektion.",
  field_preparationRemarks: "Anmerkungen zur Aufbereitung",
  field_preparationSubstrate: "Substrat der Aufbereitung",
  field_preparationSubstrate_tooltip:
    "Material, auf dem der Organismus in der Materialprobe präsentiert wird oder wächst. Beispiele: Stein, Baumstamm, Agar.",
  field_preparationType: "Aufbereitungstyp",
  field_preparationType_tooltip:
    "Ein Substantiv, das aufzeigt, was aufbereitet wird. Beispiele: Bein, Gewebe, DNA",
  field_preservationType: "Konservierungstyp",
  field_preservationType_tooltip:
    "Beschreibung des Konservierungstyps der Materialprobe. Beispiel: Gefriertrocknen.",
  field_projectName: "Projektname",
  field_projectStatus: "Projektstatus",
  field_publiclyReleasable: "Öffentlich aufrufbar",
  field_publiclyReleasable_tooltip:
    "Gibt an, ob das Objekt öffentlich auf einer Webseite oder in offenen Datenportalen veröffentlicht werden könnte.",
  field_remarks: "Anmerkungen",
  field_restrictToCreatedBy: "Privat",
  field_restriction: "Einschränkung",
  field_restrictionRemarks: "Bemerkungen zur Einschränkung",
  field_restrictions: "Einschränkungen",
  "field_run-summary_items.genericMolecularAnalysisItemSummary.genericMolecularAnalysisSummary.analysisType":
    "Analysetyp",
  "field_run-summary_items.genericMolecularAnalysisItemSummary.genericMolecularAnalysisSummary.name":
    "Workflow-Name",
  "field_run-summary_items.genericMolecularAnalysisItemSummary.name":
    "Run-Elementname",
  "field_run-summary_name": "Run-Name",
  field_sampleName: "Probenname",
  field_scientificName: "Wissenschaftlicher Name",
  field_scientificNameDetails: "Wissenschaftliche Klassifikation",
  field_scientificNameInput: "Wissenschaftlicher Name",
  field_sex: "Geschlecht",
  field_sourceSet: "Quellmenge",
  field_startDate: "Anfangsdatum",
  field_startEventDateTime: "Datum und Zeit des Anfangsevents",
  field_startEventDateTime_tooltip:
    "Startzeitpunktformat muss ein Teilformat von YYYY-MM-DDTHH:MM:SS.MMM sein. Wenn ein Datum/Zeitwert vorhanden ist, ist âTâ erforderlich.",
  field_tags: "Stichworte",
  field_targetOrganismPrimaryClassification:
    "Klassifikation des Zielorganismus",
  field_targetOrganismPrimaryScientificName:
    "Wissenschaftlicher Name des Zielorganismus",
  field_title: "Titel",
  "field_title.en": "Englischer Titel",
  "field_title.fr": "FranzÃ¶sischer Titel",
  field_transcriberRemarks: "Notizen des Übertragenden",
  field_type: "Typ",
  field_typeStatus: "Statustyp",
  field_typeStatusEvidence: "Statustyp - Nachweis",
  field_useNextSequence: "Verwenden Sie den nächsten verfügbaren Identifikator",
  field_useTargetOrganism: "Verwenden Sie den Zielorganismus",
  field_useTargetOrganismError:
    "Der Zielorganismus muss auswählt werden, wenn 'Zielorganismus verwenden' aktiviert ist.",
  field_verbatimDate: "Verbatim Datum",
  field_verbatimDeterminer: "Verbatim Bestimmer",
  field_verbatimEventDateTime: "Verbatim Datum und Uhrzeit des Events",
  field_verbatimRemarks: "Verbatim Anmerkungen",
  field_verbatimScientificName: "Verbatim wissenschaftlicher Name",
  field_visibleManagedAttributes: "Sichtbare Regelattribute im Editor",
  field_visibleManagedAttributes_tooltip:
    "Durch das Hinzufügen oder Entfernen eines Attributs mithilfe dieser Dropdown-Liste wird der Wert nicht geändert oder entfernt. Es wirkt sich nur auf die Sichtbarkeit des Attributs in diesem Editor aus.",
  field_vocabularyElementType_boolean_label: "Boolean",
  field_vocabularyElementType_date_label: "Datum",
  field_vocabularyElementType_decimal_label: "Dezimal",
  field_vocabularyElementType_integer_label: "Ganzzahl",
  field_vocabularyElementType_picklist_label: "Auswahlliste",
  field_vocabularyElementType_text_label: "Text",
  field_webpage: "Webseite",
  field_xmpMetadataDate: "zuletzt geändert am",
  field_xmpMetadataDate_tooltip:
    "Datum und Uhrzeit der letzten Änderung des Eintrags",
  field_xmpRightsWebStatement: "Lizenz",
  fileTooBig: "Datei ist zu groß",
  filterAttribute: "Filterattribut",
  filterByGroup: "nach Gruppe filtern",
  filterPredicate: "Prädikat filtern",
  filterValue: "Filterwert",
  footerContactInfo: "Kontaktinformationen",
  footerPrivacy: "Datenschutz",
  footerTermsAndConditions: "Geschäftsbedingungen",
  forTestingPurposesOnlyMessage:
    "Nur zur Testzwecken. Nur nicht klassifizierte Daten sillten hochgeladen werden. Alle hochgeladenen Daten können jederzeit gelöscht werden.",
  formNavigation: "Formularnavigation",
  formTemplate: "Benutzerdefinierte Vorlage",
  formTemplateEditPermission_tooltip:
    "Nur der Ersteller dieser Formularvorlage kann sie bearbeiten.",
  formTemplateGroupVisibility_tooltip:
    "Bitte wählen Sie eine Gruppe für diese Formularvorlage aus. Diese bestimmt deren Sichtbarkeit.",
  formTemplatePrivate_tooltip: "Formularvorlage ist nur für Sie sichtbar.",
  formTemplatePublic_tooltip:
    "Formularvorlage ist für alle Mitglieder der Gruppe {group} sichtbar.",
  formTemplateSelection: "Benutzerdefinierte Vorlage",
  formTemplates: "Formularvorlage",
  fromDinaUserGuide: "Aus dem DINA Benutzerhandbuch",
  fromParent: "(von {parentLink})",
  generateBatch: "Batch generieren",
  generateLabel: "Ettikett generieren",
  generateSeries: "Serie generieren",
  generatingReport: "Bericht wird erstellt â¦",
  geoReferenceAssertion: "Georeferenzierungszusage",
  geoReferencing: "Georeferenzierung",
  geoReferencingLegend: "Georeferenzierung",
  geographyLegend: "Geographie (Orte)",
  geographySearchBoxTooltip:
    "Suche nach Ortsnamen (z.B. Ottawa) oder WGS84 Koordinaten (z.B. '40.123, - 74.123')",
  georeferencedByLabel: "Georeferenziert durch (Agent)",
  georeferencedDateLabel: "Georeferenzierungsdatum",
  globalNameSearchLabel: "Suche nach globalem Namen",
  globalNameSources: "Namensquellen",
  goToObjectUploadPage: "Zur Objekt-Upload-Seite",
  goToThePreviousStep: "Zurück zum vorherigen Schritt",
  governmentOfCanada: "Regierung von Kanada",
  governmentOfCanadaSymbol: "Symbol der kanadischen Regierung",
  group: "Gruppe",
  groupListTitle: "Gruppen",
  groupMustBeSelected: "Eine Gruppe muss ausgewählt werden",
  groupName: "Name",
  hostOrganismLegend: "Wirtsorganismus",
  http403ForbiddenError: "Zugriff verweigert",
  http500InternalServerError: "Unerwarteter Serverfehler",
  identifierLegend: "Identifikatoren",
  identifierType: "Typen von Identifikatoren",
  identifierURI: "URI Identifikator",
  identifiers: "Identifikatoren",
  imagePreview: "Bildvorschau",
  includeAll: "Alle hinzunehmen",
  insertHybridSymbol: "Hybridsymbol einfügen",
  institution: "Institution",
  institutionListTitle: "Institutionen",
  isFiledAs: "Gespeichert als",
  isTargetHeader: "Ist Ziel?",
  isolation: "Isolation",
  keepContentsTogether: "Inhalte zusammen halten",
  language: "Sprache",
  languageOfPage: "de",
  largeImg: "Großes Bild",
  latLongAutoSetterButton: "In Dezimale Lat/Long konvertieren",
  latitudeValidationError:
    "Ungültiger Breitengrad: {Breitengrad}, \n Der gültige Breitengradbereich liegt zwischen -90 und 90 für Grad und 0 bis 60 für Minute und Sekunde",
  literalGeoreferencedByLabel: "Georeferenziert durch",
  load: "Belastung",
  loading: "Laden",
  loadingSpinner: "Lädt...",
  loanTransaction: "Transaktion",
  loanTransactionManagedAttributeListTitle:
    "Regelattribut für Kredite und Transaktionen",
  loanTransactionsSectionTitle: "Transaktionen",
  locationLabel: "Ort",
  locationPlaceholder: "Ort zum Suchen eingeben...",
  longitudeValidationError:
    "Ungültiger Längengrad: {longtitude}, \n der gültige Längengradbereich liegt zwischen -90 und 90 für Grad und 0 bis 60 für Minute und Sekunde",
  makeFiledAs: "als 'abgelegt als' markieren",
  makePrimary: "als 'primär' markieren",
  managedAttributeEditTitle: "Regelattribut bearbeiten",
  managedAttributeTemplateOrderInfo:
    "Dieses Regelattribut Layout wird in der Formularvorlage gespeichert",
  managedAttributeValueLabel: "Wert",
  managedAttributes: "Regelattribute",
  managedAttributesViews: "Formularvorlage",
  "material-sample": "Materialprobe",
  materialDirection_tooltip:
    "Transaktionsmaterialrichtung: {materialDirection}",
  materialIn: "Eingangsmaterial",
  materialOut: "Ausgangsmaterial",
  materialSample: "Materialprobe",
  materialSampleAssociationLegend: "Zuordnung von Materialproben",
  materialSampleAttachments: "Anhang zur Materialprobe",
  materialSampleFieldExtensions: "Materialprobe-Felderweiterungen",
  materialSampleFieldsMapping: "Feld der Materialprobe",
  materialSampleFormTemplate: "Formularvorlage zur Materialprobe",
  materialSampleFormTemplates: "Formularvorlage zur Materialprobe",
  materialSampleInfo: "Information zur Materialprobe",
  materialSampleListTitle: "Materialprobe",
  materialSampleManagedAttributes: "Regelattribut zur Materialprobe",
  materialSampleName: "Name der Materialprobe",
  materialSampleShowParentAttributes: "Übergeordnete Attribute",
  materialSampleSplitConfiguration: "Aufteilungskonfiguration",
  materialSampleSplitConfigurationCondition: "Bedingung",
  materialSampleSplitConfigurationConditionType: "Bedingungstyp",
  materialSampleSplitConfigurationDirectParent: "Direktes Elternobjekt",
  materialSampleSplitConfigurationMaterialSampleGeneration:
    "Erzeugung der Materialprobe",
  materialSampleSplitConfigurationMaterialSampleNameGeneration:
    "Erzeugung des Materialproben-Namens",
  materialSampleSplitConfigurationRequiredMaterialSampleType:
    "Der Materialprobentyp ist erforderlich",
  materialSampleSplitConfigurationSeparator: "Trennzeichen",
  materialSampleSplitConfigurationStrategy: "Strategie",
  materialSampleSplitConfigurationVisibleMaterialSampleType:
    "Der Materialprobentyp muss sichtbar sein",
  materialSampleTypeListTitle: "Typen der Materialprobe",
  materialSampleViewTitle: "{primaryID} - Materialprobe",
  materialSamples: "Materialproben",
  materialSamplesBulkFinishLabel: "Materialproben  {actionType}",
  materialSamplesCreatedLabel: "Materialproben wurden erzeugt",
  materialSamplesToCreate: "zu erstellende Materialproben",
  metadata: "Metadaten",
  metadataAttributesTemplateSave: "Bitte speichern Sie diese Attributvorlage",
  metadataBucketNameLabel: "Name der Kategorie",
  metadataBuiltInAttributesLabel: "integrierte Attribute",
  metadataBulkEditTagsLabel: "Schlagworte (durch Komma getrennt)",
  metadataDcFormatLabel: "DcFormat",
  metadataExternalResourceDetailsLabel: "Details zu externen Ressourcen",
  metadataFieldsMapping: "Metadatenfeld",
  metadataFileExtensionLabel: "Dateierweiterung",
  metadataFileIdentifierLabel: "Dateikennung",
  metadataFileStorageDetailsLabel: "Dateispeicher",
  metadataFilenameLabel: "Dateiname",
  metadataFirstDigitalVersionCreatedDateLabel:
    "Die erste digitale Version wurde erstellt von",
  metadataFormTitle: "Metadaten",
  metadataHashFunctionLabel: "Hash-Funktion",
  metadataHashValueLabel: "Hashwert",
  metadataLastMetadataModificationTimeLabel:
    "Letztes Änderungsdatum der Metadaten",
  metadataListGalleryLayout: "Galerie",
  metadataListTableLayout: "Tabelle",
  metadataManagedAttributesLabel: "Regelattribute",
  metadataMediaDetailsLabel: "Medien",
  metadataObjectTypeLabel: "Typ der gespeicherten Objekte",
  metadataPageLink: "Detailseite",
  metadataResourceExternalURLLabel: "URL der externen Ressource",
  metadataRightsDetailsLabel: "Rechte",
  metadataTagsLabel: "Stichworte",
  metadataUploadDetailsLabel: "Details hochladen",
  metersField_tooltip:
    "Bitte nutzen Sie folgende Einheiten für die automatische Konvertierung: ft, in, ft in, yd, mm, cm, km, pd, po, pd po.",
  moveAllContent: "den gesamten Inhalt verschieben",
  multiple: "Mehrere",
  multipleMaterialSamples: "Mehrere Materialproben",
  multipleUnits: "Mehrere Einheiten",
  mustBeValidDecimalValue: "Muss ein gültiger Dezimalwert sein.",
  mustBeValidIntegerValue: "Muss ein gültiger ganzzahliger Wert sein.",
  noBulkEditFilesError:
    "Sie haben keine Dateien für die Massenbearbeitung hochgeladen. Gehen Sie zur Upload-Seite",
  noChildren: "keine Kindelemente",
  noFileToDisplay: "keine Datei zur Anzeige vorhanden",
  noGroups: "keine Gruppen",
  noManagedAttributeValues: "Keine Werte für Regelattribute vorhanden.",
  noResultsFound: "Keine Ergebnisse gefunden.",
  noneTopLevel: "Keine (oberste Ebene)",
  notEditableWhenThereAreChildStorageUnits:
    "Kann nicht bearbeitet werden, wenn Kindelemente in der Lagerungseinheit vorhanden sind.",
  notPubliclyReleasable: "Nicht öffentlich zugänglich",
  objectListTitle: "Gelagerte Objekte",
  objectStoreDataUnavailable:
    "Die Daten der gelagerten Objekte sind nicht verfügbar",
  objectStoreDetailsTitle: "Details des Objektspeichers",
  objectStoreTitle: "Objektspeicher",
  objectSubtypeListTitle: "Objektsubtypen",
  objectSubtypeTitle: "Objektsubtyp",
  openGeographySearchButtonLabel: "In Open Street Maps suchen",
  organism: "Organismus",
  organismState: "Zustand des Organismus",
  organisms: "Organismen",
  organizationEnglishNameLabel: "englischer Name",
  organizationFrenchNameLabel: "französischer Name",
  organizationGermanNameLabel: "deutscher Name",
  organizationListTitle: "Organisationen",
  originalFile: "Originaldatei",
  originalMaterialSampleLabel: "original Materialprobe",
  otherIdentifiers: "Weitere Identifikatoren",
  overwriteValues: "Inhalte überschreiben",
  parentCollectionLabel: "Ausgangssammlung",
  parentMaterialSample: "Ausgangsprobe",
  parentSampleNotFoundLabel: "Ausgangsprobe wurde nicht gefunden",
  personListTitle: "Personen",
  phacAnimalRGLevel: "PHAC Animal RG Level",
  phacContainmentLevel: "PHAC Containment Level",
  phacHumanRGLevel: "PHAC Human RG Level",
  possibleDataLossWarning:
    "Es sind noch Daten ungespeichert, sind Sie sicher, dass Sie die Seite verlassen möchten?",
  preparation: "Aufbereitung",
  preparationData: "Aufbereitungsdaten",
  preparationMethodNameLabel: "Name der Aufbereitungsmethode",
  preparationProtocols: "Aufbereitungsprotokolle",
  preparationTypeListTitle: "Aufbereitungstyp",
  preparationTypeNameLabel: "Name der Aufbereitungstyps",
  preparations: "Aufbereitungen",
  preparedBy: "Aufbereitet durch",
  previewAndCustomizeLabel: "Vorschau und Anpassung",
  previewNotAvailable: "Vorschau ist nicht verfügbar",
  primary: "Primär",
  primaryButton_tooltip:
    "Machen Sie diese Behauptung beim Export zum primären Datenpunkt. Nur eine Behauptung kann primär sein.",
  primaryId: "Primäre ID",
  proceedToCreateMetadata: "Mit der Erstellung der Metadaten fortfahren",
  projectAttachments: "Projektanhänge",
  projectFieldExtensions: "Projekt-Felderweiterungen",
  projectListTitle: "Projekte",
  projects: "Projekte",
  protocolAttachments: "Protokollanhänge",
  protocolListTitle: "Protokolle",
  protocolNameLabel: "Protokollname",
  protocolViewTitle: "Protokoll",
  reception: "Rezeption",
  removeAssertionLabel: "Diese Geo-Referenz löschen",
  removeComponentData: "Diese {component} Daten löschen",
  removeFromParentStorageUnit: "Aus übergeordneter Lagereinheit entfernen",
  removeGroup: "Gruppe löschen",
  removeIdentifier: "Identifier löschen",
  removeManagedAttributeValue:
    "Inhalt des Regelattributes löschen: {attributeNames}",
  removeOrganism: "Organismus löschen",
  removeSavedSearch: "gespeicherte Suche löschen",
  removeThisElement: "Dieses {typeName} löschen",
  removeThisPlaceLabel: "Diesen Ort löschen",
  resetMetadataEditorAttributesButtonText:
    "Auf ursprüngliches Attributelayout zurücksetzen",
  resetNamesToDefaultValues: "Namen auf den ursprünglichen Inhalt zurücksetzen",
  restricted: "Eingeschränkt",
  restrictions: "Einschränkungen",
  revisionsButtonText: "Revisionen",
  revisionsByUserPageTitle: "Revisionen durch den Nutzer",
  revisionsListTitle: "Revisionen für {name}",
  role: "Rolle",
  roleAction: "Rolle/Aktion",
  roles: "Rollen",
  rolesPerGroup: "Rollen pro Gruppe",
  runWorkflow: "",
  save: "Speichern",
  saveAll: "Alles speichern",
  saveAndCopyToNext: "Speichern und zum nächsten kopieren",
  saveAndCreateNewMaterialSampleButton:
    "Speichern und neues Material Sample anlegen",
  saveAndGoToViewPageButton: "Speichern und zur nächsten Seite gehen",
  saveAsDefault: "als Default speichern",
  saveGeoReferenceAssertion: "Geo-Referenz Erklärung speichern",
  saveSearch: "Suche speichern",
  saveSearchInstruction:
    "Bitte tragen Sie einen Namen für Ihre Suche ein. Sie können diese Suche auch als default markieren",
  saveThisOrderView: "",
  scheduledActions: "geplante Aktionen",
  scientificNameSearch: "Suche in den wissenschaftlichen Namen",
  searchButton: "Suche",
  searchOnCOL: "Suche im Catalogue of Life",
  searchPreviousTags: "Vorherige Tags durchsuchen",
  searchResults: "Suchergebnisse ({resultSize})",
  searchStorage: "Lagereinheiten durchsuchen",
  selectAnExtenstion: "Erweiterung auswählen",
  selectCollectorGroupLabel:
    "Wählen Sie eine Sammlergruppe, um das Feld 'Sammler' vorab auszufüllen",
  selectGroup: "Gruppe auswählen",
  selectOrType: "Auswahl oder Eingabe",
  selectRuleSet: "Regelsatz auswählen",
  seriesModeInfo: "Serienmodus: Materialproben haben aufsteigende IDs.",
  set: "",
  setAll: "",
  shipmentAddress: "Lieferadresse",
  shipmentDetails: "Lieferdetails",
  showLess: "Weniger anzeigen",
  showMore: "Mehr anzeigen",
  showParentAttributes: "Übergeordnete Materialprobe",
  showing: "Anzeigen",
  showingFilteredStorageUnits: "Gefilterte Lagerungseinheiten anzeigen",
  showingTopLevelStorageUnits: "Top Level Lagerungseinheiten anzeigen",
  skipColumn: "Überspringen",
  skipToAboutThisApplication: "Zur Seite 'Über diese Seite' springen",
  skipToBasicHtmlVersion: "zur basic HTML Version wechseln",
  skipToMainContent: "Zum Hauptinhalt springen",
  source: "Quelle",
  specifyParentContainer: "Bitte Elternelement auswählen",
  splitButton: "Aufteilen",
  splitConfigurationAdd: "Aufteilungskonfiguration hinzufÜ¼gen",
  splitConfigurationEdit: "Aufteilungskonfiguration bearbeiten",
  splitConfigurationTitle: "Aufteilungskonfigurationen",
  splitConfiguration_separator_dash: "Bindestrich",
  splitConfiguration_separator_space: "Leerzeichen",
  splitConfiguration_separator_underscore: "Unterstrich",
  splitFrom: "Aufteilen von",
  splitSampleActionMetadataLegend: "Aktions-Metadaten",
  splitSampleChildSamplesToCreateLabel:
    "Zu erstellende untergeordnete Materialprobe",
  splitSampleConfigLegend: "Konfiguriere die Aktion: Aufteilen",
  splitSampleDescription:
    "Teilt eine Elternprobe in eine oder mehrere untergeordnete Proben auf",
  splitSampleInstructions:
    "Es können maximal 30 untergeordneten Proben erstellt werden",
  splitSampleRemarksPlaceholder:
    "Bitte beschreiben Sie, was sie getan haben, was geändert wurde oder was als Endresultat passiert ist (z.B. Entfernen eines Beins)",
  splitSampleTagOriginalAsDestroyed: "Das Original als 'Zerstört' markieren",
  splitSubsampleTitle: "Die Materialprobe aufteilen",
  splitWorkflowRunTitle: "Workflow-Durchlauf aufteilen",
  startNewRunConfigLabel: "Starte einen neuen Durchlauf",
  stateChangeMetaLegend: "Statusänderungs-Metadaten (Optional)",
  stateProvinceLabel: "Staat / Provinz",
  status: "Status",
  storage: "Lager",
  storageUnitListTitle: "Lagereinheit",
  storageUnitName: "Name der Lagereinheit",
  storageUnitType: "Typ der Lagereinheit",
  storageUnitTypeListTitle: "Typen der Lagereinheit",
  storagesCreatedByMe: "Lager, die von mir erstellt wurden",
  tags: "Etiketten",
  target: "Ziel",
  template: "Vorlage",
  thisWillRemoveYourTemplate:
    "Dieser Vorgang entfernt die ausgewählten Modellfelder und Standardwerte.",
  thumbnail: "Vorschaubild",
  thumbnailNotAvailableText: "Kein Vorschaubild vorhanden",
  title_collectingEvent: "Sammlungsevent",
  title_collection: "Sammlung",
  title_organism: "Organismus",
  title_person: "Person",
  title_preparationMethod: "Preparationsmethode",
  title_preparationType: "Preparationstyp",
  title_storageUnit: "Lagereinheit",
  title_storageUnitType: "Typ der Lagereinheit",
  to: "Zu",
  toBeReturned: "Zurückzusenden",
  tooltipDefaultLinkMessage: "Klicken Sie hier, um mehr zu erfahren.",
  toponymyLegend: "Aktueller geographischer Ort",
  totalExtenstionFieldsCount: "Gesamtzahl der Felder für diese Erweiterung",
  transactionAttachments: "Anhänge der Transaktion",
  transactionDetails: "Transaktionsdetails",
  transactions: "Transaktionen",
  typeAnythingOrPickAScientificName:
    "Geben Sie etwas ein oder wählen Sie einen wissenschaftlichen Namen",
  typeNewTagOrSearchPreviousTags:
    "Geben Sie ein neues Ettikett ein oder durchsuchen Sie die voerherigen Etiketten",
  typeSpecimen: "Geben sie das Exemplar ein",
  updateExistingView: "Den bestehenden View aktualisieren",
  uploadButtonText: "Hochladen",
  uploadFilesMaxSize: "Die maximale Filegröße ist {maxSize}.",
  uploadFormInstructions:
    "Hier die Dateien hineinziehen und ablegen oder klicken um den Durchsuchen-Dialog zu öffnen.",
  uploadNewAttachments: "neue Anhänge hochladen",
  uploadPageTitle: "Dateien hochladen",
  useCollectorGroupLabel: "Collector-Gruppe verwenden",
  useLastSelectedOrderView:
    "Verwenden Sie die zuletzt ausgewählte Auftragsansicht",
  userListTitle: "Nutzer",
  userMustBelongToGroup: "Der Nutzer muss einer Gruppe angehören",
  userProfile: "Benutzerprofil",
  userViewTitle: "Nutzer",
  valueCad: "Wert ($ CAD)",
  verbatimDeterminationLegend: "Verbatim Bestimmung",
  verbatimEventDateTime: "Verbatim Event Datum und Zeit",
  verbatimLabelLegend: "Verbatim Label",
  verbatimLatLong: "Verbatim Lat/Long",
  viewDetailButtonLabel: "Details anzeigen",
  viewOnMap: "Auf der Karte anzeigen",
  viewPreviewButtonText: "Vorschau",
  warningMessage: "Warnmeldung",
  whoAmITitle: "Wer bin ich?",
  withAKeyboard: "Mit Tastatur",
  withAMouse: "Mit der Maus",
  workbookExtraFiles:
    "Folgende Dateien in der Tabelle wurden nicht hochgeladen: {files}{remaining, plural, =0 {} other { (und {remaining} weitere)}}",
  workbookGroupUploadTitle: "Arbeitsmappe hochladen",
  workbookInsufficientRows:
    "Die Tabelle enthält {actual} Zeilen, aber {expected} Dateien wurden hochgeladen. Bitte sicherstellen, dass alle Dateien hochgeladen wurden.",
  workbookMissingFiles:
    "Folgende hochgeladene Dateien fehlen in der Tabelle: {files}{remaining, plural, =0 {} other { (und {remaining} weitere)}}",
  workbookTitle: "Arbeitsmappen",
  workbookUploadBulkEditInfoMessage:
    "{count} Dateien für Massenbearbeitung bereit. Laden Sie eine Tabelle mit einer Spalte Original Filename hoch",
  workbookUploadFailure:
    "Es ist ein Problem beim Lesen der hochgeladenen Tabelle aufgetreten",
  workbookUploadInstructions:
    "Hier die Tabelle hineinziehen und ablegen oder klicken um den Durchsuchen-Dialog zu öffnen.",
  year: "Jahr",
  yearMonth: "Jahr-Monat",
  yearMonthDay: "Jahr-Monat-Tag",
  yearMonthDayTime: "Jahr-Monat-Tag-Zeit"
};
