import { SEQDB_MESSAGES_ENGLISH } from "./seqdb-en";

/**
 * French translation of SeqDB English messages
 */
export const SEQDB_MESSAGES_FRENCH: Partial<typeof SEQDB_MESSAGES_ENGLISH> = {
  addPcrPrimerTitle: "Ajouter une amorce PCR",
  addPcrProfileTitle: "Ajouter un profil de thermocycleur",
  addProductTitle: "Ajouter un produit",
  addProtocolTitle: "Ajouter un protocole",
  addRegionTitle: "Ajouter une région",
  addWorkflowTitle: "Ajouter un flux de SNG",
  availableSamplesTitle: "Échantillons disponibles",
  backToListButtonText: "Retour à la liste",
  cancelButtonText: "Annuler",
  createButtonText: "Créer nouveau",
  deselectAllCheckedSamplesButtonText:
    "<-- Désélectionner tous les échantillons cochés ",
  deselectButtonText: "Désélectionner",
  editPcrPrimerTitle: "Modifier l’amorce PCR",
  editPcrProfileTitle: "Modifier le profil de thermocycleur",
  editProductTitle: "Modifier le produit",
  editProtocolTitle: "Modifier le protocole",
  editRegionTitle: "Modifier la région",
  editWorkflowTitle: "Modifier le flux de SNG",
  editableTable: "Tableau modifiable",
  field_averageFragmentSize: "Taille moyenne des fragments",
  field_concentration: "Concentration",
  "field_group.groupName": "Nom du groupe",
  field_inputAmount: "Montant de l’entrée",
  field_inputNg: "Entrée (Ng)",
  field_name: "Nom",
  field_notes: "Remarques",
  field_product: "Produit",
  field_protocol: "Protocole",
  field_quality: "Qualité",
  "field_sample.name": "Nom d’échantillon",
  field_size: "Taille",
  field_targetBpSize: "Taille de la paire de bases cible",
  indexI5: "Indice i5",
  indexI7: "Indice i7",
  indexSetListTitle: "Ensembles d’indices",
  indexSetMustBeSet: "L’ensemble d’indices doit être défini.",
  notShearedStatus: "Sans cisaillement",
  notSizeSelectedStatus: "Sans sélection de taille",
  pcrPrimerListTitle: "Amorces PCR",
  pcrPrimerViewTitle: "Amorce PCR",
  pcrProfileListTitle: "Profils de thermocycleur",
  pcrProfileViewTitle: "Profil de thermocycleur",
  plpDetailsFormTitle:
    "Ajouter détails sur le cisaillement ou la sélection de taille",
  plpEditModeLabel: "Modifier",
  plpShearingModeLabel: "Détails sur le cisaillement",
  plpSizeModeLabel: "Détails sur la sélection de taille",
  plpStepTitle: "Cisaillement et sélection de taille",
  plpViewModeSelectorLabel: "Mode d’affichage :",
  productListTitle: "Produits",
  productUpcFieldHelpText:
    "Nota : Le code universel de produit peut être lu par un lecteur de codes à barres en mode clavier",
  productViewTitle: "Produit",
  protocolListTitle: "Protocoles",
  protocolViewTitle: "Protocole",
  regionListTitle: "Régions",
  regionViewTitle: "Région",
  removeShearingDetailsButtonText:
    "Supprimer les détails sur le cisaillement sélectionnés",
  removeSizeSelectionDetailsButtonText:
    "Supprimer les détails sur la sélection de taille sélectionnés",
  sampleSelectionTitle: "Sélection d’échantillons",
  selectAllCheckedSamplesButtonText:
    "Sélectionner tous les échantillons cochés -->",
  selectButtonText: "Sélectionner",
  selectedSamplesTitle: "Échantillons sélectionnés",
  seqdbTitle: "Base de données des séquences (fr)",
  shearedStatus: "Cisaillé",
  shearingLabel: "Cisaillement",
  sizeSelectedStatus: "Sélection de taille ajoutée",
  sizeSelectionLabel: "Sélection de taille",
  wellCoordinates: "Coordonnées du puits",
  workflowDetailsTab: "Détails",
  workflowListTitle: "Flux de SNG",
  workflowStepTab: "Étape {number} : {name}",
  workflowViewTitle: "Flux de SNG",
  addPcrBatchTitle: "Ajouter le lot PCR",
  addMolecularSampleTitle: "Ajouter l’échantillon moléculaire",
  editPcrBatchTitle: "Modifier le lot PCR",
  editMolecularSampleTitle: "Modifier l’échantillon moléculaire",
  molecularSample: "Échantillon moléculaire",
  molecularSampleListTitle: "Échantillons moléculaires",
  pcrBatchListTitle: "Lots PCR",
  pcrBatchViewTitle: "Visualiser le lot PCR",
  sampleSelectionInstructions:
    "Votre sélection d’échantillons est sauvegardée lorsque vous appuyez sur un bouton de sélection ou de désélection. Il n’y a pas de bouton Enregistrer distinct.",
  workflowDetails: "Détails du flux de travail"
};
