import { SEQDB_MESSAGES_ENGLISH } from "./seqdb-en";

/**
 * French translation of SeqDB English messages
 */
export const SEQDB_MESSAGES_FRENCH: Partial<typeof SEQDB_MESSAGES_ENGLISH> = {
  addMolecularSampleTitle: "Ajouter l’échantillon moléculaire",
  addPcrBatchTitle: "Ajouter le lot PCR",
  addPcrPrimerTitle: "Ajouter une amorce PCR",
  addProductTitle: "Ajouter un produit",
  addProtocolTitle: "Ajouter un protocole",
  addRegionTitle: "Ajouter une région",
  addSeqBatchTitle: "Ajouter un lot de SEQ",
  addThermocyclerProfileTitle: "Ajouter un profil de thermocycleur",
  addWorkflowTitle: "Ajouter un flux de SNG",
  availableMaterialSamplesTitle: "Échantillons de matériau disponibles",
  availableSamplesTitle: "Échantillons disponibles",
  backToListButtonText: "Retour à la liste",
  cancelButtonText: "Annuler",
  createButtonText: "Créer nouveau",
  deselectAllCheckedSamplesButtonText:
    "<-- Désélectionner tous les échantillons cochés ",
  deselectButtonText: "Désélectionner",
  editMolecularSampleTitle: "Modifier l’échantillon moléculaire",
  editPcrBatchTitle: "Modifier le lot PCR",
  editPcrPrimerTitle: "Modifier l’amorce PCR",
  editProductTitle: "Modifier le produit",
  editProtocolTitle: "Modifier le protocole",
  editRegionTitle: "Modifier la région",
  editSeqBatchTitle: "Modifier un lot de SEQ",
  editThermocyclerProfileTitle: "Modifier le profil de thermocycleur",
  editWorkflowTitle: "Modifier le flux de SNG",
  editableTable: "Tableau modifiable",
  field_averageFragmentSize: "Taille moyenne des fragments",
  field_concentration: "Concentration",
  "field_group.groupName": "Nom du groupe",
  field_inputAmount: "Montant de l’entrée",
  field_inputNg: "Entrée (Ng)",
  field_name: "Nom",
  field_notes: "Remarques",
  field_product: "Produit",
  field_protocol: "Protocole",
  field_quality: "Qualité",
  "field_sample.name": "Nom d’échantillon",
  field_size: "Taille",
  field_targetBpSize: "Taille de la paire de bases cible",
  indexGridInstructions:
    "La sélection d'un élément de la liste déroulante située dans la partie supérieure définit l'index de cette colonne. La sélection d'un élément de la liste déroulante située dans la partie gauche définit l'index de cette ligne. La sélection de l'option « Aucun » efface l'index.",
  indexI5: "Indice i5",
  indexI7: "Indice i7",
  indexSetListTitle: "Ensembles d’indices",
  indexSetMustBeSet: "L’ensemble d’indices doit être défini.",
  indexSetViewTitle: "L'ensemble d’indices",
  molecularSample: "Échantillon moléculaire",
  molecularSampleListTitle: "Échantillons moléculaires",
  molecularSampleViewTitle: "Échantillon moléculaire",
  notShearedStatus: "Sans cisaillement",
  notSizeSelectedStatus: "Sans sélection de taille",
  pcrBatch: "Lot PCR",
  pcrBatchListTitle: "Lots PCR",
  pcrBatchName: "Nom du lot PCR",
  pcrBatchViewTitle: "Visualiser le lot PCR",
  pcrPrimerListTitle: "Amorces PCR",
  pcrPrimerViewTitle: "Amorce PCR",
  pcrReaction: "Étape de la réaction PCR",
  plpDetailsFormTitle:
    "Ajouter détails sur le cisaillement ou la sélection de taille",
  plpEditModeLabel: "Modifier",
  plpShearingModeLabel: "Détails sur le cisaillement",
  plpSizeModeLabel: "Détails sur la sélection de taille",
  plpStepTitle: "Cisaillement et sélection de taille",
  plpViewModeSelectorLabel: "Mode d’affichage :",
  productListTitle: "Produits",
  productUpcFieldHelpText:
    "Nota : Le code universel de produit peut être lu par un lecteur de codes à barres en mode clavier",
  productViewTitle: "Produit",
  regionListTitle: "Régions",
  regionViewTitle: "Région",
  removeShearingDetailsButtonText:
    "Supprimer les détails sur le cisaillement sélectionnés",
  removeSizeSelectionDetailsButtonText:
    "Supprimer les détails sur la sélection de taille sélectionnés",
  sampleGridInstructions:
    "Faites glisser et déposez des échantillons entre la liste d'échantillons et la grille, ou placez automatiquement les échantillons dans la grille en sélectionnant une option « Remplir par » puis en cliquant sur le bouton « Déplacer tout ».",
  sampleSelectionInstructions:
    "Votre sélection d’échantillons est sauvegardée lorsque vous appuyez sur un bouton de sélection ou de désélection. Il n’y a pas de bouton Enregistrer distinct.",
  sampleSelectionTitle: "Sélection d’échantillons",
  sangerWorkflowSequencingListTitle: "Méthode de Sanger - Séquençage",
  selectAllCheckedSamplesButtonText:
    "Sélectionner tous les échantillons cochés -->",
  selectButtonText: "Sélectionner",
  selectCoordinates: "Sélectionner des coordonnées",
  selectMaterialSamples: "Sélectionner des échantillons de matériau",
  selectSamples: "Sélectionner échantillons moléculaires",
  selectedSamplesTitle: "Échantillons sélectionnés",
  seqBatch: "Lot de SEQ",
  seqBatchListTitle: "Lots de SEQ",
  seqBatchName: "Nom du lot de SEQ",
  seqBatchViewTitle: "Consulter un lot de SEQ",
  seqdbTitle: "Base de données des séquences (fr)",
  shearedStatus: "Cisaillé",
  shearingLabel: "Cisaillement",
  sizeSelectedStatus: "Sélection de taille ajoutée",
  sizeSelectionLabel: "Sélection de taille",
  startNewWorkflow: "Commencer nouveau flux de travail",
  thermocyclerProfileListTitle: "Profils de thermocycleur",
  wellCoordinates: "Coordonnées du puits",
  workflowDetails: "Détails du flux de travail",
  workflowDetailsTab: "Détails",
  workflowListTitle: "Flux de SNG",
  workflowStepTab: "Étape {number} : {name}",
  workflowViewTitle: "Flux de SNG"
};
