import { SEQDB_MESSAGES_ENGLISH } from "./seqdb-en";

/**
 * French translation of SeqDB English messages
 */
export const SEQDB_MESSAGES_FRENCH: Partial<typeof SEQDB_MESSAGES_ENGLISH> = {
  addLibraryPoolTitle: "Ajouter une banque dans une bibliothèque",
  addLibraryPrepBatchTitle: "Ajouter un lot préparé dans une bibliothèque",
  addPcrBatchTitle: "Ajouter le lot PCR",
  addPcrPrimerTitle: "Ajouter une amorce PCR",
  addProductTitle: "Ajouter un produit",
  addProtocolTitle: "Ajouter un protocole",
  addRegionTitle: "Ajouter une région",
  addSeqBatchTitle: "Ajouter un lot de SEQ",
  addSeqSubmissionTitle: "Ajouter une soumission de séquençage",
  addSequencingFacilityTitle: "Ajouter une installation de séquençage",
  addThermocyclerProfileTitle: "Ajouter un profil de thermocycleur",
  addWorkflowTitle: "Ajouter un flux de SNG",
  availableMaterialSamplesTitle: "Échantillons de matériau disponibles",
  availableSamplesTitle: "Échantillons disponibles",
  backToListButtonText: "Retour à la liste",
  cancelButtonText: "Annuler",
  createButtonText: "Créer nouveau",
  deselectAllCheckedSamplesButtonText:
    "<-- Désélectionner tous les échantillons cochés ",
  deselectButtonText: "Désélectionner",
  editLibraryPoolTitle: "Modifier une banque dans une bibliothèque",
  editLibraryPrepBatchTitle: "Modifier un lot préparé dans une bibliothèque",
  editPcrBatchTitle: "Modifier le lot PCR",
  editPcrPrimerTitle: "Modifier l’amorce PCR",
  editProductTitle: "Modifier le produit",
  editProtocolTitle: "Modifier le protocole",
  editRegionTitle: "Modifier la région",
  editSeqBatchTitle: "Modifier un lot de SEQ",
  editSeqSubmissionTitle: "Modifier une soumission de séquençage",
  editSequencingFacilityTitle: "Modifier une installation de séquençage",
  editThermocyclerProfileTitle: "Modifier le profil de thermocycleur",
  editWorkflowTitle: "Modifier le flux de SNG",
  editableTable: "Tableau modifiable",
  field_averageFragmentSize: "Taille moyenne des fragments",
  field_concentration: "Concentration",
  field_contactInfo: "Coordonnées des personnes-ressources",
  field_dateUsed: "Date d'utilisation",
  "field_group.groupName": "Nom du groupe",
  field_inputAmount: "Montant de l’entrée",
  field_inputNg: "Entrée (Ng)",
  field_name: "Nom",
  field_negtiveControl: "Contrôle négatif",
  field_notes: "Remarques",
  field_positiveControl: "Contrôle positif",
  field_product: "Produit",
  field_protocol: "Protocole",
  field_quality: "Qualité",
  field_role: "Rôle",
  "field_sample.name": "Nom d’échantillon",
  "field_shippingAddress.addressLine1": "Ligne 1 de l'adresse",
  "field_shippingAddress.addressLine2": "Ligne 2 de l'adresse",
  "field_shippingAddress.city": "Ville",
  "field_shippingAddress.country": "Pays",
  "field_shippingAddress.provinceState": "Province/État",
  "field_shippingAddress.zipCode": "Code postal",
  field_size: "Taille",
  field_targetBpSize: "Taille de la paire de bases cible",
  hideUsed: "Cacher utilisé",
  indexGridInstructions:
    "La sélection d'un élément de la liste déroulante située dans la partie supérieure définit l'index de cette colonne. La sélection d'un élément de la liste déroulante située dans la partie gauche définit l'index de cette ligne. La sélection de l'option « Aucun » efface l'index.",
  indexI5: "Indice i5",
  indexI7: "Indice i7",
  indexSetListTitle: "Ensembles d’indices",
  indexSetMustBeSet: "L’ensemble d’indices doit être défini.",
  indexSetViewTitle: "L'ensemble d’indices",
  libraryPool: "Banques des bibliothèques",
  libraryPoolContent: "Contenu d'une banque d'une bibliothèque",
  libraryPoolingName: "Nom des banques des bibliothèques",
  libraryPoolsListTitle: "Banques des bibliothèques",
  libraryPrepBatch: "Lot préparé d'une bibliothèque",
  libraryPrepBatchListTitle: "Lots préparés des bibliothèques",
  materialSampleNameAndVersion: "Nom et version de l'échantillon",
  ngsWorkflowListTitle: "Flux de séquençage de nouvelle génération (SNG)",
  ngsWorkflowWholeGenomeSeqPoolingTitle:
    "Flux de SNG - Banques pour le séquençage de tout le génome",
  ngsWorkflowWholeGenomeSeqTitle: "Flux de SNG - séquençage de tout le génome",
  noUlRnxProtocolData:
    "Aucune donnée d'ul par réaction valide pour le protocole",
  notShearedStatus: "Sans cisaillement",
  notSizeSelectedStatus: "Sans sélection de taille",
  pcrBatch: "Lot PCR",
  pcrBatchListTitle: "Lots PCR",
  pcrBatchName: "Nom du lot PCR",
  pcrBatchViewTitle: "Visualiser le lot PCR",
  pcrPrimerListTitle: "Amorces PCR",
  pcrPrimerViewTitle: "Amorce PCR",
  pcrReaction: "Étape de la réaction PCR",
  pcrReactionTitle: "PCR",
  pcrTubeNumber: "Nombre de tubes à PCR",
  pcrWellCoordinates: "Coordonnées des puits pour la PCR",
  pcrWorkflow: "Flux de travail pour la PCR",
  pcrWorkflowListTitle: "Flux de travail pour les PCR",
  pcrWorksheetTitle: "Détails de la PCR ",
  plpDetailsFormTitle:
    "Ajouter détails sur le cisaillement ou la sélection de taille",
  plpEditModeLabel: "Modifier",
  plpShearingModeLabel: "Détails sur le cisaillement",
  plpSizeModeLabel: "Détails sur la sélection de taille",
  plpStepTitle: "Cisaillement et sélection de taille",
  plpViewModeSelectorLabel: "Mode d’affichage :",
  preLibraryPrep: "BBibliothèques - Préparation préalable ",
  primerName: "Nom de l'amorce ",
  print: "Imprimer",
  productListTitle: "Produits",
  productUpcFieldHelpText:
    "Nota : Le code universel de produit peut être lu par un lecteur de codes à barres en mode clavier",
  productViewTitle: "Produit",
  regionListTitle: "Régions",
  regionViewTitle: "Région",
  removeShearingDetailsButtonText:
    "Supprimer les détails sur le cisaillement sélectionnés",
  removeSizeSelectionDetailsButtonText:
    "Supprimer les détails sur la sélection de taille sélectionnés",
  result: "Résultat",
  rxnsFormular: "Nombre de réactions = x échantillons + contrôle + erreur",
  sampleGridInstructions:
    "Faites glisser et déposez des échantillons entre la liste d'échantillons et la grille, ou placez automatiquement les échantillons dans la grille en sélectionnant une option « Remplir par » puis en cliquant sur le bouton « Déplacer tout ».",
  sampleSelectionInstructions:
    "Votre sélection d’échantillons est sauvegardée lorsque vous appuyez sur un bouton de sélection ou de désélection. Il n’y a pas de bouton Enregistrer distinct.",
  sampleSelectionTitle: "Sélection d’échantillons",
  sampleVersion: "Version de l'échantillon",
  sangerWorkflowSequencingListTitle: "Méthode de Sanger - Séquençage",
  selectAllCheckedSamplesButtonText:
    "Sélectionner tous les échantillons cochés -->",
  selectButtonText: "Sélectionner",
  selectCoordinates: "Sélectionner des coordonnées",
  selectLibraryPool: "Sélectionner une banque dans une bibliothèque",
  selectLibraryPrepBatch: "Sélectionner un lot préparé dans une bibliothèque",
  selectMaterialSamples: "Sélectionner des échantillons de matériau",
  selectPcrBatch: "Sélectionner Lot de PCR",
  selectPcrBatchTitle: "Sélectionner Lot de PCR",
  selectSamples: "Sélectionner échantillons moléculaires",
  selectedPoolContents: "Contenu des banques sélectionnées",
  selectedSamplesTitle: "Échantillons sélectionnés",
  seqBatch: "Lot de SEQ",
  seqBatchListTitle: "Lots de SEQ",
  seqBatchName: "Nom du lot de SEQ",
  seqBatchViewTitle: "Consulter un lot de SEQ",
  seqSubmissionListTitle: "Soumission de séquençage",
  seqTubeNumber: "Nombre de tubes pour le séquençage",
  seqWellCoordinates: "Coordonnées des puits pour le séquençage",
  seqWorkSheetErrors: "erreurs)",
  seqWorkSheetPleaseAdd: "(veuillez ajouter",
  seqWorksheetComponents: "Composants",
  seqWorksheetConcentration: "Concentration",
  seqWorksheetEnterSampleDataHere: "Saisir les données sur l'échantillon ici :",
  seqWorksheetExportersMessage:
    "Les exportateurs incluront tous les enregistrements de toutes les pages",
  seqWorksheetPrimer: "Amorce",
  seqWorksheetRxns: "Nombre de réactions ",
  seqWorksheetTitle: "Formulaire Réaction de séquençage ",
  seqWorksheetUlRxn: "ul par réaction",
  seqdbTitle: "Base de données des séquences (fr)",
  sequencingFacilityContacts: "Personnes-ressources",
  sequencingFacilityListTitle: "Installations de séquençage",
  sequencingFacilityShippingAddress: "Adresse d'expédition",
  shearedStatus: "Cisaillé",
  shearingDetails: "Détails sur le cisaillement",
  shearingLabel: "Cisaillement",
  sizeSelectedStatus: "Sélection de taille ajoutée",
  sizeSelectionDetails: "Détails sur le choix des tailles",
  sizeSelectionLabel: "Sélection de taille",
  specimenIdentifier: "Identifiant du spécimen",
  startNewWorkflow: "Commencer nouveau flux de travail",
  thermocyclerProfileListTitle: "Profils de thermocycleur",
  total: "Total",
  wellCoordinates: "Coordonnées du puits",
  wellLocation: "Emplacement du puits",
  workflowDetails: "Détails du flux de travail",
  workflowDetailsTab: "Détails",
  workflowStepTab: "Étape {number} : {name}",
  workflowViewTitle: "Flux de SNG"
};
