/**
 * English SeqDB messages. A message must be set here in English before other languages.
 */
export const SEQDB_MESSAGES_ENGLISH = {
  addIndexSetTitle: "Add Index Set",
  addLibraryPoolTitle: "Add Library Pool",
  addLibraryPrepBatchTitle: "Add Library Prep Batch",
  addNgsIndexTitle: "Add NGS Index",
  addPcrBatchTitle: "Add PCR Batch",
  addPcrPrimerTitle: "Add PCR Primer",
  addProductTitle: "Add Product",
  addProtocolTitle: "Add Protocol",
  addRegionTitle: "Add Region",
  addSeqBatchTitle: "Add SEQ Batch",
  addSeqSubmissionTitle: "Add SEQ Submission",
  addSequencingFacilityTitle: "Add Sequencing Facility",
  addThermocyclerProfileTitle: "Add Thermocycler Profile",
  addWorkflowTitle: "Add NGS Workflow",
  availableMaterialSamplesTitle: "Available Material Samples",
  availableSamplesTitle: "Available Molecular Samples",
  backToListButtonText: "Back to List",
  cancelButtonText: "Cancel",
  createButtonText: "Create New",
  deselectAllCheckedSamplesButtonText:
    "<-- Deselect all checked molecular samples",
  deselectButtonText: "Deselect",
  editIndexSetTitle: "Edit Index Set",
  editLibraryPoolTitle: "Edit Library Pool",
  editLibraryPrepBatchTitle: "Edit Library Prep Batch",
  editNgsIndexTitle: "Edit NGS Index",
  editPcrBatchTitle: "Edit PCR Batch",
  editPcrPrimerTitle: "Edit PCR Primer",
  editProductTitle: "Edit Product",
  editProtocolTitle: "Edit Protocol",
  editRegionTitle: "Edit Region",
  editSeqBatchTitle: "Edit SEQ Batch",
  editSeqSubmissionTitle: "Edit SEQ Submission",
  editSequencingFacilityTitle: "Edit Sequencing Facility",
  editThermocyclerProfileTitle: "Edit Thermocycler Profile",
  editWorkflowTitle: "Edit NGS Workflow",
  editableTable: "Editable Table",
  field_averageFragmentSize: "Average Fragment Size",
  field_concentration: "Concentration",
  field_contactInfo: "Contact Info",
  field_dateUsed: "Date Used",
  field_direction: "Direction",
  "field_group.groupName": "Group Name",
  field_inputAmount: "Input Amount",
  field_inputNg: "Input (Ng)",
  field_lotNumber: "Lot Number",
  field_name: "Name",
  field_negtiveControl: "Neg Control",
  field_notes: "Notes",
  field_positiveControl: "Pos Control",
  field_product: "Product",
  field_protocol: "Protocol",
  field_purification: "Purification",
  field_quality: "Quality",
  field_role: "Role",
  "field_sample.name": "Sample Name",
  "field_shippingAddress.addressLine1": "Address Line 1",
  "field_shippingAddress.addressLine2": "Address Line 2",
  "field_shippingAddress.city": "City",
  "field_shippingAddress.country": "Country",
  "field_shippingAddress.provinceState": "Province/State",
  "field_shippingAddress.zipCode": "Zip Code",
  field_size: "Size",
  field_targetBpSize: "Target Base Pair Size",
  hideUsed: "Hide used",
  indexGridInstructions:
    "Selecting a dropdown item along the top side sets the index for that column. Selecting a dropdown item along the left side sets the index for that row. Selecting None erases the Index.",
  indexI5: "Index i5",
  indexI7: "Index i7",
  indexSetListTitle: "Index Sets",
  indexSetMustBeSet: "Index Set must be set.",
  indexSetViewTitle: "Index Set",
  libraryPool: "Library Pool",
  libraryPoolContent: "Library Pool Content",
  libraryPoolingName: "Library Pooling Name",
  libraryPoolsListTitle: "Library Pools",
  libraryPrepBatch: "Library Prep Batch",
  libraryPrepBatchListTitle: "Library Prep Batches",
  materialSampleNameAndVersion: "Sample Name and Version",
  ngsIndexes: "NGS Indexes",
  ngsWorkflowListTitle: "NGS Workflow",
  ngsWorkflowWholeGenomeSeqPoolingTitle:
    "NGS Workflows - Whole Genome Sequencing Pooling",
  ngsWorkflowWholeGenomeSeqTitle: "NGS Workflows - Whole Genome Sequencing",
  noUlRnxProtocolData: "No valid protocol data of ulRnx.",
  notShearedStatus: "Not Sheared",
  notSizeSelectedStatus: "No Size Selection",
  pcrBatch: "PCR Batch",
  pcrBatchListTitle: "PCR Batches",
  pcrBatchName: "PCR Batch Name",
  pcrBatchViewTitle: "View PCR Batch",
  pcrPrimerListTitle: "PCR Primers",
  pcrPrimerViewTitle: "PCR Primer",
  pcrReaction: "PCR Reaction Results",
  pcrReactionTitle: "PCR Reaction",
  pcrTubeNumber: "PCR Tube Number",
  pcrWellCoordinates: "PCR Well Coordinates",
  pcrWorkflow: "PCR Workflow",
  pcrWorkflowListTitle: "PCR Workflows",
  pcrWorksheetTitle: "Detailed PCR Reaction Information",
  plpDetailsFormTitle: "Add New Shearing/Size Selection Details",
  plpEditModeLabel: "Edit",
  plpShearingModeLabel: "Shearing Details",
  plpSizeModeLabel: "Size Selection Details",
  plpStepTitle: "Shearing/Size Selection",
  plpViewModeSelectorLabel: "View mode: ",
  preLibraryPrep: "Pre Library Prep",
  primerName: "Primer Name",
  print: "Print",
  productListTitle: "Products",
  productUpcFieldHelpText:
    "Note: Universal Product Code can be read from barcode scanner in keyboard mode",
  productViewTitle: "Product",
  regionListTitle: "Regions",
  regionViewTitle: "Region",
  removeShearingDetailsButtonText: "Remove selected Shearing details",
  removeSizeSelectionDetailsButtonText:
    "Remove selected Size Selection details",
  result: "Result",
  rxnsFormular: "# Rxns = x samples + control + error",
  sampleGridInstructions:
    'Drag and drop Samples between the Sample List and the Grid, or automatically place the Samples into the Grid by selecting a "Fill By" option and then clicking the "Move All" button.',
  sampleSelectionInstructions:
    "Your Sample selection is Saved when you press a Select or Deselect button. There is no separate Save button.",
  sampleSelectionTitle: "Sample Selection",
  sampleVersion: "Sample Version",
  sangerWorkflowSequencingListTitle: "Sanger Workflows - Sequencing",
  selectAllCheckedSamplesButtonText: "Select all checked molecular samples -->",
  selectButtonText: "Select",
  selectCoordinates: "Select Coordinates",
  runStep: "Run",
  selectLibraryPool: "Select Library Pool",
  selectLibraryPrepBatch: "Select Library Prep Batch",
  selectMaterialSamples: "Select Material Samples",
  indexAssignmentStep: "Index Assignment",
  assignByGrid: "Assign by grid",
  assignByTable: "Assign by table",
  selectI5: "Select i5",
  selectI7: "Select i7",
  missingIndexForAssignment:
    "Index Set must be set on the Library Prep Batch to assign indexes.",
  missingContainerAndIndexForAssignment:
    "Container Type and Index Set must be set to use the index grid.",
  missingSelectedCoordinatesForAssignment:
    "Coordinates needed to be selected in order to assign indexes using the grid.",
  selectPcrBatch: "Select PCR Batch",
  selectPcrBatchTitle: "Select PCR Batch",
  selectSamples: "Select Material Samples",
  selectedPoolContents: "Selected Pool Contents",
  selectedSamplesTitle: "Selected Material Samples",
  seqBatch: "SEQ Batch",
  seqBatchListTitle: "SEQ Batches",
  seqBatchName: "SEQ Batch Name",
  seqBatchViewTitle: "View SEQ Batch",
  seqSubmissionListTitle: "SEQ Submission",
  seqTubeNumber: "SEQ Tube Number",
  seqWellCoordinates: "SEQ Well Coordinates",
  libraryPrepWorksheetTitle: "Library Prep Worksheet",
  seqWorkSheetErrors: " errors)",
  seqWorkSheetPleaseAdd: "(please add ",
  seqWorksheetComponents: "Components",
  seqWorksheetConcentration: "Concentration",
  seqWorksheetEnterSampleDataHere: "Enter Sample data here:",
  seqWorksheetExportersMessage:
    "Exporters will include all records from all pages",
  seqWorksheetPrimer: "Primer",
  seqWorksheetRxns: "# Rxns ",
  seqWorksheetTitle: "Sequencing Reaction Form",
  seqWorksheetUlRxn: "ul/rxn",
  seqdbTitle: "Sequencing",
  sequencingFacilityContacts: "Contacts",
  sequencingFacilityListTitle: "Sequencing Facilities",
  sequencingFacilityShippingAddress: "Shipping Address",
  shearedStatus: "Sheared",
  shearingDetails: "Shearing Details",
  shearingLabel: "Shearing",
  sizeSelectedStatus: "Size Selection Added",
  sizeSelectionDetails: "Size Selection Details",
  addGoodAndWeakButton: "Good/Weak",
  sizeSelectionLabel: "Size Selection",
  specimenIdentifier: "Specimen Identifier",
  startNewWorkflow: "Start New Workflow",
  thermocyclerProfileListTitle: "Thermocycler Profiles",
  total: "Total",
  wellCoordinates: "Well Coordinates",
  wellLocation: "Well Location",
  workflowDetails: "Workflow Details",
  workflowDetailsTab: "Details",
  workflowStepTab: "Step {number}: {name}",
  workflowViewTitle: "NGS Workflow",
  sequencingFacility: "Sequencing Facility",
  molecularAnalysisRunListTitle: "Molecular Analysis Runs",
  field_molecularAnalysisRunName: "Molecular Analysis Run Name",
  molecularAnalysisRunItems: "Molecular Analysis Run Items",
  molecularAnalysisWorkflowTitle: "Molecular Analysis Workflow",
  molecularAnalysisName: "Molecular Analysis Name",
  molecularAnalysis: "Molecular Analysis",
  metagenomicsWorkflowTitle: "Metagenomics Workflow",
  metagenomicsWorkflowName: "Metagenomics Workflow Name",
  metagenomicsBatch: "Metagenomics Batch",
  resultsStep: "Results"
};
