/**
 * English SeqDB messages. A message must be set here in English before other languages.
 */
export const SEQDB_MESSAGES_ENGLISH = {
  addMolecularSampleTitle: "Add Molecular Sample",
  addPcrBatchTitle: "Add PCR Batch",
  addPcrPrimerTitle: "Add PCR Primer",
  addPcrProfileTitle: "Add Thermocycler Profile",
  addProductTitle: "Add Product",
  addProtocolTitle: "Add Protocol",
  addRegionTitle: "Add Region",
  addWorkflowTitle: "Add NGS Workflow",
  availableSamplesTitle: "Available Molecular Samples",
  backToListButtonText: "Back to List",
  cancelButtonText: "Cancel",
  createButtonText: "Create New",
  deselectAllCheckedSamplesButtonText:
    "<-- Deselect all checked molecular samples",
  deselectButtonText: "Deselect",
  editMolecularSampleTitle: "Edit Molecular Sample",
  editPcrBatchTitle: "Edit PCR Batch",
  editPcrPrimerTitle: "Edit PCR Primer",
  editPcrProfileTitle: "Edit Thermocycler Profile",
  editProductTitle: "Edit Product",
  editProtocolTitle: "Edit Protocol",
  editRegionTitle: "Edit Region",
  editWorkflowTitle: "Edit NGS Workflow",
  editableTable: "Editable Table",
  field_averageFragmentSize: "Average Fragment Size",
  field_concentration: "Concentration",
  "field_group.groupName": "Group Name",
  field_inputAmount: "Input Amount",
  field_inputNg: "Input (Ng)",
  field_name: "Name",
  field_notes: "Notes",
  field_product: "Product",
  field_protocol: "Protocol",
  field_quality: "Quality",
  "field_sample.name": "Sample Name",
  field_size: "Size",
  field_targetBpSize: "Target Base Pair Size",
  indexGridInstructions:
    "Selecting a dropdown item along the top side sets the index for that column. Selecting a dropdown item along the left side sets the index for that row. Selecting None erases the Index.",
  indexI5: "Index i5",
  indexI7: "Index i7",
  indexSetListTitle: "Index Sets",
  indexSetMustBeSet: "Index Set must be set.",
  indexSetViewTitle: "Index Set",
  molecularSample: "Molecular Sample",
  molecularSampleListTitle: "Molecular Samples",
  molecularSampleViewTitle: "Molecular Sample",
  notShearedStatus: "Not Sheared",
  notSizeSelectedStatus: "No Size Selection",
  pcrBatch: "PCR Batch",
  pcrBatchListTitle: "PCR Batches",
  pcrBatchName: "PCR Batch Name",
  pcrBatchViewTitle: "View PCR Batch",
  pcrPrimerListTitle: "PCR Primers",
  pcrPrimerViewTitle: "PCR Primer",
  pcrProfileListTitle: "Thermocycler Profiles",
  pcrProfileViewTitle: "Thermocycler Profile",
  plpDetailsFormTitle: "Add New Shearing/Size Selection Details",
  plpEditModeLabel: "Edit",
  plpShearingModeLabel: "Shearing Details",
  plpSizeModeLabel: "Size Selection Details",
  plpStepTitle: "Shearing/Size Selection",
  plpViewModeSelectorLabel: "View mode: ",
  productListTitle: "Products",
  productUpcFieldHelpText:
    "Note: Universal Product Code can be read from barcode scanner in keyboard mode",
  productViewTitle: "Product",
  regionListTitle: "Regions",
  regionViewTitle: "Region",
  removeShearingDetailsButtonText: "Remove selected Shearing details",
  removeSizeSelectionDetailsButtonText:
    "Remove selected Size Selection details",
  sampleGridInstructions:
    'Drag and drop Samples between the Sample List and the Grid, or automatically place the Samples into the Grid by selecting a "Fill By" option and then clicking the "Move All" button.',
  sampleSelectionInstructions:
    "Your Sample selection is Saved when you press a Select or Deselect button. There is no separate Save button.",
  sampleSelectionTitle: "Sample Selection",
  sangerWorkflow: "Sanger Workflow",
  sangerWorkflowListTitle: "Sanger Workflows",
  selectAllCheckedSamplesButtonText: "Select all checked molecular samples -->",
  selectButtonText: "Select",
  selectSamples: "Select Molecular Samples",
  selectedSamplesTitle: "Selected Molecular Samples",
  seqdbTitle: "Sequencing",
  shearedStatus: "Sheared",
  shearingLabel: "Shearing",
  sizeSelectedStatus: "Size Selection Added",
  sizeSelectionLabel: "Size Selection",
  startNewWorkflow: "Start New Workflow",
  wellCoordinates: "Well Coordinates",
  workflowDetails: "Workflow Details",
  workflowDetailsTab: "Details",
  workflowListTitle: "NGS Workflows",
  workflowStepTab: "Step {number}: {name}",
  workflowViewTitle: "NGS Workflow"
};
