= Pa11y-ci automation

We used pa11y-ci to automate the WCAG compliance detection and 
pa11y-ci-reporter-html to generate report of configured level of severity with good readability.

== Follow below steps in sequence

=== Go to packages/dina-ui for object store UI ( packages/seqdb-ui for seqdb UI )

`cd packages/dina-ui`

=== Check compliance for all configured pages and output json format results  

`yarn a11y-check`

=== Generate user fridendly html report based on above results 

`yarn a11y-generate-report`

Note for linux user, due to a bug in pa11y-ci-html-reporter npm package,  will need to run below first:

`sudo apt install dos2unix`

`dos2unix /home/shemy/git/dina-ui/node_modules/pa11y-ci-reporter-html/bin/pa11y-ci-reporter-html.js`

=== Know issues

Due to the pa11y implementation, in order to get all compliance level report (A, AA  are the currentl AAFC scope), one will need to change the .pa11yci file to manually switch between the A and AA  to cover both,as the script takes one arg only.

e.g, modify the .pa11yci file to change Standards: "WCAG2AA" to Standards: "WCAG2A", as Standards: "WCAG2AA" is the default, and WCAG2AAA is out of scope as of writting the doc.
