= Yarn Package Scripts

== Top-level directory

Commands you can run from the root package:

=== `yarn docs`

Compiles the docs (written in https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc]) as a
single HTML file in the "generated-docs" directory.

=== `yarn test`

Runs the tests for all packages (without generating the test coverage reports).

=== `yarn test:coverage`

Runs the tests for all packages. Prints the test coverage report to stdout, and writes the coverage report files
into the "coverage" directory.

== Sub-package directories

Commands you can run from sub-packages:

=== `yarn build`

Generates the production build.

=== `yarn dev`

Runs the UI application at localhost:3000 in dev mode using https://github.com/zeit/next.js[Next.js].
When you save a file, you can refresh the page to see your changes without restarting the app.
Note that this does not let the UI connect to the backend because there is no HTTP proxy set up. See
"https://github.com/poffm/dina-dev" for the full dev mode with a proxy.

=== `yarn next`

Runs the UI application at localhost:3000 in dev mode using https://github.com/zeit/next.js[Next.js].
When you save a file, you can refresh the page to see your changes without restarting the app.
Note that this does not let the UI connect to the backend because there is no HTTP proxy set up. See
"https://github.com/poffm/dina-dev" for the full dev mode with a proxy.

=== `yarn test`

Runs the tests (without generating the test coverage report).

=== `yarn test:coverage`

Runs the tests. Prints the test coverage report to stdout, and writes the coverage report files
into the "coverage" directory.
